opensource4you/astraea

README.md
app/build.gradle
app/src/main/java/org/astraea/App.java
app/src/main/java/org/astraea/performance/latency/CloseableThread.java
app/src/main/java/org/astraea/performance/latency/ComponentFactory.java
app/src/main/java/org/astraea/performance/latency/Consumer.java
app/src/main/java/org/astraea/performance/latency/ConsumerThread.java
app/src/main/java/org/astraea/performance/latency/DataManager.java
app/src/main/java/org/astraea/performance/latency/End2EndLatency.java
app/src/main/java/org/astraea/performance/latency/KafkaUtils.java
app/src/main/java/org/astraea/performance/latency/MeterTracker.java
app/src/main/java/org/astraea/performance/latency/Producer.java
app/src/main/java/org/astraea/performance/latency/ProducerThread.java
app/src/main/java/org/astraea/performance/latency/TopicAdmin.java
app/src/test/java/org/astraea/performance/latency/CloseableThreadTest.java
app/src/test/java/org/astraea/performance/latency/ConsumerThreadTest.java
app/src/test/java/org/astraea/performance/latency/DataManagerTest.java
app/src/test/java/org/astraea/performance/latency/End2EndLatencyTest.java
app/src/test/java/org/astraea/performance/latency/FakeComponentFactory.java
app/src/test/java/org/astraea/performance/latency/KafkaUtilsTest.java
app/src/test/java/org/astraea/performance/latency/MeterTrackerTest.java
app/src/test/java/org/astraea/performance/latency/ProducerThreadTest.java

see https://github.com/chia7712/astraea/tree/latency_benchmark#latency-benchmark for docs

Add latency benchmark

---

app/src/main/java/org/astraea/performance/latency/CloseableThread.java
app/src/test/java/org/astraea/performance/latency/CloseableThreadTest.java

Throw exception while `execute()` calls `close()`.

Throw exception while `execute` calls `close`

---

app/src/test/java/org/astraea/performance/latency/CloseableThreadTest.java

看過"testExecuteAndCleanup()"的測試後，發現並不適合直接測試，還是需要新增執行緒。
`ConsumerThread`, `ProducerThread`的測試都已經是直接測試。
因此只有改動`testExecuteOnce()`。

Directly test `run()` instead of using thread pool

---

README.md
docker/start_broker.sh
docker/start_kafka_tool.sh
docker/start_tool.sh
docker/start_zookeeper.sh

考量我們可能需要測試最新的kafka，因此腳本需要能基於source code來運行kafka，簡單說就是定義`KAFKA_REVISION`後再執行腳本，腳本就會去下載原始碼編譯並建置kafka。詳細說明請見readme

Enable to run kafka from source code

---

README.md
app/src/main/java/org/astraea/App.java
app/src/main/java/org/astraea/argument/ArgumentUtil.java
app/src/main/java/org/astraea/metrics/kafka/KafkaMetricClientAppArgument.java
app/src/main/java/org/astraea/offset/OffsetExplorerArgument.java
app/src/main/java/org/astraea/topic/ReplicaCollie.java
app/src/main/java/org/astraea/topic/TopicAdmin.java
app/src/test/java/org/astraea/AppTest.java
app/src/test/java/org/astraea/argument/ArgumentUtilTest.java
app/src/test/java/org/astraea/offset/OffsetExplorerTest.java
app/src/test/java/org/astraea/topic/ReplicaCollieTest.java

這個工具可以方便地將某些replicas從指定的brokers中移到其他節點，相比kafka官方工具需要去寫json檔案，這隻工具可以快速實現“隔離”某些brokers的需求

ReplicaCollie - used to migrate replicas between brokers

---

README.md
docker/start_broker.sh
docker/start_kafka_tool.sh
docker/start_prometheus.sh
docker/start_zookeeper.sh

1. 埋入exporter到broker
2. 新增script啟動prometheus
3. update readme

Integrate prometheus service to docker script

---

app/src/main/java/org/astraea/performance/Metrics.java
app/src/main/java/org/astraea/performance/Performance.java
app/src/main/java/org/astraea/performance/Tracker.java
app/src/test/java/org/astraea/performance/MetricsTest.java
app/src/test/java/org/astraea/performance/PerformanceTest.java

原本的average bytes算法是“這一秒取得的資料量“，但對於吞吐量測試中，我們其實並不在意”某一秒”的狀況，反之，從開始到現在的平均量才是我們在意的。因此這隻PR調整了平均量的算法，此外也包含以下幾個修正：
1. 簡化`max`和`min`的算法
2. 簡化一部分的測試

Correct the average bytes

---

app/src/main/java/org/astraea/performance/Metrics.java
app/src/main/java/org/astraea/performance/Tracker.java
app/src/test/java/org/astraea/performance/TrackerTest.java

Problem in [#41 comment](https://github.com/skiptests/astraea/issues/41#issuecomment-959763076).
Solved: 
When there is no consumer, the tracker will not print out the consumers information.
And will terminate after the producers are done.

Fix zero consumer behaviour

---

app/src/main/java/org/astraea/topic/Builder.java
app/src/test/java/org/astraea/topic/TopicAdminTest.java

之前的版本我們允許重複建立topic (透過檢查，存在則忽略）
現在這個版本還原之前的邏輯，並新增更完整的確認，包含:
1. number of partitions
1. number of replicas
1. all configs
上述只要有任何一個不一樣則拋出錯誤

Enable to create topic repeatedly

---

app/src/test/java/org/astraea/metrics/kafka/KafkaMetricsTest.java
app/src/test/java/org/astraea/topic/ReplicaCollieTest.java
app/src/test/java/org/astraea/topic/TopicAdminTest.java

為了照顧windows使用者，因此這隻PR disable無法在windows上執行的tests，不過下列幾隻我不太確定為何不能在windows跑，因此會另外開議題來追蹤
1. `ReplicaCollieTest ` https://github.com/skiptests/astraea/issues/102
2. `TopicAdminTest#testReassign` https://github.com/skiptests/astraea/issues/103

Make sure test can run on windows

---

app/src/main/java/org/astraea/performance/Tracker.java

測試時，為了方便紀錄produce/consume所花費的時間，故先新增"印出時間"。

印出produce/consume時間

---

app/src/main/java/org/astraea/topic/Builder.java
app/src/main/java/org/astraea/topic/Migrator.java
app/src/main/java/org/astraea/topic/ReplicaCollie.java
app/src/main/java/org/astraea/topic/TopicAdmin.java
app/src/test/java/org/astraea/topic/TopicAdminTest.java

考量我們要完整支援partition assignments，因此將該操作的設定獨立成一個介面(`migrator`)以便可擴充支援所有行為

Add migrator interface

---

app/build.gradle

有時候跑測試會遇到以下錯誤:
```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 42.
at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base@11.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.ja …
```

Increase the JVM memory for testing

---

README.md
docker/start_broker.sh

允許使用者將host folders掛載給broker containers，如此可達到下列兩個效果
1. 保存資料
2. 同時使用多顆硬碟作為資料存取

Enable to mount host folders to broker container

---

README.md
app/src/main/java/org/astraea/App.java
app/src/main/java/org/astraea/argument/ArgumentUtil.java
app/src/main/java/org/astraea/topic/ReplicaSyncingMonitor.java
app/src/test/java/org/astraea/argument/ArgumentUtilTest.java
app/src/test/java/org/astraea/topic/ReplicaSyncingMonitorIntegrationTest.java
app/src/test/java/org/astraea/topic/ReplicaSyncingMonitorTest.java

resolve #89 
This PR implements a tool to monitor replica syncing progress, it can be used to monitor replica migration progress.
```
Usage: <main class> [options]
Options:
* --bootstrap.servers String: server to connect to
--interval          Time: the time interval between replica state check, 
support multiple time unit like 10s, 500ms and 100us. 
If no time unit specified, second unit will be used. 
(default: PT1S)
--prop.file         the file path containing the properties to be passed 
to kafka admin
--topics            String: topics to track, use all non-synced topics by 
default (default: [])
--track             Boolean: keep track even if all the replicas are 
synced, also attempts to discover any non-synced 
replicas (default: false)
```
```java
package org.astraea;
import …
```

Implementation of replica syncing monitor

---

app/src/main/java/org/astraea/metrics/jmx/MBeanClient.java
app/src/test/java/org/astraea/service/RequireJmxServer.java
app/src/test/java/org/astraea/service/RequireJmxServerTest.java

將測試用途的jmx server也改成用JNDI，這樣與我們實際使用一致

The embedded jmx server should use JNDI

---

docker/start_broker.sh
docker/start_spark.sh
docker/submit_spark_job.sh

這是為下一個題目做準備，這個腳本可以幫我們啟動spark cluster

Add script to run spark cluster

---

docker/submit_spark_job.sh

Rename the image name from spark to spark-job

---

app/src/main/java/org/astraea/metrics/collector/BeanCollector.java
app/src/test/java/org/astraea/metrics/collector/TestBeanCollector.java

from https://github.com/skiptests/astraea/pull/138#discussion_r771094107
現在不同的receiver會維護各自的objects，而非跟其他receivers共用

The receiver should keep independent objects

---

README.md
app/src/main/java/org/astraea/performance/Manager.java
app/src/main/java/org/astraea/performance/Performance.java
app/src/main/java/org/astraea/utils/DataSize.java
app/src/main/java/org/astraea/utils/DataUnit.java
app/src/test/java/org/astraea/performance/ManagerTest.java
app/src/test/java/org/astraea/utils/DataSizeTest.java

為`DataSize`新增字串轉`DataSize`的方法，
並把Performance tool中的參數`--record.size`，改使用`DataSize`表示。(#155)

Use `DataSize` to rewrite `--record.size` for performance tool

---

README.md
docker/grafana.sh
docker/start_grafana.sh
docker/start_node_exporter.sh
docker/start_prometheus.sh

Context: #10
This PR implement/improve the scripts for the following tools
* Grafana
* Node Exporter
* Prometheus
Test this on our cluster, work well.
dashboard source here.
1. https://grafana.com/grafana/dashboards/1860
2. https://grafana.com/grafana/dashboards/721
```shell
./docker/start_node_exporter.sh
[INFO] Container ID of node_exporter: 16d0e741ba516495465fad6977bcea7abd80b4c872ab44bdc2713db08557e6a9
[INFO] node_exporter running at http://192.168.0.2:9100
./docker/start_prometheus.sh start 192.168.0.2:5566 192.168.0.2:9100
[INFO] Start existing prometheus instance
prometheus-9090
[INFO] =================================================
[INFO] config file: /tmp/prometheus-9090.yml
[INFO] prometheus address: http://192.168.0.2:9090
[INFO] command to run grafana at this host: …
```

Observability tools

---

.gitignore
app/src/main/java/org/astraea/App.java
docker/start_astraea.sh

這種腳本可以提供兩個好處:
1. 使用者只需要有docker就可以使用astraea的各種功能
2. 我們可以將所有東西封裝在docker image裡面，這樣使用者可以在無對外網路下使用astraea

Add script to run astraea by docker

---

docker/start_broker.sh

在有些比較慢的環境中，broker的啟動會需要較多時間，因此我們在擷取id的時候應該多點耐心

Wait some more time for broker id

---

README.md
app/src/main/java/org/astraea/performance/Distribution.java
app/src/main/java/org/astraea/performance/Manager.java
app/src/main/java/org/astraea/performance/Performance.java
app/src/test/java/org/astraea/performance/DistributionTest.java
app/src/test/java/org/astraea/performance/ManagerTest.java

#135  新增一個參數用以設定record key的分佈情況。
使用方法
`performance --bootstrap.servers localhost:9092 --key.distribution key-01:0.2,key-02:0.3`
可以讓20%的record使用"key-01"作為record key；30%的record使用"key-02"作為record key；剩下50%的record不使用key。

新增record key分佈設定

---

docker/start_kafka_tool.sh

Don't show help message when running kafka-tool

---

app/src/main/java/org/astraea/performance/Manager.java

若每次record都重新產生隨機內容，發送效率會大幅下降。
為解決random record的負擔，又可以製造random record的結果，改成每次只改一個byte。如此一來，既可以產生不同的record，也可以降低產生訊息所需的時間。

Generate random record by replacing one byte

---

app/src/test/java/org/astraea/performance/PerformanceTest.java

#195 該bug的產生原因為adminClient可能會存在還沒有來得及創建topic,之後的程序就需要抓topic了，所以這裡給它一個等待的時間。

fix flaky PerformanceTest  

---

app/src/main/java/org/astraea/performance/FileWriter.java
app/src/main/java/org/astraea/performance/Metrics.java
app/src/main/java/org/astraea/performance/Tracker.java
app/src/test/java/org/astraea/performance/MetricsTest.java

同時紀錄 "平均throughput" 和 "現在的每秒throughput"。
另外，把輸出檔案的throughput都改成 "現在的每秒throughput"，因讀取檔案的時候可以靠工具幫忙計算出平均量。console log則需要平均量，所以都保留且印出。

Add new metric for current throughput

---

app/src/main/java/org/astraea/performance/Manager.java
app/src/test/java/org/astraea/performance/ManagerTest.java

#209 
> `Manager#consumedDone` is always `false` when there is no consumer ...
Fixed by adding check on number of consumers.

Fix consumerDone() false when no consumer

---

docker/start_broker.sh

修正rejectProperty() 使其可以正常的拒絕設定特定的property
修正前:
```
$ ./start_broker.sh zookeeper.connect=192.168.103.141:19316 sean@sean:~/Documents/astraea/docker$ ./start_broker.sh zookeeper.connect=192.168.103.141:19316 broker.id=10
b03cc9d48844ee2d5b509f850d6a1ea76264aebf825d720153a5ecd57e037f38
=================================================
broker id: 10
broker address: 192.168.103.39:10667
jmx address: 192.168.103.39:14630
exporter address: 192.168.103.39:15784
=================================================
```
修正後:
```
./start_broker.sh zookeeper.connect=192.168.103.141:19316 sean@sean:~/Documents/astraea/docker$ ./start_broker.sh zookeeper.connect=192.168.103.141:19316 broker.id=10
broker.id is NOT configurable
```

fix rejectProperty funtion in `start_broker.sh`

---

docker/start_broker.sh
docker/start_kafka_tool.sh
docker/start_spark.sh
docker/start_zookeeper.sh

This PR address following tasks to reduce the image size.
1. use multi-stages to avoid unused files to be cached
2. replace `JDK` by `JRE` in runtime

Reduce zookeeper, broker, spark and astraea image size

---

docker/start_kafka_tool.sh

We use the performance tool to benchmark our Kafka, so the JVM heap should be configurable.

Add heap configs to kafka tool

---

docker/start_zookeeper.sh

此PR針對`start_zookeeper.sh`，新增設定JVM heap size的選項
```
env HEAP_OPTS="-Xmx4G -Xms1G" ./docker/start_zookeeper.sh
```

Add HEAP_OPTS to set max and min JVM heap size for Zookeeper script

---

app/src/main/java/org/astraea/Utils.java
app/src/main/java/org/astraea/partitioner/nodeLoadMetric/NodeLoadClient.java
app/src/main/java/org/astraea/partitioner/nodeLoadMetric/PartitionerUtils.java
app/src/main/java/org/astraea/partitioner/smoothPartitioner/SmoothWeightPartitioner.java
app/src/test/java/org/astraea/partitioner/nodeLoadMetric/PartitionerUtilsTest.java
app/src/test/java/org/astraea/partitioner/smoothPartitioner/PartitionerTest.java

優化Partitioner效能，現在在10KiB的record.size下也能保持一定的效能。
右邊爲改善過後的astraea partitioner的數據，原先的數據結果大概爲30min avg=500MB/s
主要的改善點爲減少不必要的該方法`brokersWeight`調用。JMC告訴我該方法佔了整個程式12%的cpu使用量。
而如果metrics不變這個方法的結果就不會改變。metrics最快也是1s更新一次，所以改爲超過1s再進行一次計算。

Optimization Partitioner

---

.github/workflows/ci.yml
app/build.gradle

透過該參數可以降低github CI跑測試的平行度，進而降低因為資源問題導致的測試失敗

Introduce maxParallelForks

---

app/src/main/java/org/astraea/performance/Performance.java
app/src/test/java/org/astraea/performance/PerformanceTest.java

`--configs`類似`prop.file`，但比較簡單可以直接在命令列指定複數的參數，目前會用於測試不同的`partitioner`。因為各個partitioner所使用的參數可能不相同，使用`--configs`可以避免我們需要將各個partitioner特定的參數通通暴露到performance tool

add configs field to Performance tool

---

app/src/main/java/org/astraea/topic/TopicExplorer.java
app/src/test/java/org/astraea/topic/TopicExplorerTest.java

resolve #245 
Raise an exception if any of the target topic/partition has no leader.
```
Exception in thread "main" java.lang.IllegalStateException: Some partitions have no leader: [__consumer_offsets-0, __consumer_offsets-1, __consumer_offsets-2, __consumer_offsets-3, __consumer_offsets-4, __consumer_offsets-5, __consumer_offsets-6, __consumer_offsets-7, __consumer_offsets-8, __consumer_offsets-9, __consumer_offsets-10, __consumer_offsets-11, __consumer_offsets-12, __consumer_offsets-13, __consumer_offsets-14, __consumer_offsets-15, __consumer_offsets-16, __consumer_offsets-17, __consumer_offsets-18, __consumer_offsets-19, __consumer_offsets-20, __consumer_offsets-21, __consumer_offsets-22, __consumer_offsets-23, __consumer_offsets-24, __consumer_offsets-25, __consumer_offsets-26, …
```

fix AdminClient#listOffsets API timeout error

---

app/src/main/java/org/astraea/cost/LoadCost.java
app/src/main/java/org/astraea/cost/MemoryWarningCost.java
app/src/main/java/org/astraea/partitioner/nodeLoadMetric/NodeLoadClient.java
app/src/main/java/org/astraea/partitioner/nodeLoadMetric/PartitionerUtils.java
app/src/main/java/org/astraea/partitioner/smoothPartitioner/SmoothWeight.java
app/src/main/java/org/astraea/partitioner/smoothPartitioner/SmoothWeightDispatcher.java
app/src/test/java/org/astraea/cost/FakeClusterInfo.java
app/src/test/java/org/astraea/cost/LoadCostTest.java
app/src/test/java/org/astraea/cost/MemoryWarningCostTest.java
app/src/test/java/org/astraea/partitioner/nodeLoadMetric/PartitionerUtilsTest.java
app/src/test/java/org/astraea/partitioner/smoothPartitioner/SmoothWeightTest.java

此PR重構了原來的`SmoothWeightPartitioner`，使用`CostFunction`實做。並做了些許的變動：
1. 省去部份初始判斷(`lastTime==-1...`)
2. 把時間判斷集中(原本是`NodeLoadClient`, `SmoothWeightPartitioner`分別做"1秒1更新")
3. 省去還未實做的功能(如：`throughputAbility`, `standardDeviation`...等功能)
4. 算法切分不同，所以unit test另外寫了一份。
另外改寫的過程中發現了很多問題：
1. 現在算法結果難以使用0~1表示
2. 許多型別轉換(是否必要)
3. 參數重複參考(是否必要)
4. `CostFunction`回傳值的 "意義"
@wycccccc 看看算法是否須要再做調整？

Rewrite `SmoothWeightPartitioner`

---

app/src/main/java/org/astraea/metrics/HasBeanObject.java
app/src/main/java/org/astraea/metrics/collector/BeanCollector.java
app/src/main/java/org/astraea/metrics/jmx/BeanObject.java
app/src/test/java/org/astraea/metrics/collector/BeanCollectorTest.java

新增`createdTimestamp`給所有bean objects，同時該timestamp將用作`BeanCollector`內部的時間淘汰選擇

Add created timestamp to all bean objects

---

app/src/main/java/org/astraea/cost/ClusterInfo.java
app/src/main/java/org/astraea/cost/PartitionInfo.java
app/src/test/java/org/astraea/cost/FakeClusterInfo.java
app/src/test/java/org/astraea/partitioner/StrictCostDispatcherTest.java

這個 PR 對 `ClusterInfo` 和 `PartitionInfo` 新增一些 Balancer 需要的欄位
* add `ClusterInfo#topics`
有 `ClusterInfo#partitoins(String topic)` 和 `ClusterInfo#availablePartitions(String topic)`, 但是沒有辦法單從 `ClusterInfo` 得知有哪些 topic 存在，所以這些 method 沒辦法直接利用，如果 `ClusterInfo` 是 cluster 在某個時間點的 snapshot 的話 `topic` 資訊應該也要暴露。
* add `replicas`, `inSyncReplicas`, `offlineReplicas` fields to `PartitionInfo`
`ClusterInfo` 如果是 cluster snapshot 的話，這些 replica 分佈的資訊應該也要包含在內，不過原先的 `PartitionInfo` 並沒有這些欄位，導致後面 CostFunction 沒辦法從 `ClusterInfo` 中得知 replica 分佈資訊。

Revise `ClusterInfo` and `PartitionInfo` implementation

---

app/src/main/java/org/astraea/topic/TopicExplorer.java

客戶回報的問題，當使用consumer group但不使用committed offset的時後，我們的工具無法列出該consumer group的相關資訊。
這個原因是我們只會顯示“有”committed offsets的consumer group，然而kafka的機制是允許在使用consumer group的前提下卻不使用committed offsets。因此我們也應該遵守一樣的規則將其顯示出來
*After*
```
| | Consumer Group "spark-kafka-source-509ea296-bd57-4c09-9b7c-458857e486ca--2103420107-driver-0"
| |   no committed offset for partition 0
| |   no committed offset for partition 1
| |   no committed offset for partition 2
| |   no committed offset for partition 3
| |   no committed offset for partition 4
| |   no committed offset for partition 5
| |   no committed offset for partition 6
| |   no committed offset for partition 7
| |   no committed offset for partition 8
| |   no committed offset for partition 9
| |   Members:
| |     member …
```

Show the consumer group having no committed offset

---

app/src/main/java/org/astraea/argument/CompressionField.java
app/src/main/java/org/astraea/consumer/Builder.java
app/src/main/java/org/astraea/consumer/Consumer.java
app/src/main/java/org/astraea/consumer/Isolation.java
app/src/main/java/org/astraea/performance/Performance.java
app/src/main/java/org/astraea/producer/Builder.java
app/src/main/java/org/astraea/producer/Producer.java
app/src/main/java/org/astraea/topic/Builder.java
app/src/main/java/org/astraea/topic/Compression.java
app/src/main/java/org/astraea/topic/Creator.java
app/src/test/java/org/astraea/argument/CompressionFieldTest.java
app/src/test/java/org/astraea/partitioner/smoothPartitioner/PartitionerTest.java
app/src/test/java/org/astraea/performance/PerformanceTest.java
app/src/test/java/org/astraea/producer/ProducerTest.java
app/src/test/java/org/astraea/topic/CompressionTest.java

一些重構，包含：
1) 新增`Compression` and `Isolation` 來避免直接使用kafka參數
2) 重構一些較長的函示

Add Isolation and Compression to simplify builder

---

app/src/main/java/org/astraea/consumer/Builder.java
app/src/main/java/org/astraea/consumer/Consumer.java
app/src/test/java/org/astraea/consumer/ConsumerTest.java

Enable users to limit the returned number of records from Consumer#poll

---

app/src/test/java/org/astraea/topic/cost/CalculateUtilsTest.java

`CalculateUtilsTest`完全沒有用到`RequireBrokerCluster`所提供的服務

remove RequireBrokerCluster from CalculateUtilsTest

---

app/src/main/java/org/astraea/Utils.java
app/src/main/java/org/astraea/concurrent/ThreadPool.java
app/src/main/java/org/astraea/performance/DataSupplier.java
app/src/main/java/org/astraea/performance/Manager.java
app/src/main/java/org/astraea/performance/Performance.java
app/src/main/java/org/astraea/performance/ProducerExecutor.java
app/src/main/java/org/astraea/performance/ReportFormat.java
app/src/main/java/org/astraea/performance/Tracker.java
app/src/main/java/org/astraea/producer/Sender.java
app/src/test/java/org/astraea/concurrent/ThreadPoolTest.java
app/src/test/java/org/astraea/performance/DataSupplierTest.java
app/src/test/java/org/astraea/performance/ManagerTest.java
app/src/test/java/org/astraea/performance/PerformanceTest.java
app/src/test/java/org/astraea/performance/ProducerExecutorTest.java
app/src/test/java/org/astraea/performance/TrackerTest.java

改善了以下幾個點：
1. 避免`Manager`涵蓋太多功能導致難以測試，原本的`Manager`掌管了producer/consuemr的資料量、也掌管了如何產生資料、更掌管了什麼時候要停止各個consumer/producer
2. throttle的使用方式改善，原本的方式是直接卡著等到可以回傳資料，但這樣會導致呼叫者只能乾等，這隻PR增加了幾個狀態列讓呼叫者可以自行決定大概何時要再來拿、或是過程要不要做一些事情
3. 避免建立多餘的producer，原本會同時建立兩個producer，一個負責transaction、一個負責一般的資料。然而實際上我們同時只會用一個...
4. 增加更多的測試

Refactor ProducerExecutor

---

README.md
app/build.gradle
app/src/main/java/org/astraea/App.java
app/src/main/java/org/astraea/topic/TopicAdmin.java
app/src/main/java/org/astraea/web/ErrorObject.java
app/src/main/java/org/astraea/web/GroupHandler.java
app/src/main/java/org/astraea/web/Handler.java
app/src/main/java/org/astraea/web/JsonObject.java
app/src/main/java/org/astraea/web/TopicHandler.java
app/src/main/java/org/astraea/web/WebService.java
app/src/test/java/org/astraea/web/GroupHandlerTest.java
app/src/test/java/org/astraea/web/HandlerTest.java
app/src/test/java/org/astraea/web/TopicHandlerTest.java
app/src/test/java/org/astraea/web/WebServiceTest.java
docker/start_kafka_tool.sh

這是一個獨立的新應用程式，目的是將一些非常需要觀察的叢集資訊透過restful APIs曝露出來，目前專案原有的工具都是將資料印到console上面，這在與下游整合上不太容易，因此我們要改成restful APIs的形式。這隻PR作為起始動作包含幾個目標：
1. 盡量不引入太多第三方函式庫，整個web service目前只額外用到google json
2. 目前支援查詢`topics` and `groups`
3. `start_kafka_tool.sh`腳本有配合修改讓web service所監聽的port可以開放
之後會逐步擴充web service能查詢的項目，最終目標要取代掉現有的`offsets`和`monitor`
---
範例一：查詢topic: testPerformance-1652350196001
```
GET http://localhost:8001/topics/testPerformance-1652350196001
```
```json
{
"name": "testPerformance-1652350196001",
"partitions": [
{
"partitionId": 6,
"earliest": 0,
"latest": 149844,
"replicas": [
{
"broker": 1001,
"lag": 0,
"size": 78885381,
"leader": true,
"inSync": true,
"isFuture": false,
"path": "/tmp/log-folder-2"
}
]
},
{
"partitionId": 2,
"earliest": 0,
"latest": 149888,
"replicas": [
{
"broker": 1001,
"lag": 0, …
```

Add web service to inspect kafka cluster

---

app/src/main/java/org/astraea/web/BrokerHandler.java
app/src/main/java/org/astraea/web/WebService.java
app/src/test/java/org/astraea/service/RequireBrokerCluster.java
app/src/test/java/org/astraea/web/BrokerHandlerTest.java

```
GET http://hostname:port/brokers
```
```json
{
"brokers": [
{
"id": 1001,
"configs": {
"log.cleaner.min.compaction.lag.ms": "0",
"metric.reporters": "",
"offsets.topic.num.partitions": "50",
"sasl.oauthbearer.jwks.endpoint.refresh.ms": "3600000",
"log.flush.interval.messages": "9223372036854775807",
"controller.socket.timeout.ms": "30000",
"auto.create.topics.enable": "true",
"principal.builder.class": "org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder",
"controller.quorum.request.timeout.ms": "2000",
"replica.socket.receive.buffer.bytes": "65536",
"min.insync.replicas": "1",
"replica.fetch.wait.max.ms": "500",
"num.recovery.threads.per.data.dir": "1",
"ssl.keystore.type": "JKS",
"password.encoder.iterations": "4096",
"zookeeper.ssl.protocol": "TLSv1.2", …
```

Enable to expose broker information by Restful API

---

app/src/test/java/org/astraea/admin/AdminTest.java

```
AdminTest > testOffsets() FAILED
[30](https://github.com/skiptests/astraea/runs/6440503201?check_suite_focus=true#step:5:30)
org.opentest4j.AssertionFailedError: expected: <6> but was: <3>
[31](https://github.com/skiptests/astraea/runs/6440503201?check_suite_focus=true#step:5:31)
at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
[32](https://github.com/skiptests/astraea/runs/6440503201?check_suite_focus=true#step:5:32)
at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
[33](https://github.com/skiptests/astraea/runs/6440503201?check_suite_focus=true#step:5:33)
at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
[34](https://github.com/skiptests/astraea/runs/6440503201?check_suite_focus=true#step:5:34)
at …
```

Fix flaky AdminTest#testOffsets

---

app/src/main/java/org/astraea/admin/Admin.java
app/src/main/java/org/astraea/admin/Builder.java
app/src/main/java/org/astraea/performance/Performance.java
app/src/main/java/org/astraea/web/BrokerHandler.java
app/src/test/java/org/astraea/web/BrokerHandlerTest.java

產生下方的統計畫面
```json
"brokers": [
{
"id": 1001,
"topics": [
{
"topic": "log",
"partitionCount": 8
},
{
"topic": "table",
"partitionCount": 10
}
],
```

Add topic/partitions to broker for restful APIs

---

docker/start_kafka_tool.sh

We use the restful APIs to touch web service rather than console, so it does not need to run in foreground.

The web container should run in background

---

docker/start_spark.sh

The python version in ubuntu 22.04 is 3.10, and it has compatibility issue (see https://github.com/vmprof/vmprof-python/issues/240)

Downgrade ubuntu from 22.04 to 20.04 for spark image

---

app/src/main/java/org/astraea/partitioner/smooth/SmoothWeightRoundRobin.java
app/src/main/java/org/astraea/partitioner/smooth/SmoothWeightRoundRobinDispatcher.java
app/src/test/java/org/astraea/partitioner/smooth/SmoothWeightRoundRobinDispatchTest.java
app/src/test/java/org/astraea/partitioner/smooth/SmoothWeightRoundRobinTest.java

如題，完成 #315 後續討論部分，這裏只是完成該功能，並不是模擬程式。

SWRR supports the calculation of multiple topics

---

app/src/main/java/org/astraea/partitioner/smooth/SmoothWeightRoundRobin.java
app/src/test/java/org/astraea/partitioner/smooth/SmoothWeightRoundRobinDispatchTest.java
app/src/test/java/org/astraea/partitioner/smooth/SmoothWeightRoundRobinTest.java

https://github.com/skiptests/astraea/commit/6a6135cd0ed5df788e87311c2b9ef2eb9257aa51 breaks the build, and it is caused by https://github.com/skiptests/astraea/commit/0840f87daed9c48825782c0f30a09d06c56d780e which renamed some APIs

The build is broken after we rename availablePartitionLeaders to availableReplicaLeaders

---

app/src/main/java/org/astraea/web/PipelineHandler.java
app/src/main/java/org/astraea/web/WebService.java
app/src/test/java/org/astraea/web/PipelineHandlerTest.java

The API `/pipelines` can show the producer/consumer connected to topics.
```json
{
"topicPartitions": [
{
"topic": "testPerformance-1653542175343",
"partition": 0,
"from": [
{
"producerId": 6,
"producerEpoch": 0,
"lastSequence": 129638,
"lastTimestamp": 1653542192678
},
{
"producerId": 7,
"producerEpoch": 0,
"lastSequence": 129637,
"lastTimestamp": 1653542192730
},
{
"producerId": 8,
"producerEpoch": 0,
"lastSequence": 129244,
"lastTimestamp": 1653542192736
}
],
"to": [
{
"groupId": "groupId-1653542175709",
"memberId": "consumer-groupId-1653542175709-1-c1f578db-5c84-4c06-863e-342c0c3fe654",
"clientId": "consumer-groupId-1653542175709-1",
"host": "/172.17.0.1"
}
]
},
{
"topic": "testPerformance-1653542175343",
"partition": 1,
"from": [
{
"producerId": 6,
"producerEpoch": 0,
"lastSequence": …
```

Enable to show consuemr/producer connected to topics

---

app/src/main/java/org/astraea/consumer/Consumer.java
app/src/main/java/org/astraea/performance/Performance.java
app/src/test/java/org/astraea/consumer/ConsumerTest.java

#323 
解決consumer throughput 時常為0 的怪象。
發生原因於 #323 留言中解釋。

Decrease number of records buffered

---

app/src/main/java/org/astraea/admin/Admin.java
app/src/main/java/org/astraea/admin/Builder.java
app/src/main/java/org/astraea/admin/ReplicaMigrator.java
app/src/main/java/org/astraea/common/Utils.java
app/src/test/java/org/astraea/admin/AdminTest.java
app/src/test/java/org/astraea/common/UtilsTest.java
app/src/test/java/org/astraea/service/Services.java

實作 `Admin#preferredLeaderElection`

---

.gitignore
README.md
docker/start_app.sh

隨著逐漸整合越來越多功能，只用"kafka-tool"來稱呼顯得侷限，因此改用我們的入口名稱`app`來取代

Rename kafka-tool to app

---

app/src/main/java/org/astraea/app/admin/ReplicaSyncingMonitor.java
app/src/test/java/org/astraea/app/admin/ReplicaSyncingMonitorTest.java

resolve #311.
https://github.com/skiptests/astraea/blob/ee5f014ef684c15b6b5417e57c7c072ebd238be3/app/src/main/java/org/astraea/app/admin/ReplicaSyncingMonitor.java#L218-L231
`ReplicaSyncingMonitor` 原先假設 log size 不會縮減，對此在程式碼內穿插一段邏輯，如果觸發這樣的情境會直接丟出錯誤，但 log retention/log compaction 可能會造成 log 大小縮減，對此這個假設並不正確，這個 PR 移除這段 safe check，允許出現 log size 在追蹤過程中變小的情況。
```shell
[2022-06-10T16:54:59.630245]
Topic "topic-1":
| Partition 0:
| | replica on broker   0 => [####################] 100.00% [leader, synced, log-shrunk]
| | replica on broker   1 => [########            ]  43.75% ? Byte/seconds (unknown) [log-shrunk]
Topic "topic-2":
| Partition 0:
| | replica on broker   0 => [####################] 100.00% [leader, synced, log-shrunk]
| | replica on broker   1 => [########            ]  43.75% ? …
```

Fix log shrinkage cause `ReplicaSyncingMonitor` to raise an exception.

---

app/src/main/java/org/astraea/app/web/WebService.java
app/src/test/java/org/astraea/app/admin/AdminTest.java

剛剛在審查#405的時候發現我不小心打錯路徑名稱....
另外也修正了一隻不穩定的測試

Rename transaction API path from "transaction" to "transactions"

---

app/src/main/java/org/astraea/app/performance/Metrics.java
app/src/main/java/org/astraea/app/performance/Performance.java
app/src/main/java/org/astraea/app/performance/ProducerExecutor.java
app/src/main/java/org/astraea/app/producer/Metadata.java
app/src/test/java/org/astraea/app/performance/ManagerTest.java
app/src/test/java/org/astraea/app/performance/MetricsTest.java
app/src/test/java/org/astraea/app/performance/PerformanceTest.java
app/src/test/java/org/astraea/app/performance/ProducerExecutorTest.java
app/src/test/java/org/astraea/app/performance/TrackerTest.java

如果是有額外考量才特地把 serializedKeySize 以及 serializedValueSize return type 設為 long 的話，歡迎關掉這份pr，感謝

Fix incorrect return type

---

app/src/main/java/org/astraea/app/admin/Admin.java
app/src/main/java/org/astraea/app/admin/Builder.java
app/src/main/java/org/astraea/app/consumer/Builder.java
app/src/main/java/org/astraea/app/consumer/PartitionsBuilder.java
app/src/main/java/org/astraea/app/consumer/SubscribedConsumer.java
app/src/main/java/org/astraea/app/consumer/TopicsBuilder.java
app/src/test/java/org/astraea/app/admin/AdminTest.java
app/src/test/java/org/astraea/app/consumer/ConsumerTest.java

這邊新增兩個方法給admin
1. 刪除所有members (static and dynamic)
2. 刪除static members
kafka目前不支援刪除dynamic members :(

Enable to remove all members/static members

---

app/src/main/java/org/astraea/app/web/PostRequest.java
app/src/main/java/org/astraea/app/web/RecordHandler.java
app/src/main/java/org/astraea/app/web/WebService.java
app/src/test/java/org/astraea/app/web/RecordHandlerTest.java

resolve https://github.com/skiptests/astraea/issues/397

Implement post record web api

---

app/src/main/java/org/astraea/app/balancer/generator/ShufflePlanGenerator.java
app/src/main/java/org/astraea/app/balancer/log/ClusterLogAllocation.java
app/src/main/java/org/astraea/app/balancer/log/LayeredClusterLogAllocation.java
app/src/test/java/org/astraea/app/balancer/log/LayeredClusterLogAllocationTest.java

延續 https://github.com/skiptests/astraea/pull/412#issuecomment-1159626602
令 `ClusterLogAllocation#migrationReplica` 能夠指定要搬移到哪個 data directory，同時修改 `ShufflePlanGenerator` 的實作，使他能夠使用這個新的 API 來做產生計劃，這樣產生的計劃比較明確，能使後續 `CostFunction` 比較好做預測。

Allow `ClusterLogAllocation#migrationReplica` specify data directory

---

app/src/main/java/org/astraea/app/admin/Admin.java
app/src/main/java/org/astraea/app/admin/Builder.java
app/src/main/java/org/astraea/app/admin/Reassignment.java
app/src/main/java/org/astraea/app/common/Utils.java
app/src/test/java/org/astraea/app/admin/AdminTest.java

新增`Admin#reassignments`用來列舉目前的搬移狀況，包含兩種例子：
1. 節點之間的搬移
2. 目錄之間的搬移

Enable to list reassignment by Admin

---

app/src/main/java/org/astraea/app/admin/Builder.java
app/src/main/java/org/astraea/app/admin/ReplicaCollie.java
app/src/main/java/org/astraea/app/web/PostRequest.java
app/src/main/java/org/astraea/app/web/ReassignmentHandler.java
app/src/main/java/org/astraea/app/web/Response.java
app/src/main/java/org/astraea/app/web/WebService.java
app/src/test/java/org/astraea/app/web/PostRequestTest.java
app/src/test/java/org/astraea/app/web/ReassignmentHandlerTest.java
docs/web_server/README.md
docs/web_server/web_api_reassignments_chinese.md

新增Web APIs用來操作 reassignment，包含：
1) 查看目前的 `reassignment`
2) 移動partitions的部署節點
3) 移動replica的資料路徑

Web APIs for reassignments

---

app/src/main/java/org/astraea/app/admin/Builder.java
app/src/test/java/org/astraea/app/admin/AdminTest.java

#440 中對 `Migrator#moveTo` 實作一些檢查，確保要進行 data directory 搬移的對象是當前 replica list 的一份子。
不過這個檢查寫錯了
* 我們要確保的是**進行 data directory 搬移的對象是當前 replica list 的一份子**
* 但是被我寫成**所有 replica list 的成員都要被搬移**。
假設現在有個 partition 有 `[0,1,2]` 這個 replica list，假設我只想對 0 進行 data directory 搬移，則當前的檢查會拋出 `[1,2]` 並非 replica list 的一部分這個錯誤，只有傳入的 map 指定對 0,1,2 這三個 broker 同時做 data directory 的搬移才不會發生錯誤。
這個 PR 修正這些檢查

Fix incorrect check in `Migrator#moveTo`

---

app/src/main/java/org/astraea/app/metrics/jmx/MBeanClient.java
app/src/main/java/org/astraea/app/metrics/jmx/MBeanClientImpl.java
app/src/test/java/org/astraea/app/metrics/jmx/MBeanClientTest.java

我們即將新增一種新的metrics評量方式 - 監控producer local metrics來評估合適的節點，為了達到這個目的，我們需要將local JVM metrics串接到`MBeanClient`，這隻PR達成這第一步，接下來會開始引入可以用local metrics來評估的各種cost functions。這個方法的最大好處是使用者“不需要"輸入JMX port等資訊一樣可以享受cost functions帶來的好處

Introduce local MBeanClient

---

app/src/main/java/org/astraea/app/cost/NodeLatencyCost.java
app/src/main/java/org/astraea/app/partitioner/StrictCostDispatcher.java
app/src/test/java/org/astraea/app/cost/NodeLatencyCostTest.java
app/src/test/java/org/astraea/app/partitioner/StrictCostDispatcherTest.java

修復兩個bugs:
1. JMX port沒定義時會噴出錯誤
2. NodeLatencyCost 無法處理多個beans

Allow to ignore jmx port and NodeLatencyCost can't parse beans

---

app/src/main/java/org/astraea/app/admin/Builder.java
app/src/main/java/org/astraea/app/admin/QuotaCreator.java
app/src/main/java/org/astraea/app/web/QuotaHandler.java
app/src/test/java/org/astraea/app/admin/AdminTest.java

感謝 @garyparrot  在 #481 中重構了 `DataRate`，因此可以讓其作為public APIs的一部分了

QuotaCreator should use DataRate rather than long

---

README.md
app/src/main/java/org/astraea/app/performance/Performance.java

key distribution預設值為`fixed`，這個會導致key值一直是固定的，這樣不符合常見的用法，因此改成`uniform`

Change key distribution from fixed to uniform

---

app/src/main/java/org/astraea/app/cost/NeutralIntegratedCost.java
app/src/main/java/org/astraea/app/metrics/collector/Fetcher.java
app/src/main/java/org/astraea/app/metrics/jmx/MBeanClientImpl.java
app/src/main/java/org/astraea/app/partitioner/StrictCostDispatcher.java
app/src/test/java/org/astraea/app/metrics/collector/FetcherTest.java

`StrictCostDispatcher`可結合許多不同的cost functions，然後再索取metrics的過程中可能有些fetchers會出現錯誤，在正常使用中這些錯誤應該都屬於臨時性的錯誤，例如連線被中斷或是目標的JVM尚未更新相關的metrics，因此`StrictCostDispatcher`可以先將該些錯誤吃掉，以免在長期測試中被中斷
不過另外一個角度則是如果遇到”一定會失敗的狀況“，或許我們就應該中斷程序，這需要更多討論，因此我在PR有留下TODO (referenced to #486)

Swallow the exception thrown by fetchers

---

app/src/main/java/org/astraea/app/cost/BrokerInputCost.java
app/src/main/java/org/astraea/app/cost/BrokerOutputCost.java
app/src/main/java/org/astraea/app/metrics/KafkaMetrics.java
app/src/main/java/org/astraea/app/metrics/jmx/BeanObject.java
app/src/main/java/org/astraea/app/metrics/jmx/MBeanClientImpl.java
app/src/test/java/org/astraea/app/cost/BrokerInputCostTest.java
app/src/test/java/org/astraea/app/cost/BrokerOutputCostTest.java
app/src/test/java/org/astraea/app/metrics/broker/KafkaMetricsTest.java

這隻PR除了一些重構以外，也簡化了`BrokerInputCost`和`BrokerOutputCost`的邏輯，包含：
1. 移除了`TScore`，使用這兩個cost的傢伙應該要自行去做正規劃
2. 改用`oneMinuteRate`取代`count`，前者提供更合理的觀察指標

Simplify input/ouput cost

---

app/src/main/java/org/astraea/app/common/Cache.java
app/src/main/java/org/astraea/app/web/RecordHandler.java
app/src/test/java/org/astraea/app/common/CacheTest.java

Add cache for transactional producer

---

app/src/main/java/org/astraea/app/metrics/KafkaMetrics.java
app/src/main/java/org/astraea/app/metrics/broker/ServerMetrics.java
app/src/test/java/org/astraea/app/metrics/KafkaMetricsTest.java
app/src/test/java/org/astraea/app/metrics/broker/ServerMetricsTest.java

Move purgatory metrics to separate file

---

app/src/main/java/org/astraea/app/cost/NodeLatencyCost.java
app/src/main/java/org/astraea/app/cost/NodeThroughputCost.java
app/src/main/java/org/astraea/app/metrics/KafkaMetrics.java
app/src/main/java/org/astraea/app/metrics/producer/HasProducerNodeMetrics.java
app/src/main/java/org/astraea/app/partitioner/StrictCostDispatcher.java
app/src/test/java/org/astraea/app/cost/NodeLatencyCostTest.java
app/src/test/java/org/astraea/app/cost/NodeThroughputCostTest.java
app/src/test/java/org/astraea/app/metrics/producer/HasProducerNodeMetricsTest.java
docker/start_app.sh

Fix node metrics

---

app/src/main/java/org/astraea/app/cost/ReplicaDiskInCost.java
app/src/test/java/org/astraea/app/cost/ReplicaDiskInCostTest.java

簡化ReplicaDiskInCost中 sizeTimeSeries的計算方法，改用LogMetrics.Log.Meter

simplify sizeTimeSeries

---

app/src/test/java/org/astraea/app/cost/NodeLatencyCostTest.java

Fix NodeLatencyCostTest#testCost

---

app/src/main/java/org/astraea/app/cost/NodeLatencyCost.java
app/src/main/java/org/astraea/app/cost/NodeMetricsCost.java
app/src/main/java/org/astraea/app/cost/NodeThroughputCost.java
app/src/main/java/org/astraea/app/metrics/client/HasNodeMetrics.java
app/src/main/java/org/astraea/app/metrics/client/consumer/ConsumerMetrics.java
app/src/main/java/org/astraea/app/metrics/client/producer/HasProducerTopicMetrics.java
app/src/main/java/org/astraea/app/metrics/client/producer/ProducerMetrics.java
app/src/test/java/org/astraea/app/cost/NodeLatencyCostTest.java
app/src/test/java/org/astraea/app/cost/NodeThroughputCostTest.java
app/src/test/java/org/astraea/app/metrics/client/consumer/ConsumerMetricsTest.java
app/src/test/java/org/astraea/app/metrics/client/producer/HasProducerTopicMetricsTest.java
app/src/test/java/org/astraea/app/metrics/client/producer/ProducerMetricsTest.java

在修改 #236 時，發現 node-metrics 是 "KafkaClient" 紀錄的效能數據，consumer, producer 都有。為了重複利用程式碼，將程式碼改名成 `client/NodeMetrics` ，用來表示 client 端跟 brokers 溝通時的效能數據。
所以這隻 PR 
1. 重構了原本的 `ProducerNodeMetrics` 改名為 `NodeMetrics`
2. 更改路徑名，(`metrics/producer/ProducerMetrics` -> `metrics/client/producer/ProducerMetrics`)
3. 新增了 `ConsumerMetrics` ，模仿 `ProducerMetrics` 的寫法，讀取本地端 consumer的效能數據

Add Consumer Node Metrics

---

app/src/main/java/org/astraea/app/consumer/Builder.java
app/src/main/java/org/astraea/app/consumer/Consumer.java
app/src/main/java/org/astraea/app/consumer/PartitionsBuilder.java
app/src/main/java/org/astraea/app/consumer/TopicsBuilder.java
app/src/main/java/org/astraea/app/performance/ConsumerThread.java
app/src/test/java/org/astraea/app/consumer/ConsumerTest.java

Astraea consumer 建立後便固定了訂閱的資訊，這樣在測試consumer re-balance時會有些不方便，因此這隻PR讓consumer可以暫時解除訂閱，如此就能自由的觸發re-balance

Enable to unsubscribe/resubscribe topics/partitions

---

app/src/main/java/org/astraea/app/performance/Performance.java

執行 Performance tool 時，也等待 FileWriter 完成。
在#512 中，重構了許多thread 管理，其中 `fileWriter` thread 沒有等待完成。
`BufferedWriter` 還未 flush 資料，該 thread 已經被關閉。原來的 `BufferedWriter::close` 來不及執行就結束了。
這裡增加了等待 `fileWriter` thread 完成，讓 `BufferedWriter` 執行完 `close` 才把程式結束。

Wait for file writer complete

---

app/src/main/java/org/astraea/app/consumer/SubscribedConsumer.java
app/src/main/java/org/astraea/app/consumer/TopicsBuilder.java
app/src/test/java/org/astraea/app/consumer/ConsumerTest.java

當啟用追蹤時，`consumer`會紀錄每次 balance後的結果和時間，這會方便我們在performance印出相關資訊

Enable consumer to trace all subscriptions

---

app/src/main/java/org/astraea/app/common/Utils.java
app/src/main/java/org/astraea/app/performance/ConsumerThread.java
app/src/main/java/org/astraea/app/performance/Performance.java
app/src/main/java/org/astraea/app/performance/ProducerThread.java
app/src/main/java/org/astraea/app/performance/Report.java
app/src/main/java/org/astraea/app/performance/ReportFormat.java
app/src/main/java/org/astraea/app/performance/TrackerThread.java
app/src/test/java/org/astraea/app/performance/MetricsTest.java

1. 移除了`current throughput` (原因請見https://github.com/skiptests/astraea/issues/577)
2. 刪除不必要的內部物件

Simplify performance report

---

app/src/main/java/org/astraea/app/cost/NodeTopicSizeCost.java
app/src/test/java/org/astraea/app/cost/NodeTopicSizeCostTest.java

#553 從其中切割出，爲NodeTopicSize加入partition cost。

Log size partition cost

---

app/src/main/java/org/astraea/app/admin/ClusterInfo.java
app/src/main/java/org/astraea/app/partitioner/RoundRobin.java
app/src/main/java/org/astraea/app/partitioner/StrictCostDispatcher.java
app/src/test/java/org/astraea/app/partitioner/StrictCostDispatcherTest.java

幾個概念的調整：
1. 每次租約到期後一次算出一個長度的round-robin，如此可避免之後反覆計算的物件成本和同步的成本
2. 將常用來走訪的陣列都改成`ArrayList`，降低走訪的成本

Optimize dispatcher for large partitions

---

app/src/main/java/org/astraea/app/admin/NodeInfo.java

Pre-create hash code of NodeIno

---

app/src/main/java/org/astraea/app/admin/ClusterInfo.java
app/src/main/java/org/astraea/app/partitioner/StrictCostDispatcher.java
app/src/main/java/org/astraea/app/partitioner/smooth/SmoothWeightRoundRobinDispatcher.java
app/src/test/java/org/astraea/app/admin/AdminTest.java
app/src/test/java/org/astraea/app/cost/ClusterInfoTest.java
app/src/test/java/org/astraea/app/partitioner/StrictCostDispatcherTest.java

主要原因是最後產生 <broker, topic> partitions 的時候會產生新的陣列，當 partitions 數量很多時會有明顯的成本，因此在建立ClusterInfo的時候我們就先分類好以避免後續的成本

Avoid creating too many partition lists

---

app/src/main/java/org/astraea/app/web/ReassignmentHandler.java
app/src/test/java/org/astraea/app/web/ReassignmentHandlerTest.java
docs/web_server/web_api_reassignments_chinese.md

支援一次執行多個migration plans，這會方便我們之後執行balancer

Support to execute migration plans by Reassignment Web API

---

app/src/main/java/org/astraea/app/admin/Builder.java
app/src/main/java/org/astraea/app/admin/ClusterInfo.java
app/src/main/java/org/astraea/app/balancer/BalanceProcessDemo.java
app/src/main/java/org/astraea/app/balancer/BalancerUtils.java
app/src/main/java/org/astraea/app/balancer/generator/RebalancePlanGenerator.java
app/src/main/java/org/astraea/app/balancer/generator/ShufflePlanGenerator.java
app/src/test/java/org/astraea/app/admin/AdminTest.java
app/src/test/java/org/astraea/app/balancer/FakeClusterInfo.java
app/src/test/java/org/astraea/app/balancer/RebalancePlanProposalTest.java
app/src/test/java/org/astraea/app/balancer/generator/ShufflePlanGeneratorTest.java
app/src/test/java/org/astraea/app/balancer/log/ClusterLogAllocationTest.java
app/src/test/java/org/astraea/app/cost/ClusterInfoTest.java

1. 移除`ClusterInfo#dataDirectories`，該方法完全只為了`RebalancePlanGenerator`存在，而且在其他情境會產生矛盾（不存在）
2. 重構`RebalancePlanGenerator`讓其可以解構`ClusterInfo#dataDirectories`
3. 新增大量預設方法到`ClusterInfo`，降低其實作的複雜度

Remove ClusterInfo#dataDirectories

---

app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/main/java/org/astraea/app/web/BeanHandler.java
app/src/main/java/org/astraea/app/web/BrokerHandler.java
app/src/main/java/org/astraea/app/web/Channel.java
app/src/main/java/org/astraea/app/web/GroupHandler.java
app/src/main/java/org/astraea/app/web/Handler.java
app/src/main/java/org/astraea/app/web/PipelineHandler.java
app/src/main/java/org/astraea/app/web/PostRequest.java
app/src/main/java/org/astraea/app/web/ProducerHandler.java
app/src/main/java/org/astraea/app/web/QuotaHandler.java
app/src/main/java/org/astraea/app/web/ReassignmentHandler.java
app/src/main/java/org/astraea/app/web/RecordHandler.java
app/src/main/java/org/astraea/app/web/TopicHandler.java
app/src/main/java/org/astraea/app/web/TransactionHandler.java
app/src/main/java/org/astraea/app/web/WebService.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
app/src/test/java/org/astraea/app/web/BeanHandlerTest.java
app/src/test/java/org/astraea/app/web/BrokerHandlerTest.java
app/src/test/java/org/astraea/app/web/ChannelTest.java
app/src/test/java/org/astraea/app/web/GroupHandlerTest.java
app/src/test/java/org/astraea/app/web/HandlerTest.java
app/src/test/java/org/astraea/app/web/PipelineHandlerTest.java
app/src/test/java/org/astraea/app/web/PostRequestTest.java
app/src/test/java/org/astraea/app/web/ProducerHandlerTest.java
app/src/test/java/org/astraea/app/web/QuotaHandlerTest.java
app/src/test/java/org/astraea/app/web/ReassignmentHandlerTest.java
app/src/test/java/org/astraea/app/web/RecordHandlerTest.java
app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
app/src/test/java/org/astraea/app/web/TransactionHandlerTest.java
docs/web_server/web_api_records_chinese.md

重構了幾個項目，包含：
1. 新增`Channel`介面，該介面負責request/response的進出，如此`Handler`只需要負責與sub classes互動即可
2. `get`, `post`, and `delete`都改用`Channel`作為輸入參數，如此之後要新增任何東西都不需要再更改大量`Handler`
3. 移除所有`HttpExchange`從所有介面

Refactor Response callback

---

app/src/main/java/org/astraea/app/balancer/executor/RebalanceAdminImpl.java
app/src/test/java/org/astraea/app/balancer/executor/RebalanceAdminTest.java

resolve #622 
* debounce 檢查做得更頻繁（連續成功 10 次，每次間隔 100ms），這樣取樣的次數比較多，比較能撞到這個狀態彈跳的問題
* 整理重複的程式碼

增加 `RebalanceAdmin#wait*Synced` 的 debounce 次數

---

app/src/main/java/org/astraea/app/admin/Builder.java
app/src/main/java/org/astraea/app/admin/ClusterInfo.java
app/src/main/java/org/astraea/app/balancer/BalancerUtils.java
app/src/test/java/org/astraea/app/balancer/FakeClusterInfo.java

新增一個方法讓使用者可以取得所有`replicas`，並且用該方法來提供預設實作以簡化`ClusterInfo`的建構

Add ClusterInfo#replicas to show all cached replicas

---

docker/start_app.sh

源自 [這裡](https://github.com/skiptests/astraea/pull/619#discussion_r953819994) 的需求
目前的 start_app.sh 腳本缺乏了
1. 當參數有檔案路徑時，無法讀取 (因為沒有 mount 進 container)
2. 執行時輸出的檔案會留在 container 內
3. 腳本只能選擇 skiptests/astraea 的版本來跑，測試起來不方便
---
為此，
1. 在 start_app.sh 內新增新的參數，`ACCOUNT` 用來指定 github clone 的位置。
2. 判定輸入的參數內是否有包含 `--report.path` 並將下一個值 mount 進去。

Mount while `--report.path` occur

---

app/src/main/java/org/astraea/app/admin/ClusterInfo.java
app/src/main/java/org/astraea/app/balancer/BalancerUtils.java
app/src/main/java/org/astraea/app/cost/NodeTopicSizeCost.java
app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/test/java/org/astraea/app/balancer/BalancerUtilsIntegratedTest.java

1. `NodeTopicSizeCost` 提供 `ClusterCost`
2. 撰寫新的`ClusterInfo`產生方式，盡量保持`Replica`資訊的完整性
3. `Balancer APIs`現在改用`topic size`作為評估手段

Change balancer to Use NodeTopicSizeCost to evaluate cost

---

docker/build_deps_image.sh
docker/start_broker.sh

早期的`kafka`並沒有放置`gradlew`，因此我們新增`gradle 5`到映像檔幫助建立早期的`kafka`版本

Add gradle to deps base

---

app/src/main/java/org/astraea/app/admin/Builder.java
app/src/main/java/org/astraea/app/admin/ClusterInfo.java
app/src/main/java/org/astraea/app/admin/ReplicaInfo.java
app/src/main/java/org/astraea/app/balancer/BalancerUtils.java
app/src/main/java/org/astraea/app/cost/ReplicaLeaderCost.java
app/src/main/java/org/astraea/app/partitioner/StrictCostDispatcher.java
app/src/main/java/org/astraea/app/partitioner/smooth/SmoothWeightRoundRobin.java
app/src/test/java/org/astraea/app/admin/AdminTest.java
app/src/test/java/org/astraea/app/admin/ClusterInfoWithOfflineNodeTest.java
app/src/test/java/org/astraea/app/balancer/FakeClusterInfo.java
app/src/test/java/org/astraea/app/cost/ClusterInfoIntegratedTest.java
app/src/test/java/org/astraea/app/cost/ClusterInfoTest.java
app/src/test/java/org/astraea/app/cost/ReplicaLeaderCostTest.java
app/src/test/java/org/astraea/app/partitioner/StrictCostDispatcherTest.java
app/src/test/java/org/astraea/app/partitioner/smooth/SmoothWeightRoundRobinDispatchTest.java
app/src/test/java/org/astraea/app/partitioner/smooth/SmoothWeightRoundRobinTest.java

1. `availableReplicaLeaders` 重新命名為 `replicaLeaders` 因為 current leader 應該總是 available
2. 將各個方法重新排序
3. 補上一些測試

Refactor ClusterInfo

---

app/src/main/java/org/astraea/app/admin/ClusterInfo.java
app/src/test/java/org/astraea/app/cost/CpuCostTest.java
app/src/test/java/org/astraea/app/cost/MemoryCostTest.java
app/src/test/java/org/astraea/app/cost/NeutralIntegratedCostTest.java
app/src/test/java/org/astraea/app/cost/NodeLatencyCostTest.java
app/src/test/java/org/astraea/app/cost/NodeThroughputCostTest.java
app/src/test/java/org/astraea/app/cost/NodeTopicSizeCostTest.java
app/src/test/java/org/astraea/app/cost/ReplicaDiskInCostTest.java
app/src/test/java/org/astraea/app/cost/ReplicaLeaderCostTest.java
app/src/test/java/org/astraea/app/partitioner/StrictCostDispatcherTest.java
app/src/test/java/org/astraea/app/partitioner/smooth/SmoothWeightRoundRobinDispatchTest.java
app/src/test/java/org/astraea/app/partitioner/smooth/SmoothWeightRoundRobinTest.java

現在`ClusterInfo`是個具有豐富介面但方便實作的類別，因此不再需要使用`mock`的方式

Don't mock ClusterInfo anymore

---

app/src/main/java/org/astraea/app/metrics/client/HasNodeMetrics.java
app/src/main/java/org/astraea/app/metrics/client/consumer/ConsumerMetrics.java
app/src/main/java/org/astraea/app/metrics/client/consumer/HasConsumerCoordinatorMetrics.java
app/src/main/java/org/astraea/app/metrics/client/producer/HasProducerTopicMetrics.java
app/src/main/java/org/astraea/app/metrics/client/producer/ProducerMetrics.java
app/src/test/java/org/astraea/app/metrics/client/consumer/ConsumerMetricsTest.java
app/src/test/java/org/astraea/app/metrics/client/consumer/HasConsumerCoordinatorMetricsTest.java
app/src/test/java/org/astraea/app/metrics/client/producer/ProducerMetricsTest.java

新增`ConsumerCoordinatorMetrics` 讓我們方便存取本地 consumer 的狀態

Add ConsumerCoordinatorMetrics

---

app/src/main/java/org/astraea/app/performance/TrackerThread.java

https://github.com/skiptests/astraea/issues/680#issue-1364253603
新增 consumerDone 未達100%時，繼續更新消費進度

fix consumerDone doesn't update

---

app/src/test/java/org/astraea/app/performance/PerformanceTest.java

#687 
雖然 #690 已經有幫忙把測試做修改 (指定不存在的 broker ID，以測試 exception)，不過原來的想法是 "同時指定 broker ID 和 topic 導致 沒有合適的目標"，故仍予以修正。
測試的方式是，建立一個 1 partition 的 topic ，然後 **指定該 topic** 且 **指定 沒有 partition 的 broker ID**。這樣的話，雖然 topic 和 broker ID 都是合法的，但同時指定的話是沒有交集的。
原先測試會出錯是因為 在抓 `validBroker` 時沒有指定 topic ，導致先前建立的 topic 也混入其中。

[Fix Flaky] Test no target when specify broker and topic

---

common/src/test/java/org/astraea/common/admin/AdminTest.java

由於取得`transaction`的動作並非 atomic，因此我們改成用時間來等待狀態穩定

Fix flaky AdminTest.testTransactionIdsWithMultiPuts

---

app/build.gradle
app/src/main/java/org/astraea/app/App.java
app/src/main/java/org/astraea/app/scenario/Scenario.java
app/src/main/java/org/astraea/app/scenario/ScenarioMain.java
app/src/main/java/org/astraea/app/scenario/impl/SkewedPartitionScenario.java
app/src/test/java/org/astraea/app/scenario/impl/SkewedPartitionScenarioTest.java
common/src/main/java/org/astraea/common/Utils.java
common/src/main/java/org/astraea/common/partitioner/StrictCostDispatcher.java
common/src/test/java/org/astraea/common/UtilsTest.java
common/src/test/java/org/astraea/common/partitioner/StrictCostDispatcherTest.java

resolve #684
這個 PR 實作一個 `Scenario` 界面，其描述一個 Kafka 使用情境的 log allocation 建立邏輯。
目前提供一個 `SkewedPartitionScenario`，其透過 Binomial Distribution 來決定每個 Partition 的 Replica List 長相。由於 Binomial Distribution 可以說是離散情境下的常態分佈，因此我們可以預期他所產生出來的 partition 分佈是集中在特定幾個節點的。我們可以透過這個特性來製造一些負載不平衡的情境。
```
./gradlew run --args="scenario --bootstrap.servers 192.168.0.4:19128 --scenario.file /home/garyparrot/Ignore.txt"
```
```json
{
"topicName": "b5f6871ed8864de69998052b77ef8021",
"partitions": 100,
"replicas": 1,
"binomialProbability": 0.5,
"scenarioName": "org.astraea.app.scenario.impl.SkewedPartitionScenario"
}
```
```
Accept scenario: org.astraea.app.scenario.impl.SkewedPartitionScenario
{
"topicName": "b5f6871ed8864de69998052b77ef8021",
"partitions": 100,
"replicas": 1,
"binomialProbability": 0.5,
"leaderSum": { …
```

implementation of `Scenario`

---

app/src/main/java/org/astraea/app/performance/Performance.java
app/src/main/java/org/astraea/app/performance/ProducerThread.java
app/src/main/java/org/astraea/app/performance/Report.java
app/src/main/java/org/astraea/app/performance/ReportFormat.java
app/src/main/java/org/astraea/app/performance/TrackerThread.java
app/src/test/java/org/astraea/app/performance/TrackerTest.java

perf 自己統計的寫入資訊都可以用 kafka 內建的統計來取代，這邊用該些資訊來簡化程式碼

Replace manual repore by kafka metrics

---

app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java

Source: https://github.com/skiptests/astraea/actions/runs/3060745599/jobs/4939630645#step:5:509
`BalancerHandlerTest` 裡面有一段邏輯在確保被改變的 topics 數量是 2 個，但是經常發生數量是 0 的情況。
被改變的數量是0的源頭是找不到可用的計劃，目前測試裡面是使用 `ReplicaSizeCost` 來找計劃，而且目前邏輯直接拿第一個計劃來當做結果，加上計劃完全隨機產生，直覺上這樣測試不太能總是通過。
這個 PR 採用的修正是，使用一個總是回傳更好分數的 ClusterCost，確保更好的計劃被提出這件事總是成立。這樣做對確認 BalancerHandler 回傳的結果是否正確不影響。

Fix flaky test in `BalancerHandlerTest`

---

app/src/main/java/org/astraea/app/web/ReassignmentHandler.java
app/src/test/java/org/astraea/app/web/ReassignmentHandlerTest.java
docs/web_server/web_api_reassignments_chinese.md

resolve https://github.com/skiptests/astraea/issues/595

Support progress in reassignments web api

---

app/src/main/java/org/astraea/app/balancer/log/ClusterLogAllocation.java
app/src/test/java/org/astraea/app/balancer/log/ClusterLogAllocationTest.java

原先的 `ClusterLogAllocation#findNonFulfilledAllocation` 假設輸入的兩個 allocation 有着相同的 topic/partition set。
由於現在 Generator 產生的計劃可能是基於叢集的子集合，現在需要修正這個規則。
* 原本：source 和 target 必須要有相同的 topic/partition set。
* 現在：target topic/partitions 必須是 source 的 topic/partitions 的 subset。
目前沒有修正的版本會在有套 topic filter 時發生錯誤。

Revise `ClusterLogAllocation#findNonFulfilledAllocation`

---

app/src/test/java/org/astraea/app/web/TopicHandlerTest.java

resolve https://github.com/skiptests/astraea/issues/722
類似的解法已經有在 testCreateTopicWithReplicas 提供
https://github.com/skiptests/astraea/blob/7596f590ae0f0ec370a6e257c10cc2aeb5fb5bf4/app/src/test/java/org/astraea/app/web/TopicHandlerTest.java#L244-L254

Fix flaky testCreateTopics

---

app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java

#653 
BalancerHandler.get() 因為 queries 缺少 topics，導致 targetAllocations 的 size ＝ 0。

Fix flaky BalancerHandlerTest#testReport

---

it/build.gradle
it/src/main/java/org/astraea/it/RequireSingleWorkerCluster.java
it/src/main/java/org/astraea/it/RequireWorkerCluster.java
it/src/main/java/org/astraea/it/Services.java
it/src/main/java/org/astraea/it/WorkerCluster.java
it/src/test/java/org/astraea/it/RequireSingleWorkerClusterTest.java
it/src/test/java/org/astraea/it/RequireWorkerClusterTest.java

astraea-720 Add embedded connector worker for test

---

app/src/main/java/org/astraea/app/web/GroupHandler.java
app/src/test/java/org/astraea/app/web/GroupHandlerTest.java
common/src/main/java/org/astraea/common/admin/Builder.java
common/src/main/java/org/astraea/common/admin/ConsumerGroup.java
common/src/test/java/org/astraea/common/admin/AdminTest.java

`activeMembers` 是 `assignments` 的子資訊，因此可以拿掉，另外也簡化了一些程式碼

Remove ConsumerGroup#activeMembers

---

app/src/main/java/org/astraea/app/web/BrokerHandler.java
app/src/main/java/org/astraea/app/web/TopicHandler.java
common/src/main/java/org/astraea/common/admin/Builder.java
common/src/main/java/org/astraea/common/admin/Config.java
common/src/test/java/org/astraea/common/admin/AdminTest.java

我們太常使用`Map<String, String>`，因此讓它直接回傳

Enable Config to return raw map

---

app/src/main/java/org/astraea/app/scenario/SkewedPartitionScenario.java
app/src/test/java/org/astraea/app/balancer/BalancerTest.java

resolve #750 
出錯的原因是 `SkewedPartitionScenario` 在把 log 分佈套用到叢集時，只等待一秒鐘當作工作完成，但是實際上這個過程可能會花上不少時間。太快呼叫的結果導致後面重新選舉 leader 時觸發 `PreferredLeaderNotAvailableException` 錯誤。
修正的方式是用 `RebalanceAdmin` 裏面的等待功能等特定 log 達到 sync 狀態，而非單純等 1 秒鐘。

Fix flaky BalancerTest#testLeaderCountRebalance

---

app/src/main/java/org/astraea/app/balancer/generator/ShufflePlanGenerator.java
app/src/main/java/org/astraea/app/balancer/log/ClusterLogAllocation.java
app/src/test/java/org/astraea/app/balancer/executor/StraightPlanExecutorTest.java
app/src/test/java/org/astraea/app/balancer/log/ClusterLogAllocationTest.java

* 編修 `ClusterLogAllocation` 的 javadoc
* 重寫 `ClusterLogAllocation` 的測試，提升 readability & coverage
* 修正 `ClusterLogAllocation#letReplicaBecomeLeader` 的小問題
* 執行後 replica 和對應 leader 的 replica 資訊會錯亂
* 重新命名 `ClusterLogAllocation#letReplicaBecomeLeader` 為 `ClusterLogAllocation#becomeLeader`

Revise `ClusterLogAllocation`

---

common/src/main/java/org/astraea/common/admin/Builder.java
common/src/main/java/org/astraea/common/admin/Partition.java
common/src/main/java/org/astraea/common/admin/Topic.java
common/src/test/java/org/astraea/common/admin/AdminTest.java

重新審視了一下 kafka 原始碼，發現 `List offset`並不會順便搜尋 timestamp，因此這邊改成有紀錄的 max timestamp

Remove earliest/latest timestamp

---

app/src/main/java/org/astraea/app/balancer/executor/RebalanceAdminImpl.java
app/src/main/java/org/astraea/app/balancer/log/ClusterLogAllocation.java
app/src/test/java/org/astraea/app/balancer/executor/RebalanceAdminTest.java
app/src/test/java/org/astraea/app/balancer/log/ClusterLogAllocationTest.java

Context: https://github.com/skiptests/astraea/pull/764#discussion_r981445170
* `ClusterLogAllocation#migrateReplica` 一定要指定 destination data directory 位置
* 修正 `RebalanceAdmin#declarePreferredDataDirectories` 在遇到 null directory(caused by offline replica) 時會噴錯的問題

Remove null directory usage in `ClusterLogAllocation`

---

app/src/main/java/org/astraea/app/performance/ConsumerThread.java
app/src/main/java/org/astraea/app/performance/Performance.java

由於 kafka metrics 無法得知明確的 subscribed partitions，因此新增一個變數保存目前運作中的 client 各自處理哪些 partitions

Enable to trace subscribed partitions when running perf tool

---

app/src/test/java/org/astraea/app/web/TopicHandlerForProbabilityTest.java

原本的binomialProbability設定為0.5，三個broker分到partition的機率為0.25,0.5,0.25，broker0與broker2分到的replica數量很大的機率會一樣，導致flaky test，此PR將binomialProbability修改為0.15，三個broker分到partition的機率變成0.723,0.255,0.023，會大幅降低flaky test的機會

fix flaky test TopicHandlerForProbabilityTest

---

common/src/main/java/org/astraea/common/admin/Broker.java
common/src/main/java/org/astraea/common/admin/Builder.java
common/src/test/java/org/astraea/common/admin/AdminTest.java

Admin#brokers 可以取得 partitions，但無法辨別是否為 leaders，因此這隻 PR 新增一個方法回傳 leader partitions

Enable to trace leaders from Admin#brokers

---

gui/src/main/java/org/astraea/gui/BrokerTab.java

Add leaders to BrokerTab

---

common/src/main/java/org/astraea/common/cost/ReplicaNumberCost.java
common/src/test/java/org/astraea/common/cost/ReplicaNumberCostTest.java

as title. 基本有三種狀況：
1. 只有一個節點時，成本總是為0
2. 有多個節點，但 partitions 集中在一個節點上面，那成本是 long.max
3. 其他狀況則是回傳(max - min)的值作為成本

New cluster cost based on replica number

---

app/src/main/java/org/astraea/app/balancer/BalanceProcessDemo.java
app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
common/src/main/java/org/astraea/common/balancer/BalancerBuilder.java

如題，`Balancer`預設應該是要找出更便宜的方案，不應該允許同樣成本方案的存在

Always try to find a cheaper cluster cost

---

common/src/main/java/org/astraea/common/balancer/BalancerBuilder.java
common/src/main/java/org/astraea/common/cost/ReplicaLeaderCost.java
common/src/test/java/org/astraea/common/balancer/BalancerAlgorithmTest.java
common/src/test/java/org/astraea/common/balancer/BalancerTest.java

這是一隻討論用的PR
原本 balancer 是在同一個基礎上產生多種隨機組合，必且從中選擇一個最佳解，這隻PR則改為採用 greedy 的方式先找到一個相對好的組合後，再以該組合為基礎繼續往下找
greedy 的好處在於能較穩地的找尋更低成本的組合，但副作用是如果第一步踩錯，會導致後續基於不好的基礎往下嘗試，使得很快掉進區域最佳解裡面

Apply greedy algorithm to balancer

---

common/src/main/java/org/astraea/common/admin/Admin.java
common/src/main/java/org/astraea/common/admin/Builder.java
common/src/main/java/org/astraea/common/metrics/client/admin/AdminMetrics.java
common/src/main/java/org/astraea/common/metrics/client/admin/HasAdminMetrics.java
common/src/main/java/org/astraea/common/metrics/client/consumer/HasConsumerMetrics.java
common/src/test/java/org/astraea/common/admin/AdminTest.java
common/src/test/java/org/astraea/common/metrics/client/admin/AdminMetricsTest.java
common/src/test/java/org/astraea/common/metrics/client/consumer/HasConsumerMetricsTest.java
common/src/test/java/org/astraea/common/metrics/client/producer/ProducerMetricsTest.java

我們的 web and gui 都仰賴大量的 admin operations，因此需要一個方式來暴露 admin metrics

Add AdminMetrics to expose the status of admin

---

gui/src/main/java/org/astraea/gui/BrokerTab.java
gui/src/main/java/org/astraea/gui/TopicTab.java
gui/src/main/java/org/astraea/gui/Utils.java

`DataSize` offers great `toString` and `Comparable` (thanks to @garyparrot), so we can replace `String` type by `DataSize` directly. The benefit is that we can not only sort the `DataSize` but also have human-readable content.

Replace String by DataSize

---

common/src/main/java/org/astraea/common/Utils.java
common/src/main/java/org/astraea/common/admin/Admin.java
common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
common/src/main/java/org/astraea/common/admin/Broker.java
common/src/main/java/org/astraea/common/admin/Builder.java
common/src/main/java/org/astraea/common/admin/TopicCreator.java
common/src/test/java/org/astraea/common/admin/AdminTest.java

原先封裝的`Admin`為了方便將所有 async 都封裝成 sync，這在大量操作下會有大量執行緒彼此等待的問題，因此我們新增一個`AsyncAdmin`，它保持非同步的操作，並且將物件重新封裝回 astraea object

Add AsyncAdmin to fetch topic, partition and broker

---

etl/build.gradle
etl/src/main/scala/org/astraea/etl/DeployMode.scala
etl/src/main/scala/org/astraea/etl/DeployModePattern.scala
etl/src/main/scala/org/astraea/etl/Metadata.scala
etl/src/main/scala/org/astraea/etl/Utils.scala
etl/src/test/scala/org/astraea/etl/CSVReaderTest.scala
etl/src/test/scala/org/astraea/etl/DeployModeTest.scala
etl/src/test/scala/org/astraea/etl/MetadataTest.scala

因目前專案kafka使用的版本為scala2.12，為了能正常使用專案各功能，因此選擇降級scala版本到2.12。
scala2.12缺少try with resource，故新增該方法。另外還有一些小的scala2.12沒有實現的地方也做了對應修改。
這隻應該也會產生不少conflict，需要儘快meger。再麻煩學長有空的看看。

ETL:downgrade scala version to 2.12

---

common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java

原本的用法是 kafka internal thread 會重複被使用來處理後續所有 callbacks，這樣的副作用是如果 `CompletableFuture` chaining 很長的話，可能會影響到其他 requests，因此這隻 PR 將 `complete` 改成  `completeAsync` 讓其他執行緒接手 kafka internal thread 的任務

Convert kafka future to CompletableFuture by another thread

---

common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
common/src/main/java/org/astraea/common/admin/ConsumerGroup.java
gui/src/main/java/org/astraea/gui/AddPartitionTab.java
gui/src/main/java/org/astraea/gui/ConsumerTab.java
gui/src/main/java/org/astraea/gui/Main.java

兩個任務：
1. 新增頁面來動態增加 partitions
2. 修復舊版kafka無法取得 max timestamp
3. consumer 頁面會顯示 coordinator

[GUI] enable to add partition; add coordinator to consumer tab

---

common/src/main/java/org/astraea/common/consumer/Builder.java
common/src/main/java/org/astraea/common/consumer/Consumer.java
common/src/main/java/org/astraea/common/consumer/TopicsBuilder.java

把一些可用的 consumer 參數字串添加到 consuemr，這樣會方便日後取用，也能避免直接引入 kafka config

Add consumer constants

---

common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
common/src/main/java/org/astraea/common/admin/Broker.java
common/src/main/java/org/astraea/common/admin/NodeInfo.java
common/src/main/java/org/astraea/common/admin/Partition.java
common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
common/src/test/java/org/astraea/common/admin/AsyncAdminWithOfflineBrokerTest.java
common/src/test/java/org/astraea/common/admin/ClusterInfoWithOfflineNodeTest.java
gui/src/main/java/org/astraea/gui/PartitionTab.java

Kafka admin 更新 metadata 的時候是以 topic 為單位，因此如果有些操作需要更新 metadata (例如 listOffsets)時就可能因為 offline node 並且只有一個 replica 時而卡住

Fix AsyncAdmin can't get partitions when there is offline node

---

app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
common/src/main/java/org/astraea/common/Utils.java

resolve #857 
觸發錯誤的源頭應該是 reassignment 在 assertion 之前結束
修正：建立足夠大的 Partition, 確保搬移持續一段時間，減少 reassignment 發生到 assertion 觸發之間的 sleep interval。

Fix flaky `BalancerHandlerTest#testRebalanceDetectOngoing`

---

gui/src/main/java/org/astraea/gui/BrokerTab.java

Broker 頁面現在會顯示保存在本地但不屬於任何 topic 的partitions，這有幾種可能：
1. 該些partitions是正在搬移中，而該些metadata尚未更新到每個節點
2. 該節點曾經下線，然後partitions配置已經被更新，該節點上線後會導致該些partition不是follower/leader

[GUI] BrokerTab show the orphan partitions

---

etl/src/test/scala/org/astraea/etl/MetadataTest.scala

修正錯誤測試，目前 ci 會因為 `defaultTest`, `configuredTest` 這兩個測試報錯

Fix failed tests in MetadataTest

---

gui/src/main/java/org/astraea/gui/Context.java
gui/src/main/java/org/astraea/gui/tab/MetricsTab.java
gui/src/main/java/org/astraea/gui/tab/TopicTab.java
gui/src/main/java/org/astraea/gui/table/TableView.java

當 JMX port 有設定時，會添加五個 metrics:
1. BytesInPerSec
2. BytesOutPerSec
3. MessagesInPerSec
4. TotalFetchRequestsPerSec
5. TotalProduceRequestsPerSec

[GUI] TopicTab should show the topic metrics if metrics is enabled

---

common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
common/src/main/java/org/astraea/common/admin/NodeInfo.java
common/src/main/java/org/astraea/common/balancer/executor/RebalanceAdminImpl.java
common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
gui/src/main/java/org/astraea/gui/tab/TopicTab.java
gui/src/main/java/org/astraea/gui/tab/UpdateTopicTab.java

這隻PR調整`AsyncAdmin`回傳的資料排序，由於我們大部分的資料都有 topic, partition，因此可以用該些資訊來排序

Make consistent order for AsyncAdmin

---

.github/workflows/ci.yml

原本的 build 只會建構 production code，這樣會導致 test code 無法編譯時的錯誤被延後，另外跑測試的時候應該總是跑完所有模組，不然會在前面模組發生錯誤時就停下來，進而使得我們無法得之後面模組的測試是否正常

Always build/test all code when running CI

---

etl/src/test/scala/org/astraea/etl/KafkaWriterTest.scala

flaky的原因是沒有等待 kafka metadata 同步，因此加上一個等待時間

Fix flaky KafkaWriterTest#topicCreatorTest

---

common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java

更改計算方式，內部變數並不是 thread-safe，這會導致無法取得最新的狀態，這隻PR改成我們自行統計轉換了多少 kafka APIs，這個方式雖然會比較不準，因為我們不知道APIs對應的真實請求數量，但也足以讓我們知道有多少呼叫還沒處理完
resolve #933

Fix flaky AsyncAdminTest#testPendingRequest

---

common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
common/src/main/java/org/astraea/common/balancer/executor/RebalanceAdminImpl.java
common/src/main/java/org/astraea/common/scenario/SkewedPartitionScenario.java
common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
common/src/test/java/org/astraea/common/admin/ClusterInfoWithOfflineNodeTest.java

失敗的原因是`SkewedPartitionScenario`送出建立 topic 的請求後會馬上接著索取相關的資訊，這中間可能會遇到 metadata 尚未同步的意外，因此這隻PR在建立 topic 後增加一個檢查確保 metadata 盡可能同步完成

Fix flaky SkewedPartitionScenarioTest

---

common/src/main/java/org/astraea/common/balancer/BalancerBuilder.java
common/src/test/java/org/astraea/common/balancer/BalancerTest.java

Context: #754
這個 PR 給 `BalancerBuilder` 新增一個函數，呼叫者可以傳入 `Supplier<ClusterBean>`，這個 `Supplier` 每次呼叫應該要提供最新的 Cluster bean 資訊，這個資訊應該由建立 `Balancer` 的模組提供，以隔離撈取效能資訊和搜尋計劃的邏輯。
這個 PR 結束後的下一步是：補上 Web API 撈取 metrics 的部分，如此一來 Web APIs 就能夠支援有 Fetcher 需求的 Cost Function

Implementation of `BalancerBuilder#metricSource`

---

.github/workflows/ci.yml

https://github.com/skiptests/astraea/pull/848#discussion_r999519092
除了上述的問題外，我們在GUI文件上也是用 zulu，因此這隻PR讓CI也改用zulu

Replace AdoptOpenJDK by zulu for CI

---

common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
common/src/test/java/org/astraea/common/admin/AsyncAdminWithOfflineBrokerTest.java

Add earliest/latest/maxTimestamp to AsyncAdmin

---

gui/src/main/java/org/astraea/gui/tab/TopicTab.java

如題，原本是顯示曾經有紀錄的 group 資訊，現在改成顯示“active"

[GUI] TopicTab should show the active consumers

---

common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java

如題，有些資訊我們無法在舊版kafka中取得，因此改為空陣列回傳

Handle the exception thrown by older kafka

---

common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
common/src/main/java/org/astraea/common/admin/Partition.java
common/src/test/java/org/astraea/common/admin/AdminTest.java
common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
common/src/test/java/org/astraea/common/admin/AsyncAdminWithOfflineBrokerTest.java
gui/src/main/java/org/astraea/gui/tab/PartitionTab.java
gui/src/main/java/org/astraea/gui/tab/TopicTab.java

如題，在舊版 kafka 上會無法索取該值，除此之外，沒有資料時也會找不到max timestamp，因此我們用optional來表達該些現象

Change Partition#maxTimestamp to be optional

---

common/src/main/java/org/astraea/common/Utils.java
gui/src/main/java/org/astraea/gui/tab/BrokerTab.java
gui/src/main/java/org/astraea/gui/tab/ClientTab.java
gui/src/main/java/org/astraea/gui/tab/topic/PartitionTab.java
gui/src/main/java/org/astraea/gui/tab/topic/TopicTab.java
gui/src/main/java/org/astraea/gui/text/TextArea.java

原本的時間字串轉換沒有考慮時區，同時用字串呈現會阻礙後續的資料處理，因此現在將時間欄位都轉換成`LocalDateTime`

[GUI] Replace time string by LocalDateTime

---

gui/src/main/java/org/astraea/gui/tab/BalancerTab.java

這支PR在balancer GUI新增`migrated leader`，可以讓使用者知道產生的搬移計畫是否有移動到partition leader
看起來如下:

migrateLeaderForGUI

---

app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
common/src/main/java/org/astraea/common/balancer/Balancer.java
common/src/main/java/org/astraea/common/balancer/BalancerBuilder.java

為了讓使用者可以在Balancer的GUI可以設定多個`MoveCost`的上限，此PR將`Blaancer`改成可以吃多個`HasMoveCost`

multiMoveCostToBalancer

---

common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
common/src/main/java/org/astraea/common/admin/BrokerConfigs.java
common/src/main/java/org/astraea/common/admin/Config.java
common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
common/src/test/java/org/astraea/common/admin/BrokerConfigsTest.java

為了後續方便使用，在過程中做了幾個蜜糖：
*APPEND*
1. 值重複時則不append
2. 空值時改成 set，避免遇到bug (https://github.com/apache/kafka/pull/12503)
3. 值為*時也不append
*SUBTRACT*
1. 值為空時不subtract
2. 沒有對應的值時也不subtract
3. 值為*時則拋出錯誤

Enable to append/subtract configs from AsyncAdmin

---

common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
common/src/main/java/org/astraea/common/admin/Partition.java
common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
gui/src/main/java/org/astraea/gui/pane/PaneBuilder.java
gui/src/main/java/org/astraea/gui/tab/ClientTab.java
gui/src/main/java/org/astraea/gui/tab/QuotaTab.java
gui/src/main/java/org/astraea/gui/tab/topic/PartitionTab.java
gui/src/main/java/org/astraea/gui/tab/topic/ReplicaTab.java
gui/src/main/java/org/astraea/gui/tab/topic/TopicTab.java

現在我們支援豐富的 table query，因此可以將一些重複功能的 select items移除，此外也將`internal`的資訊放回 table 內供使用者查詢

[GUI] remove useless select items

---

common/src/main/java/org/astraea/common/metrics/collector/BeanCollector.java
common/src/main/java/org/astraea/common/metrics/collector/Register.java
common/src/test/java/org/astraea/common/metrics/collector/BeanCollectorTest.java

Context: https://github.com/skiptests/astraea/pull/955#discussion_r1003189128
給 `BeanCollector` 旗下的 `Register` 新增一個 `Register#autoUpdate`，這個 Flag 能夠讓 `Receiver` 自己建立一個執行序以定時觸發效能指標取樣。

Allow `Receiver` to launch a thread to trigger metrics update

---

app/src/main/java/org/astraea/app/web/TopicHandler.java
app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
docs/web_server/web_api_topics_chinese.md

新增兩個欄位：
1. max timestamp -> 表示各個 partition 擁有的最大時間戳記
2. active group id -> 表示目前有哪些 group 正在讀取

[WEB] add max timestamp and active group ids to topic APIs

---

common/src/main/java/org/astraea/common/admin/ClusterInfo.java
common/src/main/java/org/astraea/common/cost/ReplicaLeaderCost.java
common/src/test/java/org/astraea/common/cost/ReplicaLeaderCostTest.java

使用`ClusterInfo`來計算`BrokerCost`與`ClusterCost`也必須考慮到沒有持有任何replica的broker，否則造成計算`ClusterCost`時，結果不正確

fix ReplicaLeaderCost

---

common/src/main/java/org/astraea/common/admin/ClusterInfo.java
common/src/test/java/org/astraea/common/admin/ClusterInfoTest.java

在diff計算兩個`ClusterInfo`的分佈差異時，也必須要考慮到partitionLeader以及preferredLeader，若是沒有考慮這兩個，在計算 `ReplicaLeaderCost#MoveCost`的時候，只有更換Leader(preferredLeader)而沒有搬移到其他Broker或data folder的replica會被忽略掉

fix `ClusterInfo#diff`

---

app/src/test/java/org/astraea/app/web/BrokerHandlerTest.java
common/src/main/java/org/astraea/common/admin/TopicCreator.java
common/src/test/java/org/astraea/common/admin/ClusterInfoWithOfflineNodeTest.java
common/src/test/java/org/astraea/common/balancer/log/ClusterLogAllocationTest.java

如題，這是剩下的deprecated blocking method

Remove TopicCreator#create

---

common/src/main/java/org/astraea/common/Lazy.java
common/src/main/java/org/astraea/common/admin/ClusterInfo.java
common/src/test/java/org/astraea/common/LazyTest.java

`ClusterInfo`作為我們貫穿各地的物件，我們需要針對大量的replicas做各種索引，但該些索引的建立累積起來也相當費時，因此我們採用lazy手法只有當需要時才建立物件，這隻PR將lazy的手法抽出來成為一個獨立的行為，這樣其他需要的使用者也可以採用

Add Lazy object to initialize objs lazily

---

app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java

resolve #1047.
原先測試是建 3 個 topics，參數允許特定 2 個 topics 能夠被 Balance，然後測試預期他們兩個都有被搬移。
以現行 Generator 的機制，會隨機從 9 個 topic/partition 中抽 1 ~ 30 個做更動，且這個操作執行 30 次，取 Cost Function 最佳的分佈，由於現在都使用 `decreasing cost` 所以其實 30 次只有最後一次 matter。
由於隨機的關係我們可能會 1 ~ 30 個更動全部都抽到同一個 topic/partition。使最後 `POST /balancer` 得到的 Changes 只有 1 個。
實際上測試假設這兩個 topic/partition 都一定會抽到是不太合理的，隨機下有一定機率會全部更改都坐落在同一個 topic。雖然不確定具體機率是多少，但單看只做 1 個變更的情況，我們可以很肯定觸發這個情況的機率比 `1/30` 還要高(約 3.33%)。
這個 PR 修正測試的檢查條件，所有的 changes 都應該是針對允許的 topics。

Fix flaky `BalancerHandlerTest#testTopics`

---

common/src/main/java/org/astraea/common/balancer/executor/StraightPlanExecutor.java
gui/src/main/java/org/astraea/gui/tab/BalancerNode.java
gui/src/test/java/org/astraea/gui/tab/BalancerNodeTest.java

如題，我們重複使用`StraightPlanExecutor`來達成搬移的效果
另外在 #1055 還沒結果之前，`StraightPlanExecutor`會保持等待資料都同步的邏輯，同時為了讓`GUI`不會卡在等待資料同步，`StraightPlanExecutor`提供兩個方法，一個只負責完成plan，一個則是完成plan和資料搬移
另外也替`BalancerNode`補上測試

[GUI] apply StraightPlanExecutor to BalancerNode

---

app/src/main/java/org/astraea/app/balancer/BalanceProcessDemo.java
app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
common/src/main/java/org/astraea/common/admin/ClusterInfo.java
common/src/main/java/org/astraea/common/balancer/executor/RebalancePlanExecutor.java
common/src/main/java/org/astraea/common/balancer/executor/StraightPlanExecutor.java
common/src/test/java/org/astraea/common/balancer/BalancerTest.java
common/src/test/java/org/astraea/common/balancer/executor/StraightPlanExecutorTest.java
gui/src/main/java/org/astraea/gui/pane/PaneBuilder.java
gui/src/main/java/org/astraea/gui/tab/BalancerNode.java
gui/src/main/java/org/astraea/gui/tab/topic/ReplicaNode.java
gui/src/test/java/org/astraea/gui/tab/topic/ReplicaNodeTest.java

fix #1055 
現在`RebalancePlanExecutor`預設需要實作的部分只要完成搬移就好，最後集體的資料同步和re-election將會由預設實作完成。同時使用者可以選擇是否要等待最後的同步

Enable RebalancePlanExecutor to execute plan with/without sycn waiting

---

common/src/main/java/org/astraea/common/admin/Admin.java
common/src/main/java/org/astraea/common/consumer/Deserializer.java
common/src/main/java/org/astraea/common/producer/Builder.java
gui/src/main/java/org/astraea/gui/pane/PaneBuilder.java
gui/src/main/java/org/astraea/gui/tab/AboutNode.java
gui/src/main/java/org/astraea/gui/tab/BalancerNode.java
gui/src/main/java/org/astraea/gui/tab/BrokerNode.java
gui/src/main/java/org/astraea/gui/tab/ClientNode.java
gui/src/main/java/org/astraea/gui/tab/QuotaNode.java
gui/src/main/java/org/astraea/gui/tab/SettingNode.java
gui/src/main/java/org/astraea/gui/tab/topic/PartitionNode.java
gui/src/main/java/org/astraea/gui/tab/topic/ReplicaNode.java
gui/src/main/java/org/astraea/gui/tab/topic/TopicNode.java
gui/src/main/java/org/astraea/gui/text/TextInput.java

新增兩個頁面，第一個是可以讀取 topic
第二個頁面則是可以寫入資料
另外也將讀取 record timestamp的功能從`topic`頁面移除

[GUI] add read/write records tab

---

common/src/main/java/org/astraea/common/balancer/executor/StraightPlanExecutor.java
gui/src/main/java/org/astraea/gui/pane/PaneBuilder.java
gui/src/main/java/org/astraea/gui/tab/BalancerNode.java

手動在8節點1000個partitions測試，原本只有一個debounce不太穩，後續操作依然會遇到中間狀態，所以拉到到三個
另外也調整GUI當表格為空值的時候，將表格和第二控制區塊都收起來

More debounce for stable re-balance

---

app/src/test/java/org/astraea/app/web/GroupHandlerTest.java

[MINOR] Unused testGroups method

---

common/src/main/java/org/astraea/common/admin/Admin.java
common/src/main/java/org/astraea/common/consumer/Builder.java
common/src/main/java/org/astraea/common/consumer/Consumer.java
common/src/test/java/org/astraea/common/consumer/ConsumerTest.java

這隻PR是 #1093 的第一步，我們要將 consumer thread 從目前的執行緒中移出，這樣方便我們去銜接不同的 I/O (例如 file IO)

Enable consumer builder to build stream directly

---

common/src/main/java/org/astraea/common/cost/BrokerInputCost.java
common/src/main/java/org/astraea/common/cost/BrokerOutputCost.java
common/src/test/java/org/astraea/common/cost/BrokerInputCostTest.java
common/src/test/java/org/astraea/common/cost/BrokerOutputCostTest.java

Context: https://github.com/skiptests/astraea/pull/1103#discussion_r1019054271
原先 `BrokerInputCost` 和 `BrokerOutputCost` 使用 `OneMinuteRate` 來判斷各節點的輸入輸出負載重量。這個 PR 改用 `FifteenMinuteRate` 來衡量。這個指標看的時間比較長遠，較能反映出長遠下來的結果。

Use `FifteenMinuteRate` in `BrokerInputCost` and `BrokerOutputCost`

---

app/src/main/java/org/astraea/app/balancer/BalanceProcessDemo.java
app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
common/src/main/java/org/astraea/common/balancer/Balancer.java
common/src/main/java/org/astraea/common/balancer/algorithms/AlgorithmConfig.java
common/src/main/java/org/astraea/common/balancer/algorithms/GreedyBalancer.java
common/src/main/java/org/astraea/common/balancer/algorithms/SingleStepBalancer.java
common/src/main/java/org/astraea/common/cost/CostFunction.java
common/src/main/java/org/astraea/common/cost/NoSufficientMetricsException.java
common/src/test/java/org/astraea/common/balancer/BalancerAlgorithmTest.java
common/src/test/java/org/astraea/common/balancer/BalancerTest.java
common/src/test/java/org/astraea/common/balancer/algorithms/GreedyBalancerTest.java
gui/src/main/java/org/astraea/gui/tab/BalancerNode.java

resolve #1008.
* 把 `Balancer#offer()` 的 `brokerFolders` 參數移動到 `AlgorithmConfig` 裡面。
* 把 `executionTime` 參數從 `AlgorithmConfig` 移動到 `Balancer#offer` 函數簽名上。
* 實作 default interface method `Balancer#retryOffer()`,裡面會重複呼叫 `Balancer#offer`，如果遇到 `NoSufficientMetricsException` 時，在等一段時間後主動重試這個產生
這個 PR 在做 #955 在做的事情，只是從 `Balancer` 做起而非從 `BalancerHandler` 做起。這裡面還有很多要克服的問題
* 使 `BalancerHandler` 使用 `retryOffer`
* 使 `BalancerHandler` 內計算原本 cluster cost 的邏輯移動到 balancer 內部。
上述問題會在 #955 處理掉。

Enhance `Balancer` with retry mechanism

---

gui/src/main/java/org/astraea/gui/Query.java
gui/src/test/java/org/astraea/gui/QueryTest.java

如題，空白的字串應該使用`xxx=`來搜尋，`xxx=*`應該比對到任何有值的內容

[GUI] wildcard should exclude empty/blank string

---

common/src/main/java/org/astraea/common/partitioner/StrictCostDispatcher.java
common/src/test/java/org/astraea/common/partitioner/StrictCostDispatcherTest.java

現在的 `MetricCollector` `fetcher` 是共用的，相比之前的 `BeanCollector` 是每個 node 都有自己的 `fetcher` ，也因此不需要每新增一個 node 就加入 `fetcher`，故刪除。

Remove redundant fetcher adding

---

common/src/main/java/org/astraea/common/admin/Admin.java
common/src/test/java/org/astraea/common/admin/AdminTest.java

#1120 
把有操作 `host.() + ”:”` 相關的部份都替換成 `Admin#bootstrapSerbers`

add a test for bootstrapServers

---

docker/build_deps_image.sh

#1153 之後，我們可能會在 etl test scope 中加入更多相依性，因此 deps image 建置的時候要明確建構 etl test code確保相關的相依函式庫都有被拉進來

Deps image should include dependencies of etl test scope

---

app/src/main/java/org/astraea/app/balancer/BalanceProcessDemo.java
app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
common/src/main/java/org/astraea/common/admin/AdminImpl.java
common/src/main/java/org/astraea/common/admin/ClusterInfo.java
common/src/main/java/org/astraea/common/balancer/algorithms/AlgorithmConfig.java
common/src/main/java/org/astraea/common/balancer/algorithms/GreedyBalancer.java
common/src/main/java/org/astraea/common/balancer/algorithms/SingleStepBalancer.java
common/src/main/java/org/astraea/common/balancer/tweakers/AllocationTweaker.java
common/src/main/java/org/astraea/common/balancer/tweakers/ShuffleTweaker.java
common/src/test/java/org/astraea/common/admin/AdminTest.java
common/src/test/java/org/astraea/common/balancer/BalancerAlgorithmTest.java
common/src/test/java/org/astraea/common/balancer/BalancerTest.java
common/src/test/java/org/astraea/common/balancer/FakeClusterInfo.java
common/src/test/java/org/astraea/common/balancer/algorithms/GreedyBalancerTest.java
common/src/test/java/org/astraea/common/balancer/tweakers/ShuffleTweakerTest.java
gui/src/main/java/org/astraea/gui/tab/BalancerNode.java

resolve #1106
* 新增 `ClusterInfo#brokerFolders()`，透過 `Broker` 形態的 `NodeInfo` 來推導這個關係。
* 移除 `AlgorithmConfig#dataFolders()`，現在 Balancer 可以直接從傳入的 ClusterInfo 取得這些資訊。
* 移除 `AllocationTweaker#generate()` 函數簽名上的 data folder 需求，這個訊息可以從另外一個 ClusterInfo 參數中取得。

Embed broker folders information into `ClusterInfo`

---

app/src/test/java/org/astraea/app/web/RecordHandlerTest.java

新增一個基於純 json 字串的測試，避免我們習慣用物件直接測試 Web APIs 導致跳過 json 這一段

[WEB] add raw string case for RecordHandler

---

app/src/main/java/org/astraea/app/web/Channel.java
app/src/main/java/org/astraea/app/web/PostRequest.java
app/src/main/java/org/astraea/app/web/RecordHandler.java
app/src/main/java/org/astraea/app/web/Request.java
app/src/test/java/org/astraea/app/EnumInfoTest.java
app/src/test/java/org/astraea/app/web/RecordHandlerTest.java
app/src/test/java/org/astraea/app/web/RequestTest.java
app/src/test/java/org/astraea/web/TestUtils.java
app/src/test/java/org/astraea/web/TestUtilsTest.java
common/src/main/java/org/astraea/common/Utils.java
common/src/main/java/org/astraea/common/json/JsonConverter.java
common/src/main/java/org/astraea/common/json/TypeRef.java
common/src/test/java/org/astraea/common/json/JsonConverterTest.java
common/src/test/java/org/astraea/common/json/TypeRefTest.java

fix #974 Implement RecordHandler

astraea-974 Implement RecordHandler post request

---

app/src/main/java/org/astraea/app/web/Channel.java
app/src/main/java/org/astraea/app/web/RecordHandler.java
app/src/main/java/org/astraea/app/web/Request.java
app/src/test/java/org/astraea/app/web/RequestTest.java
common/src/main/java/org/astraea/common/Utils.java
common/src/main/java/org/astraea/common/json/JsonConverter.java

如題，移除`RequestObject`改以`Request`替代，並且限制request的轉型只能針對`Request`
已知限制：
Class a {
Optional<T> b;
}
上述的generic type `T` 目前沒有做進一步的檢查，換言之，handle 如何放了一個非 `Request` 在裡面，unit test 無法得知，但如果該型別可以正確通過 json 轉換，則 production code 視為沒問題

[WEB] Remove RequestObject

---

common/src/main/java/org/astraea/common/partitioner/PartitionerUtils.java
common/src/main/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobinDispatcher.java

現在的 `SmoothWeightRoundRobinDispatcher` 在全力打資料的時候，大概會執行在 1 分鐘後出現 heap 記憶體不足，其原因來自於內部的 arrayList 不斷的增大，之前沒有出現問題是因為之前的版本跟新速率沒有那麼快 (10 秒更新一次)，增加的速率也不會讓 heap 在 30 分鐘內耗盡。
現在修正為：有新的 partition 才加入 arrayList。
為了計算速度，新增了一個變數 `hasPartitionsSet` 用來紀錄元素是否已經出現過；同時保留原來的 arrayList ，用來做快速的隨機讀取。
---
新增一個 TODO，現在 partition 的選擇是從 broker 內的 partition 選擇 (紀錄在 `hasPartitions`)，但是卻沒有對 topic 篩選，如果這個 producer 同時會發送不同 topic 的 record，那有可能就會出錯了？
---
新增具有描述性的錯誤訊息。
現在的 `SmoothWeightRoundRobinDispatcher` 如果沒有配置 "partitioner.config" 的路徑，會跑出 `NullPointerException`。現在在讀檔前先檢查使用者是否有設定 "partitioner.config"。

Fix heap memory problem in SmoothWeightRoundRobinDispatcher

---

app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
common/src/main/java/org/astraea/common/metrics/collector/MetricCollector.java
common/src/main/java/org/astraea/common/metrics/collector/MetricCollectorImpl.java
common/src/main/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobinDispatcher.java
common/src/test/java/org/astraea/common/cost/BrokerInputCostTest.java
common/src/test/java/org/astraea/common/cost/BrokerOutputCostTest.java
common/src/test/java/org/astraea/common/cost/CpuCostTest.java
common/src/test/java/org/astraea/common/cost/MemoryCostTest.java
common/src/test/java/org/astraea/common/metrics/collector/MetricCollectorTest.java

beans 的索引責任即將交給 ClusterBean，因此 MetricsCollector 可以專心負責收集 beans 即可
ref: https://github.com/skiptests/astraea/pull/1171

Refactor MetricsCollector

---

app/src/main/java/org/astraea/app/backup/Exporter.java
app/src/main/java/org/astraea/app/backup/ImportCsv.java
common/src/main/java/org/astraea/common/Utils.java
common/src/test/java/org/astraea/common/UtilsTest.java
fs/src/main/java/org/astraea/fs/FileSystem.java
fs/src/test/java/org/astraea/fs/AbstractFileSystemTest.java
fs/src/test/java/org/astraea/fs/FileSystemTest.java
fs/src/test/java/org/astraea/fs/ftp/FtpFileSystemTest.java
fs/src/test/java/org/astraea/fs/local/LocalFileSystemTest.java

檔案系統的串接往往會陷入 dependency hell，因此我們入口處用動態的方式隔開各種相依性，同時開放呼叫者透過參數來決定要呼叫哪一種實作，例如：`Map.of("local.impl", "xxx")`可以指定 local file system 改成呼叫"xxx"這個實作，相關測試可以看`FileSystemTest.testOf`

[FS] enable to create file system dynamically

---

app/src/main/java/org/astraea/app/web/Channel.java
app/src/main/java/org/astraea/app/web/TopicHandler.java
app/src/test/java/org/astraea/app/web/TopicHandlerTest.java

我在 a1558e20 執行 Web Service，嘗試用他來建立 Topic，不過沒有建立成功。
```shell
curl -X POST --location "http://localhost:8001/topics" \
-H "Content-Type: application/json" \
-d "{
\"topics\": [
{
\"name\": \"shoot\",
\"partitions\": 100,
\"replicas\": 1
}
]
}"
```
```
{}
```
原因和目前 Channel 內的 HTTP Request Body 解析有關，目前的更動有讀取 Request Body 兩次的需求
https://github.com/skiptests/astraea/blob/41180158b5e6d4b78e410d77f233cbc7fbf414d2/app/src/main/java/org/astraea/app/web/Channel.java#L233-L234
不過 HttpExcange 回傳的 Request Body 在 InputStream 裡面，裡面的資料只能讀一次，導致 `PostRequest` 有內容但是 `Request` 版本的沒有內容，這個 PR 暫時把它改成預讀然後複製兩個 Buffer 出來供給資訊。

[WEB] Fix the HTTP request stream read issue temporarily

---

common/src/test/java/org/astraea/common/connector/ConnectorClientTest.java

如題，一樣是同步的問題， kafka connector 透過 kafka topic 來同步資料，因此會出現同步資料的時間區間，此時索取資料就會遇到`Cannot complete request momentarily due to stale configuration (typically caused by a concurrent config change)`
fix #1205

[CONNECTOR] Fix flaky ConnectorClientTest#testUrls

---

docker/start_worker.sh

一開始直接嘗試去檔案找特定內容會噴出檔案不存在的錯誤，因此這隻PR調整順序，會先嘗試設定 group.id 後，再去檔案內將 group.id 撈出來

[CONNECTOR] avoid weird error message from start_worker.sh

---

app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
common/src/main/java/org/astraea/common/admin/Admin.java
common/src/main/java/org/astraea/common/admin/AdminImpl.java
common/src/main/java/org/astraea/common/admin/ClusterInfo.java
common/src/main/java/org/astraea/common/admin/ClusterInfoBuilder.java
common/src/main/java/org/astraea/common/admin/NodeInfo.java
common/src/test/java/org/astraea/common/admin/AdminTest.java
common/src/test/java/org/astraea/common/admin/ClusterInfoBuilderTest.java
common/src/test/java/org/astraea/common/admin/ClusterInfoTest.java
common/src/test/java/org/astraea/common/admin/ReplicaInfoTest.java
common/src/test/java/org/astraea/common/balancer/FakeClusterInfo.java
common/src/test/java/org/astraea/common/balancer/executor/StraightPlanExecutorTest.java
common/src/test/java/org/astraea/common/balancer/tweakers/ShuffleTweakerTest.java
common/src/test/java/org/astraea/common/cost/ReplicaLeaderCostTest.java
common/src/test/java/org/astraea/common/cost/ReplicaNumberCostTest.java
common/src/test/java/org/astraea/common/cost/ReplicaSizeCostTest.java
common/src/test/java/org/astraea/common/partitioner/StrictCostDispatcherTest.java
common/src/test/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobinDispatchTest.java
common/src/test/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobinTest.java
gui/src/main/java/org/astraea/gui/Context.java
gui/src/main/java/org/astraea/gui/tab/BrokerNode.java
gui/src/main/java/org/astraea/gui/tab/topic/TopicNode.java
gui/src/test/java/org/astraea/gui/tab/BalancerNodeTest.java
gui/src/test/java/org/astraea/gui/tab/topic/ReplicaNodeTest.java

Resolve #1189, #1185.
* 移除 `NodeInfo` 的 `Comparable` 界面
* `ClusterInfo` 內使用 `List` 儲存 `Node`
* `Clusterinfo#of(List)` 移動到 test scope.

Remove `Comparable` interface from `NodeInfo`

---

connector/src/test/java/org/astraea/connector/ConnectorTest.java

worker re-balance 發生時就會導致測試失敗，因此調整成確認初始化和關閉的次數相同
fix #1225

[CONNECTOR] Fix flaky ConnectorTest#testRunCustomConnector

---

fs/build.gradle

fs module 並沒有用到 Kafka 程式碼，因此事先排除以免意外引入

[FS] exclude kafka dependency

---

common/src/main/java/org/astraea/common/admin/ClusterInfo.java
common/src/main/java/org/astraea/common/partitioner/StrictCostDispatcher.java
common/src/test/java/org/astraea/common/admin/ClusterInfoTest.java
common/src/test/java/org/astraea/common/cost/ClusterInfoIntegratedTest.java

#1215 引入了新的資料結構 `BrokerTopic`，這可以取代原本的`Map.Entry<Integer, String>`

Apply BrokerTopic to ClusterInfo

---

common/src/main/java/org/astraea/common/admin/ClusterBean.java
common/src/main/java/org/astraea/common/cost/ReplicaSizeCost.java
common/src/test/java/org/astraea/common/admin/ClusterBeanTest.java

Context: https://github.com/skiptests/astraea/pull/1215#discussion_r1041251610
* 給 `ClusterBean#*Metrics()` 的查詢方法實作快取機制。
* 給查詢方法添加測試
* 透過 `ClusterBean#replicaMetrics()` 取代 `ClusterBean#mapByReplica()`

Implement query cache mechanism for `ClusterBean#*Metrics()`

---

common/src/main/java/org/astraea/common/cost/BrokerInputCost.java
common/src/main/java/org/astraea/common/cost/BrokerOutputCost.java
common/src/main/java/org/astraea/common/cost/Dispersion.java
common/src/main/java/org/astraea/common/cost/ReplicaLeaderCost.java
common/src/main/java/org/astraea/common/cost/ReplicaSizeCost.java
common/src/test/java/org/astraea/common/cost/DispersionTest.java
common/src/test/java/org/astraea/common/cost/ReplicaLeaderCostTest.java

`Dispersion#correlationCoefficient` 的名稱看上去裡面的實作是[相關係數(correlation coefficient)](https://zh.wikipedia.org/zh-tw/%E7%9A%AE%E5%B0%94%E9%80%8A%E7%A7%AF%E7%9F%A9%E7%9B%B8%E5%85%B3%E7%B3%BB%E6%95%B0)，但實際上是[變異係數(coefficient of variation)](https://zh.wikipedia.org/zh-tw/%E5%8F%98%E5%BC%82%E7%B3%BB%E6%95%B0)，這個 PR 把名字改正。

Reame `Dispersion#correlationCoefficient` to `Dispersion#cov`

---

connector/src/main/java/org/astraea/connector/perf/PerfSink.java
connector/src/main/java/org/astraea/connector/perf/PerfSinkTask.java
connector/src/main/java/org/astraea/connector/perf/PerfSource.java
connector/src/main/java/org/astraea/connector/perf/PerfSourceTask.java
connector/src/test/java/org/astraea/connector/perf/PerfSinkTest.java
connector/src/test/java/org/astraea/connector/perf/PerfSourceTest.java

這是一隻很簡單的 perf sink，單純用來消費 topic 資料

[CONNECTOR] add perf sink

---

common/src/main/java/org/astraea/common/admin/ClusterBean.java
common/src/test/java/org/astraea/common/admin/ClusterBeanTest.java

slove [comment](https://github.com/skiptests/astraea/pull/1241#discussion_r1045209694)，`ClusterBean`在query指定類別的bean時，也應該檢查該類別的subClass

`ClusterBean` query metrics should check all subClass

---

common/src/main/java/org/astraea/common/cost/CostFunction.java
common/src/main/java/org/astraea/common/cost/HasClusterCost.java
common/src/test/java/org/astraea/common/cost/ClusterCostTest.java

Resolve #1134.
現在 BalancerHandler 吐出來的 function 欄位都是 HasClusterCost 預設的 toString 內容，目前裡面的資訊不包含優化算法的細節，這個 PR 嘗試 override `HasClusterCost#of()` 吐出來的 `Object#toString()`，在裡面提供一些和優化目標有關的文字資訊。
如 `WeightCompositeClusterCost[{"org.astraea.common.cost.ReplicaLeaderCost@24b03118" weight 1.0}, {"org.astraea.common.cost.ReplicaSizeCost@4324ac4e" weight 1.0}]`
```
http://localhost:8001/balancer/ff897675-d061-431e-9255-ea6b28256249
POST http://localhost:8001/balancer
Content-Type: application/json
{
"timeout": "10s",
"balancer": "org.astraea.common.balancer.algorithms.GreedyBalancer",
"balancer-config": {
"shuffle.plan.generator.min.step": "1",
"shuffle.plan.generator.max.step": "5"
},
"costWeights": [
{
"cost": "org.astraea.common.cost.ReplicaLeaderCost",
"weight": 1
},
{
"cost": …
```

Provide descriptive text in `HasClusterCost#of()#toString()`

---

common/src/main/java/org/astraea/common/metrics/connector/ConnectorMetrics.java
common/src/main/java/org/astraea/common/metrics/connector/SinkTaskInfo.java
common/src/main/java/org/astraea/common/metrics/connector/SourceTaskInfo.java
common/src/main/java/org/astraea/common/metrics/connector/TaskError.java
connector/src/test/java/org/astraea/connector/perf/PerfSinkTest.java
connector/src/test/java/org/astraea/connector/perf/PerfSourceTest.java
gui/src/main/java/org/astraea/gui/Context.java
gui/src/main/java/org/astraea/gui/tab/ConnectorNode.java

[CONNECTOR] add sink metrics

---

common/src/main/java/org/astraea/common/connector/Builder.java
common/src/main/java/org/astraea/common/connector/ConnectorStatus.java
common/src/test/java/org/astraea/common/connector/ConnectorClientTest.java
gui/src/main/java/org/astraea/gui/tab/ConnectorNode.java

如題，不過該欄位在先前的 kafka 是一個 bug (總是 null），因此我們將該欄位宣告成 `Optional<String>`

[CONNECTOR][GUI] fetch connector type from /status API

---

common/src/main/java/org/astraea/common/producer/Builder.java
common/src/main/java/org/astraea/common/producer/Record.java
connector/src/main/java/org/astraea/connector/SourceConnector.java
connector/src/main/java/org/astraea/connector/SourceRecord.java
connector/src/main/java/org/astraea/connector/SourceTask.java
connector/src/test/java/org/astraea/connector/SourceTest.java
it/src/main/java/org/astraea/it/Services.java

#870 等 connector 需要儲存外部系統的資料索引，因此我們引入 `SourceRecord`讓使用者可以存放外部系統的資訊在 kafka 內部，下一隻PR會將對應的 offset storage 暴露出來

[CONNECTOR] add source record

---

connector/src/main/java/org/astraea/connector/MetadataStorage.java
connector/src/main/java/org/astraea/connector/SourceConnector.java
connector/src/main/java/org/astraea/connector/SourceRecord.java
connector/src/main/java/org/astraea/connector/perf/PerfSource.java
connector/src/test/java/org/astraea/connector/ConnectorTest.java
connector/src/test/java/org/astraea/connector/MetadataStorageTest.java

source connector 可以將額外的資訊存放在另一個 topic 中，可以用來標注“來源端”的額外資訊，例如紀錄某個來源端的資料已經讀取到哪個位置

[CONNECTOR] add metadata storage to source connector

---

common/src/main/java/org/astraea/common/partitioner/RoundRobin.java
common/src/main/java/org/astraea/common/partitioner/StrictCostDispatcher.java
common/src/test/java/org/astraea/common/partitioner/RoundRobinTest.java

Solve #598 
Kafka Producer metrics 中，`producer-node-metrics` 中的 `request-latency-avg` 會出現 NaN 的原因是，當我們的 `request-latency-avg` 在某一次測到很高的值時，我們的 `StrictCostDispatcher` 會完全不發送資料到該節點上，不發送資料 `request-latency-avg` 就不會更新，所以一直保持在很高的值沒辦法更新。最後超過紀錄的時間區間，然後變成沒有數據 NaN。
這隻 PR 的解決方法是，就由平移計算出來的 broker 分數，來讓 `StrictCostDispatcher` 也有機會選到 cost 最高的 broker。
---
實際跑過以後也沒有觀察到 NaN 的狀況，結果也超乎預期：
以下是實驗環境簡單敘述：
實驗執行軟體
| 執行軟體                 |  B1  |  B2  |  B3  |  C1  |  C2  |  C3  |
| ------------------------ | :--: | :--: | :--: | :--: | :--: | :--: |
| Zookeeper                |  V   |      |      |      |      |      |
| Kakfa Broker             |  V   |  V   |  V   |     |     |      |
| Node Exporter            |  V   |  V   |  V   |     |     |      |
| Prometheus               |      |      |   V   |      | …

Move score away from zero

---

common/src/main/java/org/astraea/common/partitioner/Dispatcher.java
common/src/test/java/org/astraea/common/partitioner/DispatcherTest.java

考量`null`在 kafka 的特殊地位，我們不應該隨意將`null`轉換成 empty array

[DISPATCHER] enable null key and null value

---

app/src/main/java/org/astraea/app/performance/TrackerThread.java

在 Intellij 執行 performance tool 時，intellij 會跳出錯誤：
其實這個是 `TrackerThread` 印出來的 `recordErrorRate`，但是 "  error: " 開頭的訊息似乎會被 intellij 當成是錯誤訊息，這裡修改 `TrackerThread` 打印出來的內容，不要讓 intellij 誤會。
---
重現方法與參數：
在 intellij 上方中間偏右的地方設定參數，然後按綠色三角形開始跑，最下方的執行結果就會跳出 `1 error`。
以下是參數
"run --args="performance --bootstrap.servers 192.168.103.185:9092 --topics simple --run.until 30s"

Change tracker print out message

---

app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
common/src/main/java/org/astraea/common/balancer/Balancer.java
common/src/main/java/org/astraea/common/balancer/algorithms/GreedyBalancer.java
common/src/main/java/org/astraea/common/balancer/algorithms/SingleStepBalancer.java
common/src/test/java/org/astraea/common/balancer/BalancerAlgorithmTest.java
common/src/test/java/org/astraea/common/balancer/BalancerTest.java
common/src/test/java/org/astraea/common/balancer/algorithms/GreedyBalancerTest.java
common/src/test/java/org/astraea/common/cost/NetworkCostTest.java
docs/web_server/web_api_balancer_chinese.md
gui/src/main/java/org/astraea/gui/tab/BalancerNode.java
gui/src/test/java/org/astraea/gui/tab/BalancerNodeTest.java

Resolve #1308.
```json
{
"done": false,
"generated": true,
"id": "4110d2b7-d7b4-42ec-8527-aee453d0e33e",
"report": {
"function": "WeightCompositeClusterCost[{\"org.astraea.common.cost.ReplicaLeaderCost@5f041d67\" weight 1.0}, {\"org.astraea.common.cost.ReplicaSizeCost@5d0bc877\" weight 1.0}]"
},
"scheduled": false
}
```
現在 Balancer Web API 遇到找不到更好計劃的情況時，`GET /balancer/{id}` 回傳的結果看起來像上面的 json，內容沒有太多關於計劃沒生出來的提示，使用者看到可能會很混淆。會造成這個的主要原因是 `Balancer#offer` 回傳 `Optional<Balancer.Plan>`，由於 Optional 的存在我們基本上不知道為什麼計劃沒辦法被生成出來，也不清楚目前叢集的 `ClusterCost` 分數(initial cluster cost)，基本上 initial cluster cost 就算找不到更好的計劃也可以計算出來，但因為 `Optional` 的關係這個資訊只有在計劃真的計算出來時才能提供（最早 BalancerHandler 的設計是儘管找不到更好的計劃，也能提供 initial cost，但因為 `Balancer#retryOffer` 的 PR，這個計算 initial cost 的邏輯被迫從 Handler 移動到 Balancer 界面裡面，因此這個訊息被迫和 …

[WEB] Provide extra failure information from Balancer response

---

common/src/main/java/org/astraea/common/connector/Builder.java
common/src/main/java/org/astraea/common/connector/ConnectorClient.java
common/src/main/java/org/astraea/common/connector/ConnectorStatus.java
common/src/main/java/org/astraea/common/connector/TaskStatus.java
common/src/test/java/org/astraea/common/connector/ConnectorClientTest.java
connector/src/test/java/org/astraea/connector/ConnectorTest.java

`connectorStatus`回傳的`task`中現在會攜帶`configs`，除此之外，這隻PR也移除了`connectorInfo`因為它完全可以被`connectorStatus`取代

[CONNECTOR] add task configs

---

connector/src/main/java/org/astraea/connector/perf/PerfSink.java
connector/src/main/java/org/astraea/connector/perf/PerfSource.java
gui/src/main/java/org/astraea/gui/tab/ConnectorNode.java

如題，同時也修正了`frequency.in.seconds`的命名問題，改成`frequency`因為使用者可以自帶單位

[CONNECTOR] show task configs

---

app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java

Resolve #1320
`BalancerHandler.Change` 的 before/after 輸出順序有一定的規則，第一個 element 必須要是 Partition 的 Preferred Leader。這個 PR 新增這個排序規則還有寫測試確保這個行為。

[WEB] Fix the placement output order of `Change#before` and `Change#after`

---

common/src/main/java/org/astraea/common/Utils.java
common/src/main/java/org/astraea/common/metrics/stats/Rate.java
common/src/test/java/org/astraea/common/UtilsTest.java
connector/src/main/java/org/astraea/connector/perf/PerfSource.java
connector/src/test/java/org/astraea/connector/perf/PerfSourceTest.java

如題，現在`PerfSource`支援`throughput`限制輸出資料的速率，這可以搭配`specify.partitions`來設定各個 partitions的輸出速度

[PERF] add throughput to PerfSource

---

common/src/main/java/org/astraea/common/cost/NetworkCost.java
common/src/main/java/org/astraea/common/cost/NetworkEgressCost.java
common/src/main/java/org/astraea/common/cost/NetworkIngressCost.java
common/src/test/java/org/astraea/common/cost/NetworkCostTest.java

Resolve #1326.
讓 `NetworkCost` 把 follower replica 造成的流量納入考量。
* 黃色線是所有節點的網路卡看到的流量之平均
* 綠色線是所有節點的 BytesInPerSec + ReplicationBytesInPerSec 之平均
* 藍色線是 CostFunction 預計會看到的，所有節點的輸入流量 之平均
黃色線和綠色線之間有一個微妙約 20 MB/s 的差異，這個差異可能是來自 Protocol 的額外資料開銷，這部分應該是沒辦法直接用 JMX metrics 取得
1. 兩個 Topic，各 100 個 Partition, Replication Factor 2，依照 Kafka 創建 topic 的邏輯擺放。
2. Partition 輸入流量速率固定
3. Partition 的流量依照 Zipfian 分配
上圖中的 `BrokerIngress` 和 `BrokerEgress` 是各節點的 `BytesInPerSec + ReplicationBytesInPerSec`
上圖的 Max-min time series 是各時間點最大流量和最小流量的差異，因為線太多、加上現在的情境複雜很難把流量都聚集成一條線，所以用他反映負載有沒有比較集中

Make `NetworkCost` replication bandwidth aware

---

gui/src/main/java/org/astraea/gui/tab/topic/TopicNode.java

新增可顯示健康的頁面，上圖是顯示不可讀或寫的partitions

[GUI] add health page to show the nonavailable topic/partition

---

app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java

現在 move cost 固定會出幾個面向的報告，當選擇的 cost function 不支援該項報告時，就可能產生某個報告會有 0 的結果，因此這隻PR將測試改成“一定會有一項報告會有不為0的數值"
resolve #1318

fix flaky BalancerHandlerTest#testTopics

---

connector/src/main/java/org/astraea/connector/SinkConnector.java
connector/src/main/java/org/astraea/connector/backup/Exporter.java
connector/src/test/java/org/astraea/connector/backup/ExporterTest.java

[CONNECTOR] apply required flag to Exporter definition

---

app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java

Context #1335 
一個測試有問題，應該等最後一個 commit 的測試跑完再按合併...
https://github.com/skiptests/astraea/actions/runs/3787179796/jobs/6438738489#step:5:897
```
BalancerHandlerTest > testNoReport() FAILED
java.lang.NullPointerException
at org.astraea.app.web.BalancerHandlerTest.testNoReport(BalancerHandlerTest.java:418)
```

Fix `BalancerHandlerTest#testNoReport`

---

docker/start_etl.sh
etl/src/main/scala/org/astraea/etl/ReadStreams.scala

如題，允許探索多階層的目錄，同時在腳本中印出 application web 位址

[ETL] enable to recursive looking for source path

---

docker/start_etl.sh

如題，統一用`RESOURCES_CONFIGS`來設定 spark job memory

[ETL] use RESOURCES_CONFIGS instead of HEAP_OPTS

---

connector/src/main/java/org/astraea/connector/backup/Importer.java
connector/src/test/java/org/astraea/connector/backup/ImporterTest.java

related to #1262 #1188 
- 引用 `FtpFileSystem` 的常數
- apply documentation and require flag for definition
- use interface as declaration
- add test `testRequireConfigs()`
fix #1297 
fix #1299

[CONNECTOR] apply documentation require flag in Importer definition

---

app/src/main/java/org/astraea/app/web/BalancerHandler.java
common/src/main/java/org/astraea/common/balancer/executor/StraightPlanExecutor.java
common/src/main/java/org/astraea/common/cost/NetworkCost.java
common/src/test/java/org/astraea/common/balancer/BalancerTest.java
docs/web_server/web_api_balancer_chinese.md

Context: #1325
目前 Kafka 的實作在面對 Data-Directory 的搬移時有機會觸發節點內部的實作錯誤，導致搬移卡住不結束。這個情況會使 Web Service 無法做其他計劃的生成或執行。這個 PR 暫時移除實作內的 Data-Directory Migration 行為

Disable data-directory migration

---

README.md
docs/build_project.md

如題，#1053 已經將`application`外掛從 GUI 移除，因此舊有的執行方式已經不適合

[GUI][DOC] update docs about running GUI tool

---

connector/src/main/java/org/astraea/connector/backup/Exporter.java
connector/src/test/java/org/astraea/connector/backup/ExporterTest.java

kafka connector 並不會主動匯入 default value，因此我們在解析參數的時候要自行取得 default value

[BACKUP] size of exporter should be optional

---

app/src/main/java/org/astraea/app/performance/DataGenerator.java
app/src/main/java/org/astraea/app/performance/Performance.java
app/src/main/java/org/astraea/app/performance/ProducerThread.java
app/src/test/java/org/astraea/app/performance/PerformanceTest.java
docs/performance_benchmark.md

此 PR 為 Performance tool 新增一個判斷式，用來判斷有沒有開啟 throttle
突然想到當初沒有測到沒加入 throttle 功能的打資料效果，發現會影響到 performance tool producers 的吞吐量，如下圖`實作throttle前`與`實作throttle後`的差異
`實作throttle前`的 Revision number: 3123a226e1073121bc1072221937af0ed3212fbe 
測試指令:
```=bash
./start_app.sh performance --bootstrap.servers 192.168.103.171:9092,192.168.103.172:9092,192.168.103.173:9092 --topics a1,a2,a10 --producers 5 --consumers 0 --run.until 3m
```
經過確認後發現是修改 partition selector 的問題，需要加上一個判斷式來判斷有無 throttle
****
下圖為此 PR 修正後的測試 throttle 功能的數據
1. 沒有設置 throttle 的指令
```=bash
ACCOUNT=harryteng9527 VERSION=fix-non-throttle ./start_app.sh performance --bootstrap.servers 192.168.103.171:9092,192.168.103.172:9092 --topics a1,a2,a10 --producers 5 --consumers 0 --run.until 3m
```
2. 設置 throttle 的指令
```=bash
ACCOUNT=harryteng9527 …
```

Fix performance tool non throttle 

---

app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
docs/web_server/web_api_balancer_chinese.md

Resolve #1387.
移除 `POST /balancer` 的  `costWeights` 的預設值，因為不存在一個固定的預設優化項目能涵蓋所有叢集的問題。

[WEB] Make `costWeights` a mandatory argument in `POST /balancer`

---

common/src/main/java/org/astraea/common/partitioner/Dispatcher.java
common/src/main/java/org/astraea/common/partitioner/StrictCostDispatcher.java
common/src/main/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobinDispatcher.java

這隻 PR 將 `Dispatcher` 改成 `abstract class`，這樣做的目的如下：
1. `Dispatcher` 將提供更多基礎設施（例如定時同步 ClusterInfo)，改成 abstract class 可以包存該些資訊在上層類別
2. 可以給予我們更強大的限制來阻擋 kafka 的內容暴露到下層

[DISPATCHER] change Dispatcher from interface to abstract class

---

common/src/main/java/org/astraea/common/partitioner/Dispatcher.java
common/src/main/java/org/astraea/common/partitioner/StrictCostDispatcher.java
common/src/main/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobin.java
common/src/main/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobinDispatcher.java
common/src/test/java/org/astraea/common/partitioner/DispatcherTest.java

這隻 PR 將 `Admin` 整合到 `Dispatcher` 裡面，如此下游的 Dispatcher 可以確保收到“完整"的 ClusterInfo，如此之後各個成本都可以統一面對 `Replica`

[DISPATCHER] create Admin for all dispatcher to fetch full cluster info

---

common/src/main/java/org/astraea/common/cost/BrokerInputCost.java
common/src/main/java/org/astraea/common/cost/BrokerOutputCost.java
common/src/main/java/org/astraea/common/cost/CpuCost.java
common/src/main/java/org/astraea/common/cost/HasBrokerCost.java
common/src/main/java/org/astraea/common/cost/LoadCost.java
common/src/main/java/org/astraea/common/cost/MemoryCost.java
common/src/main/java/org/astraea/common/cost/NeutralIntegratedCost.java
common/src/main/java/org/astraea/common/cost/NodeMetricsCost.java
common/src/main/java/org/astraea/common/cost/ReplicaLeaderCost.java
common/src/main/java/org/astraea/common/cost/ReplicaSizeCost.java
common/src/main/java/org/astraea/common/partitioner/StrictCostDispatcher.java
common/src/test/java/org/astraea/common/cost/NeutralIntegratedCostTest.java
common/src/test/java/org/astraea/common/partitioner/StrictCostDispatcherTest.java

如題，現在`Dispatcher`已經可以提供`Replica`，所以將介面改成使用`ClusterInfo<Replica>`
related to #1403

[COST] replace ReplicaInfo by Replica for HasBrokerCost

---

app/src/main/java/org/astraea/app/performance/ProducerThread.java
app/src/main/java/org/astraea/app/performance/Report.java
app/src/main/java/org/astraea/app/performance/TrackerThread.java
common/src/main/java/org/astraea/common/admin/ClusterInfo.java
common/src/main/java/org/astraea/common/metrics/stats/Avg.java
common/src/main/java/org/astraea/common/metrics/stats/Max.java
common/src/main/java/org/astraea/common/partitioner/Dispatcher.java
common/src/test/java/org/astraea/common/metrics/stats/AvgTest.java
common/src/test/java/org/astraea/common/metrics/stats/MaxTest.java
common/src/test/java/org/astraea/common/partitioner/DispatcherTest.java

#1403 後的幾個效能修正：
1. leader 的資訊很常被使用，因此快取起來
2. 更新 ClusterInfo 的時機改成用`nano`計算，避免在 ms 層級會同時觸發多個更新
3. producer thread 新增 e2e 延遲的統計，這個路徑包含使用 producer buffer/partitioner 的延遲

[DISPATCHER] reduce the overhead of collecting leader info

---

common/src/main/java/org/astraea/common/cost/NodeSizeCost.java
common/src/main/java/org/astraea/common/partitioner/StrictCostDispatcher.java
common/src/test/java/org/astraea/common/partitioner/StrictCostDispatcherTest.java

新增一個簡單的成本估計用來平衡節點之間的資料量，同時也修正 score 會出現0的例外狀況

[COST][DISPATCHER] add NodeSizeCost to balance broker data size

---

it/src/main/java/org/astraea/it/Services.java

related to #435
如果總共有3個 brokers，分別是0,1,2，當測試中提前關閉了`1`後，陣列中的brokers會剩下0,2，但在走訪時我們會是呼叫關閉0,1，這樣會導致broker=2的並不會被關閉

[TEST] fix the potential bug of broker leak

---

app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/main/java/org/astraea/app/web/RecordHandler.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
common/src/main/java/org/astraea/common/Utils.java
common/src/main/java/org/astraea/common/assignor/Assignor.java
common/src/main/java/org/astraea/common/json/JsonConverter.java
common/src/main/java/org/astraea/common/partitioner/StrictCostDispatcher.java
common/src/test/java/org/astraea/common/UtilsTest.java
common/src/test/java/org/astraea/common/assignor/AssignorTest.java
common/src/test/java/org/astraea/common/json/JsonConverterTest.java
common/src/test/java/org/astraea/common/partitioner/StrictCostDispatcherTest.java
docs/web_server/web_api_balancer_chinese.md

`Duration`和`DataSize`很常用在request/response，因此我們直接支援該型別的轉換來減少程式碼
fix #1121

[COMMON] Json converter should support DataSize and Duration

---

connector/src/test/java/org/astraea/connector/backup/ExporterTest.java

fix #1432 
目前推測可能因為中間睡眠的時間太短，在處理完 `record 1,2` 這兩筆後 間隔 `record 3` 可能不超過 100ms，因此沒有將檔案分割開來。
目前先將中間的睡眠時間拉長，並在每個 `task` 的最後把 `task` 關閉，因為在本機連續測試時，最後沒有將 `task` 關閉可能會導致中間某次因其他原因失敗。
當下在本機上面跑過百次沒有出現這狀況，因此先試試看這個錯誤到底是不是因為這個導致的

Fix flaky ExporterTest#testFtpSinkTaskIntervalWith2Writers

---

common/src/main/java/org/astraea/common/admin/AdminImpl.java
common/src/main/java/org/astraea/common/admin/ConsumerGroup.java
common/src/test/java/org/astraea/common/admin/AdminTest.java

`assignor`和`state`可以幫助我們查看更多資訊，`GUI`的更正會下再下一隻PR完成

[COMMON] add assignor and state to ConsumerGroup

---

app/src/main/java/org/astraea/app/performance/Performance.java
app/src/main/java/org/astraea/app/performance/ReportFormat.java

* 移除 `Performance#main` 函數簽名上的 `throws IOException`
* 簡化 `Performance#execute` 中和 file writer 有關的呼叫邏輯

[PERF] Remove `IOException` from performance tool method signature

---

common/src/main/java/org/astraea/common/admin/Admin.java
common/src/main/java/org/astraea/common/admin/AdminImpl.java
common/src/main/java/org/astraea/common/balancer/executor/StraightPlanExecutor.java
common/src/test/java/org/astraea/common/admin/AdminTest.java

Context: https://github.com/skiptests/astraea/issues/1393#issuecomment-1382656937
這個 PR 新增 `Admin#moveOrSetPreferredFolders()`，這個函數嘗試移動給定的 replica 到特定的 data folder，如果給定的 replica 不存在於特定的節點，則在該節點宣告 preferred data folder，當該 replica 在未來被移動到的那個節點時，將會直接採用當初指定的 preferred data folder 儲存資料，而非交由 Kafka 的實作細節決定儲存的 data folder。
這個 PR 順便修正 `StraightPlanExecutor` 的邏輯，在開始 broker to broker 的 replica movement 之前，會先透過這個 API 觸發 folder to folder 和 preferred data dir 的宣告。理論上這樣做可以多少減少一些 #1325 問題觸發的方式

[COMMON] Implementation of `Admin#declarePreferredDataFolders(Map)`

---

common/src/main/java/org/astraea/common/admin/ClusterBean.java
common/src/main/java/org/astraea/common/cost/NodeMetricsCost.java
common/src/test/java/org/astraea/common/cost/NodeMetricsCostTest.java

基於`node`的成本會在節點沒有對應指標時回傳“空”的成本，這會導致該節點無法被納入評估，因此這隻PR賦予所有“沒有指標”的節點最基本的分數 - max cost，代表該些節點也應該被考慮，但不是最佳優先

[COST] make sure all brokers have cost

---

common/src/test/java/org/astraea/common/metrics/broker/LogMetricsTest.java
common/src/test/java/org/astraea/common/metrics/broker/NetworkMetricsTest.java
common/src/test/java/org/astraea/common/metrics/broker/ServerMetricsTest.java
common/src/test/java/org/astraea/common/metrics/broker/ServerTopicMetricsTest.java

有些測試忘了呼叫 `Service#close()` 來關閉測試用的叢集。

[TEST] Fix lost `Service#close()` call

---

common/src/main/java/org/astraea/common/cost/HasClusterCost.java

給 `HasClusterCost#of()` 回傳的 CostFunction 所回傳的 `ClusterCost` 提供一個可讀性高的 `Object#toString()` 實作。如此一來能夠看到比較細緻的 Cost 組合資訊，如：
```java
var plan = balancer.offer(clusterInfo, Duration.ofSeconds(10));
System.out.println(plan.solution().get().proposalClusterCost());
```
```
WeightCompositeClusterCost[{"org.astraea.common.cost.ReplicaNumberCost@73035e27" cost 1.0 weight 3.0}, {"org.astraea.common.cost.NetworkIngressCost@64c64813" cost 6.107885824866958E-5 weight 1.0}, {"org.astraea.common.cost.NetworkEgressCost@3ecf72fd" cost 6.107885824866958E-5 weight 1.0}] = 3.0001221577164974
```

[COST] Provide descriptive `toString()` implementation for weight composite function

---

common/src/main/java/org/astraea/common/cost/ClusterCost.java
common/src/main/java/org/astraea/common/cost/ReplicaNumberCost.java
common/src/test/java/org/astraea/common/cost/ReplicaNumberCostTest.java

原先的 `ReplicaNumberCost#clusterCost` 實作，他的函數值域是 [0, Long.MAX]，數值本身的含義是 max broker replica number 和 min number 的差異，這個數字本身不適合 Balancer 框架使用，因為他的值域和其他 CostFunction 不一樣（不是[0,1]），這使得他的權重會便得很難調配。
這個 PR 把他的實作的值域改成 [0, 1]，數值含義是負載不平衡的比例

[COST] Rewrite `ReplicaNumberCost#clusterCost`

---

connector/src/test/java/org/astraea/connector/backup/ExporterTest.java
fs/build.gradle
fs/src/main/java/org/astraea/fs/FileSystem.java
fs/src/main/java/org/astraea/fs/hdfs/HdfsFileSystem.java
fs/src/test/java/org/astraea/fs/hdfs/HdfsFileSystemTest.java
gradle/dependencies.gradle
it/build.gradle
it/src/main/java/org/astraea/it/HdfsServer.java

#1391 
當前方式是透過 `hadoop.minicluster` 創建本地端的 `hdfs` ，也順便寫了 `hdfs` 版的 `sink task` 測試來看看是否可以正確執行。

[CONNECTOR] Add hdfs server, hdfsFileSystem and tests

---

common/src/main/java/org/astraea/common/cost/HasClusterCost.java
common/src/test/java/org/astraea/common/cost/ClusterCostTest.java

確保 `HasClusterCost#of` 回傳的 Cost 值被依照權重標準化到 [0, 1] 的區間。
目前的 `HasClusterCost#of` 回傳的權重組合 cost function 是直接將數值乘上權重後相加，最後值會介於 [0, TotalWeight] 之間。這個數字在觀察上不太方便，如我們看到值是 `3`，我們可能因為不確定上限而無法直接聯想到這個值在整體的好壞狀況。這個 PR 多一個步驟把值壓在 [0, 1] 之間，這樣做的好處：
1. 符合 Cost Function 的設計。
2. `HasClusterCost#of` 可以串 `HasClusterCost#of`。
3. 我們知道上限是 1，如果看到 `0.3` 可以直接聯想到他在整個值域的位置。

[COST] Normalize the return value of `ClusterCost` from `HasClusterCost#of`

---

app/src/main/java/org/astraea/app/performance/ReportFormat.java

如題，增加 performance tool report 紀錄的項目。
增加  publish e2e latency 。這個數據是實際使用 `KafkaProducer` 的使用者，實際感受到的發送延遲。

[PERF] Add publish e2e latency to report

---

app/src/main/java/org/astraea/app/performance/AbstractThread.java

在 #1481 看到誤用，因此將`AbstractThread`改成 package-private

[PERF] make AbstractThread package-private

---

common/src/main/java/org/astraea/common/DistributionType.java
common/src/test/java/org/astraea/common/DistributionTypeTest.java

fix #1478 
https://github.com/skiptests/astraea/pull/1485#discussion_r1100926542
與 #1485 類似，區別在於使用的是 `Collections.binarySearch()` 方法來找值，相對於 #1485 的方法 (使用 `TreeMap` 做資料結構儲存) 較為節省記憶體空間。
還需要再麻煩 @garyparrot 驗證看看。

[PERF] Binary search on zipfian value generating

---

docker/start_hadoop.sh

`sed`在不同的shell會有不同的用法，例如下方就是在OSX執行腳本時會出現的錯誤
```
sed: 1: "/tmp/13805-hdfs.xml": invalid command code 1
```
這隻PR改成通通都用`echo`，並且避免出現很寬的行數

[HDFS] simplify/fix start_hadoop.sh for OSX

---

docker/start_hadoop.sh

[HDFS] export JAVA_HOME for hadoop script

---

app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
common/src/main/java/org/astraea/common/admin/AdminImpl.java
common/src/main/java/org/astraea/common/admin/ClusterInfo.java
common/src/main/java/org/astraea/common/admin/ClusterInfoBuilder.java
common/src/main/java/org/astraea/common/admin/Config.java
common/src/main/java/org/astraea/common/admin/TopicChecker.java
common/src/main/java/org/astraea/common/balancer/executor/StraightPlanExecutor.java
common/src/main/java/org/astraea/common/partitioner/Dispatcher.java
common/src/test/java/org/astraea/common/admin/AdminTest.java
common/src/test/java/org/astraea/common/admin/ClusterInfoBuilderTest.java
common/src/test/java/org/astraea/common/admin/ClusterInfoIntegratedTest.java
common/src/test/java/org/astraea/common/admin/ClusterInfoTest.java
common/src/test/java/org/astraea/common/balancer/FakeClusterInfo.java
common/src/test/java/org/astraea/common/cost/ClusterInfoIntegratedTest.java
common/src/test/java/org/astraea/common/cost/RecordSizeCostTest.java
common/src/test/java/org/astraea/common/cost/ReplicaLeaderCostTest.java
common/src/test/java/org/astraea/common/cost/ReplicaLeaderSizeCostTest.java
common/src/test/java/org/astraea/common/partitioner/StrictCostDispatcherPerfTest.java
gui/src/test/java/org/astraea/gui/tab/health/BalancerNodeTest.java
gui/src/test/java/org/astraea/gui/tab/topic/ReplicaNodeTest.java

Context: #1393
讓 `ClusterInfo` 攜帶 Topic-level 的設定資訊，未來 `DataDirSpaceUsageCost` 會需要 retention/compaction 相關的設定來協助判斷各個 partition 對儲存空間的需求。

[COMMON] Implementation of `ClusterInfo#topics`

---

common/src/main/java/org/astraea/common/cost/NetworkCost.java
common/src/test/java/org/astraea/common/cost/NetworkCostTest.java

修正兩個 `NetworkCost` 的 bug
* `NetworkCost` 的統計結果中沒有考慮到沒有 replica 的 broker，導致後面統計時會忽略完全空負載的節點。
* `NetworkCost` 的 MetricSensor，針對沒有 replica 的 broker 不會撈回任何 metrics，導致 `NetworkCost#noMetricCheck` 認為還沒有至少一個階段的 metrics 被完全索取而拒絕計算。修正方法為現在刻意撈取 `JmxMemory`，這個 metric 在沒有 replica 的 broker 上也能撈得到。

[COST] Fix `NetworkCost` raises an exception when some brokers have no replica

---

common/src/main/java/org/astraea/common/metrics/client/HasCoordinatorMetrics.java
common/src/main/java/org/astraea/common/metrics/client/HasNodeMetrics.java
common/src/main/java/org/astraea/common/metrics/client/HasSelectorMetrics.java
common/src/main/java/org/astraea/common/metrics/client/admin/AdminMetrics.java
common/src/main/java/org/astraea/common/metrics/client/consumer/HasConsumerCoordinatorMetrics.java
common/src/main/java/org/astraea/common/metrics/client/consumer/HasConsumerFetchMetrics.java
common/src/main/java/org/astraea/common/metrics/client/consumer/HasConsumerMetrics.java
common/src/main/java/org/astraea/common/metrics/client/producer/HasProducerMetrics.java
common/src/main/java/org/astraea/common/metrics/client/producer/HasProducerTopicMetrics.java
common/src/main/java/org/astraea/common/metrics/connector/ConnectCoordinatorInfo.java
common/src/main/java/org/astraea/common/metrics/connector/ConnectWorkerConnectorInfo.java
common/src/main/java/org/astraea/common/metrics/connector/ConnectWorkerInfo.java
common/src/main/java/org/astraea/common/metrics/connector/ConnectWorkerRebalanceInfo.java
common/src/main/java/org/astraea/common/metrics/connector/ConnectorMetrics.java
common/src/main/java/org/astraea/common/metrics/connector/ConnectorTaskInfo.java
common/src/test/java/org/astraea/common/metrics/connector/ConnectorMetricsTest.java
connector/src/test/java/org/astraea/connector/perf/PerfSinkTest.java
connector/src/test/java/org/astraea/connector/perf/PerfSourceTest.java

fix #1496
- 新增 "kafka.connect" metrics `app-info` `connect-coordinator-metrics` `connect-metrics` `connect-node-metrics` `connect-worker-metrics` `connect-worker-rebalance-metrics` `connector-metrics`
- rename file `ConnectorInfo` to `ConnectorTaskInfo`  (connector-task-metrics) 因為將新增的 connector-metrics 命名為前者
- 新增 `HasCoordinatorMetrics` -> 將 consumer 及 connector 的 coordinator 合併共同 metrics 
- 新增 `HasSelectorMetrics` -> admin, consumer, producer, connector -metrics 合併共同 metrics
- 新增測試 `ConnectorMetricsTest`

[METRICS] Append worker metrics

---

common/src/main/java/org/astraea/common/cost/NetworkCost.java
common/src/test/java/org/astraea/common/cost/NetworkCostTest.java

Resolve #1285.
原本 `NetworkCost` 的分數計算方式，在同時優化網路輸入和網路輸出時會出現分數意義不平等的現象，可能導致優化結果不理想。這個 PR 修改 `NetworkCost` 的 ClusterCost 分數計算方式，他們會以 #1285 提到的方式，以相同的基準點下去做比較打分，比較能夠對比出二者不平衡的差異。

[COST] Revise `NetworkCost` calculation formula

---

fs/src/main/java/org/astraea/fs/hdfs/HdfsFileSystem.java
fs/src/test/java/org/astraea/fs/AbstractFileSystemTest.java

#1519 
將 hdfs 中的 listFolders 回傳值加上 parentPath 以符合其他版本對於此法的回傳格式，並增加相應的測試

[CONNECTOR] Fix listFolders in hdfs

---

common/src/main/java/org/astraea/common/cost/NetworkCost.java
common/src/main/java/org/astraea/common/cost/utils/ClusterInfoSensor.java
common/src/main/java/org/astraea/common/metrics/broker/ClusterMetrics.java
common/src/main/java/org/astraea/common/metrics/broker/HasGauge.java
common/src/main/java/org/astraea/common/metrics/broker/ServerMetrics.java
common/src/test/java/org/astraea/common/admin/ClusterBeanTest.java
common/src/test/java/org/astraea/common/cost/NetworkCostTest.java
common/src/test/java/org/astraea/common/cost/utils/ClusterInfoSensorTest.java
common/src/test/java/org/astraea/common/metrics/MetricFactory.java

Resolve #1508
這個 PR 提供一個 `ClusterInfoSensor`，這個 `MetricSensor` 提供從包含特定 Kafka JMX metrics 的 ClusterBean 重建一個 ClusterInfo 的能力。這個重建出來的 `ClusterInfo` 沒有包含完全的叢集狀態，目前 `ClusterInfoSensor` 可以從 ClusterBean 萃取下列的叢集負載狀態資訊：
* 每個 Broker 負責的 TopicPartition
* TopicPartition 的 leader/follower 身份
* TopicPartition 的 size
* Cluster 的簡略節點資訊 (node info, 只有 id)
`NetworkCost` 透過這個 `ClusterInfoSensor` 來取得 ClusterBean 背後對應的 Cluster 長相，這個 PR 替代其原先的複雜檢查機制。

Implementation of `ClusterInfoSensor`

---

app/src/main/java/org/astraea/app/web/BalancerHandler.java
common/src/main/java/org/astraea/common/cost/utils/ClusterInfoSensor.java
common/src/test/java/org/astraea/common/cost/NetworkCostTest.java
common/src/test/java/org/astraea/common/cost/utils/ClusterInfoSensorTest.java

修正 #1505 合併時產生的衝突。
使用者要自行過濾 Metric Collector 撈出來的 metric，把 local metric 過濾掉。
另外，修正在 `ClusterInfoTest` 使用 `registserLocalJmx()`，改成實際註冊 broker 的 jmx 。

Fix conflict of #1505

---

README.md
app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
common/src/main/java/org/astraea/common/balancer/executor/RebalancePlanExecutor.java
common/src/main/java/org/astraea/common/balancer/executor/StraightPlanExecutor.java
common/src/test/java/org/astraea/common/balancer/BalancerConsoleTest.java
common/src/test/java/org/astraea/common/balancer/BalancerTest.java
common/src/test/java/org/astraea/common/balancer/executor/StraightPlanExecutorTest.java
docs/performance_benchmark.md
docs/troubleshooting.md
docs/web_server/web_api_balancer_chinese.md

Context: https://github.com/skiptests/astraea/issues/1393#issuecomment-1382656937
Related Issue: https://github.com/skiptests/astraea/issues/1325
這個 PR 是 #1325 Data Directory 搬移時的應對機制
* 在進行 `PUT /balancer` 的時候可以指定 executor 的實作，還有 executor 的參數。其中 `enableDataDirectoryMigration` 參數指出要進行 data directory 之間的負載優化。預設是不進行。
* 現在 `GET /balancer` 會顯示 data dir 的資訊。
* 新增 troubleshooting 文件描述如何判斷遇到這個問題，還有修正這個問題。

[WEB] Enable Data Directory Migration

---

connector/src/main/java/org/astraea/connector/backup/Exporter.java
fs/build.gradle
fs/src/main/java/org/astraea/fs/hdfs/HdfsFileSystem.java
fs/src/test/java/org/astraea/fs/hdfs/HdfsFileSystemTest.java
gradle/dependencies.gradle

增加 hadoop 相關的 dependencies 使 hdfs 版的 backup 工具可以正常執行
在透過`start_worker.sh`建立 worker 時，會透過 shadowJar 建立 jar 檔案至 worker 中的 /opt/kafka/libs 當中
在使用 hdfs 的 connector 時，若直接建立會導致 `No FileSystem for scheme "hdfs"` 的錯誤出現，為此需要在建立 task 時加上以下參數才可以順利執行
`fs.hdfs.override.fs.hdfs.impl":"org.apache.hadoop.hdfs.DistributedFileSystem` 
為了避免發生此錯誤時 worker 中完全沒有任何訊息，因此將 `HdfsFileSystem` 中的 `packExeception` 替換為 `swallowException`

[CONNECTOR] Add dependencies for hdfs connector

---

common/src/main/java/org/astraea/common/cost/NetworkCost.java
common/src/test/java/org/astraea/common/cost/NetworkCostTest.java

Context: https://github.com/skiptests/astraea/pull/1476#issuecomment-1454429787
目前 `NetworkCost` 在大量 Partition （約 10000）的情境下會出現效能上的問題，這個 PR 對 `NetworkCost` 實作做一些優化。
* 快取 `ClusterBean` 計算出的 Partition 流量結果，以後這些昂貴的計算在整個 Balance 的流程中只會做一次。
* 修改衡量 `ClusterInfo` 的節點流量的方法，原本是從 raw replica stream 中做 `Collector.groupingBy` 聚合。現在透過 `ClusterInfo#replicas(int broker)` 已經聚合過的結果做流量加總，可以節省一些重複的聚合邏輯。
```
Total Run time: 35263 ms
Total ClusterCost Evaluation: 12
Average ClusterCost Processing: 2890ms
Average MoveCost Processing: 0 ms
Initial Cost: 0.20270230731415478
Final Cost: 0.20125311107585134
```
```
Total Run time: 30045 ms
Total ClusterCost Evaluation: 963
Average ClusterCost Processing: 9ms
Average MoveCost Processing: 0 ms
Initial Cost: 0.20265291955203096
Final Cost: 0.15089094792725546
``` …

[COST] Improve `NetworkCost` Performance

---

common/src/test/java/org/astraea/common/admin/AdminTest.java

如同 #1550 要多給一些時間讓 broker 向 controller 拉最新的資料

[TEST] stabilize AdminTest

---

common/src/main/java/org/astraea/common/metrics/MBeanClient.java

Context: #1553
`MBeanClient` 實作所基於的 `MBeanServerConnection` 為 Thread-Safe，這個 PR 允許 `MBeanClient#beans()` 底層的效能指標撈取同步化執行。

[COMMON] Parallelize the sampling of `MBeanClient#beans`

---

it/src/main/java/org/astraea/it/BrokerCluster.java

該參數來自於 https://github.com/skiptests/astraea/pull/388#discussion_r889496058
原本的用法應該是要避免自動平衡影響我們測試的期待，不過原本最會被影響的測試已經移除了，所以清掉該測試來看看還有沒有被影響的可能

[TEST] remove "auto.leader.rebalance.enable" from testing

---

docs/kafka_Q&A.md

#1556 更新Kafka QA的`單一partition的Consumer拉取的速度太慢`

update Kafka QA docs

---

common/src/main/java/org/astraea/common/admin/ClusterInfo.java
common/src/main/java/org/astraea/common/cost/RecordSizeCost.java
common/src/main/java/org/astraea/common/cost/ReplicaLeaderCost.java
common/src/main/java/org/astraea/common/cost/ReplicaLeaderSizeCost.java
common/src/main/java/org/astraea/common/cost/ReplicaNumberCost.java
common/src/test/java/org/astraea/common/cost/ReplicaLeaderSizeCostTest.java

不同成本考量中有許多程式碼非常類似，這隻PR將該些邏輯移動到`ClusterInfo`方便重複利用

[COST] move cluster-related cost to ClusterInfo

---

app/src/main/java/org/astraea/app/publisher/MetricPublisher.java
common/src/main/java/org/astraea/common/metrics/stats/Rate.java
common/src/test/java/org/astraea/common/metrics/stats/RateTest.java

使用 Metric Publisher 收集&發布 "有 60000 個 partition 的叢集" 的 mbean，但是 producer thread 還來不及發布 `beanQueue` 裡面的資料，`beanQueue` 就被塞滿了。
這裡改成讓 `fetcherThread` 使用 blocking call，把所有 fetch 到的 mbean 都塞進去，而不是拋出錯誤。

[Metric] Metric publisher failed when fetching many beans

---

common/src/main/java/org/astraea/common/cost/NeutralIntegratedCost.java
common/src/main/java/org/astraea/common/metrics/collector/MetricSensor.java
common/src/test/java/org/astraea/common/metrics/collector/MetricSensorTest.java

related https://github.com/skiptests/astraea/issues/1509#issue-1593324651
此 PR 想解決 SmoothWeightRoundRobinPartitioner 撈不到 localBean 的問題，這是因為在撈的過程發生 exception，導致同個節點的其他 cost 也跟著 exception 噴掉
SmoothWeightRoundRobinPartitioner 目前預設使用的 cost function 有四種，分別是
1. BrokerInputCost
2. BrokerOutputCost
3. CpuCost
4. MemoryCost
而如果 local 端沒有 BrokerInput、BrokerOutput 的 metrics，mBean client 在撈回來的時候就會噴 exception，導致 CpuCost 與 MemoryCost 也跟著噴掉
目前測試使用六台節點，因為都有開啟 Kafka server 所以都能正常拉取上述 metrics，而 Local 因為沒有 Broker 相關 metrics 所以跟著 exception 一起噴了

Provide exception handler construction for MetricSensors

---

common/src/main/java/org/astraea/common/consumer/Deserializer.java
common/src/main/java/org/astraea/common/producer/Serializer.java
common/src/test/java/org/astraea/common/serializer/ClusterInfoSerializerTest.java

related to  #1520
以下為序列化的形式
- ClusterInfo
```
+ 2 // [clusterId length]
+ n // [n bytes of clusterId]
+ 4 // [nums of NodeInfo]
┌ 4 + [NodeInfo] // [NodeInfo length + n bytes of NodeInfo]
+        ⋮
└ 4 + [NodeInfo]
+ 4 // [nums of Topic]
┌ 4 + [Topic] // [Topic length + n bytes of Topic]
+        ⋮
└ 4 + [Topic]
+ 4 // [nums of Replica]
┌ 4 + [Replica] // [Replica length + n bytes of Replica]
+        ⋮
└ 4 + [Replica]
```
- NodeInfo
```
+ 4 // [id]
+ 2 // [host length]
+ n // [n bytes of host]
+ 4 // [port]
```
- Topic
```
+ 2 // [topic length]
+ n // [n bytes of topic]
+ 4 // [nums of config]
+ n // [n bytes of config]
+ 1 // [internal]
+ 4 // [nums of topicPartitions]
+ 4 * 4 // [nums * partitions]
```
- Replica
```
+ 2 // [topic length]
+ n // [n bytes of topic]
+ 4 // [partition]
+ …
```

[CONNECTOR] Add ClusterInfo serializer and deserializer

---

app/src/main/java/org/astraea/app/web/RecordHandler.java
common/src/main/java/org/astraea/common/producer/Metadata.java
common/src/test/java/org/astraea/common/partitioner/PartitionerTest.java
common/src/test/java/org/astraea/common/producer/ProducerTest.java
gui/src/main/java/org/astraea/gui/tab/ClientNode.java

related to #1586
`Metadata`是一個常用的資料格式，改成 interface 並搭配 proxy 模式來避免預先建立太多物件

[PRODUCER] change Metadata to interface

---

common/src/main/java/org/astraea/common/metrics/MBeanClient.java
common/src/main/java/org/astraea/common/metrics/collector/LocalSenderReceiver.java
common/src/main/java/org/astraea/common/metrics/collector/MetricsFetcher.java
common/src/main/java/org/astraea/common/metrics/collector/MetricsStore.java
common/src/test/java/org/astraea/common/metrics/MBeanClientTest.java
common/src/test/java/org/astraea/common/metrics/collector/LocalMetricsTest.java
common/src/test/java/org/astraea/common/metrics/collector/MetricsFetcherTest.java
common/src/test/java/org/astraea/common/metrics/collector/MetricsStoreTest.java

related to #1594
這隻PR新增兩個元件：
1. `MetricsFetcher`：用多執行緒資料從眾多`MBeanClient`取出，並且透過`Sender`送到某個地方。`Sender`可以用 producer實作讓資料傳到遠端 topic
2. `MetricsStore`：將資料從`Receiver`中取出，並且經過`MetricsSensor`篩選產生出要保存在本地的metrics。`Receiver`可以用consumer實作來從遠端 topic 拉取資料
這次的目的是將 local/remote(topic) 兩種 metrics 體系統一，使用者可以有三種用法：
1. local mode：使用者可以透過簡單的方式快速建構一個`MetricsStore` with embedded `MetricsFetcher`，兩者的資料交換都透過記憶體交換，類似於原本的 local MetricsCollector
2. publisher：一個獨立的應用程式負責將資料從遠端server收集完後，並且丟到 topic，這時可以只用`MetricsFetcher`，必且搭配 producer版本的`Sender`
3. remote (topic) mode，正式環境上 producer/assignor/balancer 都可以用，只需要建構`MetricsStore`搭配 consumer版本的`receiver`

[METRICS] a new infra for metrics collector

---

app/src/main/java/org/astraea/app/performance/ConsumerThread.java

Consumer 目前的命名是隨機取的，這個 PR 把它改成固定的值。
* Consumer 使用固定的名稱，如此一來即使 Performance Tool 重開， Java Mission Control 內先前建立的效能圖表可以繼續使用，不會因為 consumer 名稱變動而找不到對應的 attribute。
* 避免 Prometheus 內儲存的 time-series 種類過多 （每個隨機值都被視為一個不同的 series，圖表內的顏色和 label 會變很繽紛...）

[CONSUMER] Make consumer naming static/fixed

---

app/src/main/java/org/astraea/app/performance/DataGenerator.java
app/src/main/java/org/astraea/app/performance/Performance.java
app/src/test/java/org/astraea/app/performance/PerformanceTest.java

Context: https://github.com/skiptests/astraea/issues/1567#issuecomment-1483719688
這個 PR 使 Performance Tool 能夠支援 0 個 Producer 的使用情境。
先前的討論發現 Producer/Consumer 執行在同一臺會有傳輸不順的情況，對此這個 PR 的修正能夠允許 Performance 的 Producer/Consumer 跑在不同的設備上，以繞過這個問題。
當使用 0 個 Producer 可能會發生的爭議是：Performance Tool 不知道什麼時候應該停止，因為沒有一個具體的 Producer 會給他輸入資料，這個部分是使用既有的參數 `read.idle` 來處理，如果經過 `read.idle` 實驗都沒有資料流進來，則視為 consumer 的工作完成。

[PERF] Enable the use of zero producer

---

app/src/main/java/org/astraea/app/performance/Performance.java
app/src/main/java/org/astraea/app/performance/ProducerThread.java

審查#1602時注意到，queue的總量在邏輯上會等同於producers數量，所以可以選一個當輸入參數就好

[PERF] remove duplicate argument from ProducerThread#create

---

app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java

fix #1613 
在我本地端是多給一點時間就會通過，因為現在擷取的metrics較多，會有一段時間找不到足夠的metrics來啟動

[TEST] fix BalancerHandlerTest#testRebalanceDetectOngoing

---

app/src/main/java/org/astraea/balancer/bench/BalancerBenchmark.java
app/src/main/java/org/astraea/balancer/bench/CostProfilingImpl.java

#1574 刪除了 `CostProfilingResult#solution()` 欄位，這個 PR 把它放回來。

[BALANCER] Put generated plan onto `CostProfilingResult` result

---

common/src/test/java/org/astraea/common/cost/ReplicaNumberCostTest.java

Error: https://github.com/garyparrot/astraea/actions/runs/4618986593/jobs/8167122525#step:5:3529
`ReplicaNumberCostTest#testClusterCost` 這隻測試有 1/99 的機會出錯
https://github.com/skiptests/astraea/blob/b337e5cfc4ee3624e568750c3a5d8ee61c231c61/common/src/test/java/org/astraea/common/cost/ReplicaNumberCostTest.java#L69-L75
這個情境是所有 Partition 都擠在同一個節點的情況，而 Partition 數量可能是 1 ~ 99 個，當 Partition 數正好出現 1 的時候，整個情境是 `(1, 0, 0, 0, 0, 0)`，這個符合 completely balance in terms of integer 的情況
https://github.com/skiptests/astraea/blob/573f7f7e64f0b8a8c29a24e0b364fafbf161e721/common/src/main/java/org/astraea/common/cost/ReplicaNumberCost.java#L78-L84
因為整個情境基本上已經沒辦法被調整得更平衡，被視為是 0.0 的正好狀態，所以回傳 `0` 而非測試原先預期的 `1`。

[TEST] Fix flaky `ReplicaNumberCostTest#testClusterCost`

---

common/src/main/java/org/astraea/common/partitioner/StrictCostPartitioner.java
common/src/test/java/org/astraea/common/partitioner/StrictCostPartitionerTest.java

resolve #1111 
cost function 若遇到數據不夠，可能會丟出 `NoSufficientException`，我認為這個錯誤應該要在 StrictCostPartitioner 內處理。
對此錯誤的處理方式，這裡選擇忽略，原因是 cost 在 partitioner 內是一個分配方式的參考，不應為了 "取得 cost" 而等待。
而忽略錯誤對 StrictCostPartitioner 的影響在於 "拿不到最新的數據，只能用舊有數據繼續判斷"。

[PARTITIONER] Catch exception in `StrictCostPartitioner`

---

common/build.gradle
common/src/main/java/org/astraea/common/consumer/Deserializer.java
common/src/main/java/org/astraea/common/producer/Serializer.java
common/src/main/proto/org/astraea/common/BeanObject.proto
common/src/main/proto/org/astraea/common/generated/BeanObject.proto
common/src/test/java/org/astraea/common/EnumInfoTest.java
common/src/test/java/org/astraea/common/serializer/BeanObjectSerializerTest.java

related to #1581 
這隻 PR 引入一個函式庫--protobuf，並且嘗試於 `BeanObject` 上。
這隻 PR 改動了 `EnumInfoTest` ，針對例外類別不做檢查。
因為 protobuf 如果在定義的時候使用到 `oneof` type 時，編譯的時候就會編出 enum 的類別，而 protobuf 編譯出的類別，我們不應該修改，也不應該是我們檢查 (EnumInfoTest) 的對象，所以修改 `EnumInfoTest`。

[SERIALIZATION] Serialize `BeanObject` by protoBuf

---

common/src/main/java/org/astraea/common/cost/EstimationMethod.java
common/src/main/java/org/astraea/common/cost/NetworkCost.java
common/src/main/java/org/astraea/common/cost/NetworkEgressCost.java
common/src/main/java/org/astraea/common/cost/NetworkIngressCost.java
common/src/main/java/org/astraea/common/metrics/broker/HasRate.java
common/src/test/java/org/astraea/common/cost/NetworkCostTest.java

Context: https://github.com/skiptests/astraea/issues/1641#issuecomment-1500000107
因為 FifteenMinuteRate 的等待時間有點長，要在短時間內使用他當做判斷依據有點困難，如果在 Rate 還沒收斂時就拿來當判斷依據，會有誤差出現，詳情參見 #1641 的測試。
這個 PR 允許使用者調整 network cost 要使用的衡量方法，目前提供 One/Five/Fifteen Minute Rate，預設會使用 One Minute Rate，他收斂的速度會比較快，但相對來說也會比較難反映稍微長遠的變化。
另外，雖然 FifteenMinuteRate 可以反映更長的流量行為，但根據 #1641 的測試最長似乎也就 1 小時左右，如果真的要考量長遠的流量行為，可能 NetworkCost 不適合。

[COST] Enable to tune the estimation method of `NetworkCost`

---

common/src/main/java/org/astraea/common/metrics/broker/HasCount.java
common/src/main/java/org/astraea/common/metrics/broker/HasRate.java
common/src/test/java/org/astraea/common/cost/NetworkIngressCostTest.java

Context: https://github.com/skiptests/astraea/pull/1643#discussion_r1161066272
把 `HasCount` 和 `HasRate` 內的部分 attribute 在讀取時會自動在 attribute 不存在時帶入 0 當預設值，這個行為可能會造成一些誤會，比如該 BeanObject 沒有這個 attribute 卻依然回傳值。
這個 PR 移除這個行為，現在當讀取欄位的 attribute 不存在時，會觸發 `NullPointerException` 而非回傳預設值 0

[METRICS] Remove default value of attribute function for `HasCount` & `HasRate`

---

common/src/main/java/org/astraea/common/assignor/Assignor.java
common/src/main/java/org/astraea/common/assignor/GroupSubscriptionInfo.java
common/src/main/java/org/astraea/common/assignor/RandomAssignor.java
common/src/main/java/org/astraea/common/assignor/SubscriptionInfo.java
common/src/test/java/org/astraea/common/assignor/AssignorTest.java

related https://github.com/skiptests/astraea/pull/1524#discussion_r1167741379
為了遵照專案引用物件的風格，此 PR 重新命名了 `Assignor` 相關的 class：
* Subscription 修改成 Subscription**Info**
* GroupSubscription 修改成 GroupSubscription**Info**
修改前的風格：
```java
Map<String, org.astraea.common.assignor.Subscription> subscriptions
```
修改後的風格：
```java
Map<String, SubscriptionInfo> subscriptions
```

Rename the classes that related assignor

---

common/src/main/java/org/astraea/common/cost/utils/ClusterInfoSensor.java
common/src/main/java/org/astraea/common/metrics/JndiClient.java
common/src/main/java/org/astraea/common/metrics/MBeanClient.java
common/src/main/java/org/astraea/common/metrics/collector/BeanObjectClient.java
common/src/main/java/org/astraea/common/metrics/collector/MetricSensor.java
common/src/main/java/org/astraea/common/metrics/collector/MetricStore.java
common/src/test/java/org/astraea/common/cost/ClusterCostTest.java
common/src/test/java/org/astraea/common/cost/MoveCostTest.java
common/src/test/java/org/astraea/common/cost/NodeLatencyCostTest.java
common/src/test/java/org/astraea/common/cost/NodeThroughputCostTest.java
common/src/test/java/org/astraea/common/metrics/MetricsTestUtils.java
common/src/test/java/org/astraea/common/metrics/collector/MetricSensorTest.java

新增一個介面`BeanObjectClient`來將`MetricSensor`使用的介面與通用的`MBeanClient`做出區隔，這樣之後要增加更多方法都不用擔心會破壞通用的`MBeanClient`

[COMMON] add BeanObjectClient for MetricSensor

---

common/src/main/java/org/astraea/common/metrics/collector/MetricStore.java
common/src/test/java/org/astraea/common/metrics/collector/MetricStoreTest.java

Related to #1660 
這隻 PR 為 `MetricStore` 介面新增了等待的方法。
在預設的做法中，會持續檢查 cluster bean 是否符合使用者的需求，直到時間限制到達為止。
在實作中，為了不做多餘的檢查，新增了一個 waiting list 。每當有新的等待出現時，便會註冊一個 checker 在 waiting list 中，metric store 內接收到新的 beans 後，就會去 waiting list 裡面檢查每一個 checker ，有符合，就可以把還在等待的 thread 喚醒。任何進來等待的 thread 都會在離開前取消註冊。

[METRIC] Add wait in MetricStore interface

---

app/src/test/java/org/astraea/app/web/RecordHandlerTest.java
common/src/main/java/org/astraea/common/Header.java
common/src/main/java/org/astraea/common/backup/RecordReaderBuilder.java
common/src/test/java/org/astraea/common/partitioner/PartitionerTest.java
common/src/test/java/org/astraea/common/producer/ProducerTest.java
connector/src/main/java/org/astraea/connector/SinkTask.java
connector/src/test/java/org/astraea/connector/SourceDataTest.java

[COMMON] rewrite Header by java 17 record

---

common/src/test/java/org/astraea/common/producer/RecordGeneratorTest.java

似乎更新到 JDK 17後執行速度變快了，導致原本設定每秒1G的速度會被灌爆，導致後面都被 throttled 掉，所以移除不必要的限制

[TEST] fix RecordGeneratorTest#testRandomSeed

---

app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java

修正`BalancerHandlerTest#testMoveCost` 的flaky test，主要問題為SERVICE並行執行，moveCost在計算leader數量時會受影響，因此將其測試改為獨立使用一個SERVICE

[TEST] Fix flaky BalancerHandlerTest#testMoveCost

---

common/src/main/java/org/astraea/common/producer/Record.java
connector/src/main/java/org/astraea/connector/SourceRecord.java
connector/src/main/java/org/astraea/connector/SourceTask.java
connector/src/main/java/org/astraea/connector/backup/Importer.java
connector/src/main/java/org/astraea/connector/perf/PerfSource.java
connector/src/test/java/org/astraea/connector/ConnectorTest.java
connector/src/test/java/org/astraea/connector/MetadataStorageTest.java
connector/src/test/java/org/astraea/connector/SourceDataTest.java

[PRODUCER] rewrite producer.Record by java 17 record

---

common/src/main/java/org/astraea/common/metrics/BeanQuery.java

[METRICS] rewrite BeanQuery by java 17 record

---

common/src/main/java/org/astraea/common/metrics/BeanObject.java

[METRICS] rewrite BeanObject by java 17 record

---

common/src/main/java/org/astraea/common/assignor/Assignor.java
common/src/test/java/org/astraea/common/assignor/AssignorTest.java

在執行 https://github.com/skiptests/astraea/pull/1705#issue-1699051646 時，發現有未被使用的方法 `checkUnregister`
因為使用 `MetricStore`、`分配完釋放資源` 後，就不需要去檢查未註冊的節點了。現在 assignor 分配前會用 admin 取得、註冊當下叢集所有的節點，所以 `checkUnregister` 已經用不到了，故移除

[ASSIGNOR] Remove redundant code

---

common/src/test/java/org/astraea/common/metrics/collector/MetricStoreTest.java

`MetricStore` 的清理 thread 是每 n 秒檢查一次，若 bean 已存在超過 n 秒，就會移除。但是這並不代表 n 秒前收集到的 bean 會馬上被移除。因為我們檢查的時候，可能已經離上次移除有段時間了。但我們可以確定的是 2*n 秒前收集的 bean 一定會被移除，所以這裡把等待時間改成 5*2 = 10 秒。

[METRICS] Fix flacky testBeanExpiration

---

common/src/main/java/org/astraea/common/cost/ReplicaLeaderSizeCost.java

這隻 PR 是 https://github.com/skiptests/astraea/pull/1654#issuecomment-1514855303 提到的問題，不過 #1654 可能還有一些問題需要處理，還需要一點時間。
這裡先另外開一隻 PR 處理，避免有人踩到同樣的坑。
這隻 PR 化簡 cost function -- `ReplicaLeaderSizeCost` 的計算，避免重複查找 replica leader。

[COST] Reduce calculation on `ReplicaLeaderSize` partition cost

---

app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
common/src/main/java/org/astraea/common/balancer/BalancerProblemFormat.java
common/src/test/java/org/astraea/common/balancer/BalancerProblemFormatTest.java

Related Issue: #1693
後面 BalancerBench 會需要進到 App 裡面，我們需要有一個手法讓使用者從程式輸入描述整個 Balancer 的優化問題。目前我打算重複利用 [POST /balancer](https://github.com/skiptests/astraea/blob/main/docs/web_server/web_api_balancer_chinese.md#%E6%8E%92%E7%A8%8B%E6%90%9C%E5%B0%8B%E6%96%B0%E7%9A%84%E8%B2%A0%E8%BC%89%E5%84%AA%E5%8C%96%E8%A8%88%E5%8A%83) Web API 的輸入 JSON Payload 格式。這個 PR 把 `BalancerHandler` 內描述 Balancer 問題的那個 Data Class 移動到 `common` 裡面，方便後續 Web API 和 App 重複利用他，後面 BalancerBench 的 App 也會和使用者要一個 JSON，讀取 JSON 的內容來得知優化問題的細部資訊(AlgorithmConfig & Balancer Implementation)。

[BALANCER] Implementation of `BalancerProblemFormat`

---

common/src/main/java/org/astraea/common/admin/TopicPartitionReplica.java

[COMMON] rewrite admin.TopicPartitionReplica by java 17 record

---

common/src/main/java/org/astraea/common/ByteUtils.java
common/src/main/java/org/astraea/common/admin/Broker.java
common/src/main/java/org/astraea/common/admin/Config.java
common/src/main/java/org/astraea/common/admin/Topic.java

[COMMON] rewrite admin.Config by java 17 record

---

common/src/main/java/org/astraea/common/admin/Quota.java

[COMMON] rewrite admin.Quota by java 17 record

---

app/src/main/java/org/astraea/app/web/WebService.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
common/src/main/java/org/astraea/common/Utils.java
common/src/main/java/org/astraea/common/assignor/Assignor.java
common/src/main/java/org/astraea/common/metrics/collector/MetricStore.java
common/src/main/java/org/astraea/common/partitioner/SmoothWeightRoundRobinPartitioner.java
common/src/main/java/org/astraea/common/partitioner/StrictCostPartitioner.java
common/src/test/java/org/astraea/common/UtilsTest.java
common/src/test/java/org/astraea/common/metrics/collector/LocalMetricsTest.java
common/src/test/java/org/astraea/common/metrics/collector/MetricStoreTest.java

related to #1718 
這隻 PR 是 #1718 提出的實做，重構 `MetricStore::Builder` 的 `receiver` 方法，原來的方法是指定 `MetricStore` 要使用哪一個 `Receiver`，這隻 PR 改成新增一個 `Receiver` 給 `MetricStore` 管理，因為 #1718 需要不同的 metric 來源端，所以做此重構。

[METRICS] Add receiver to metricStore

---

common/src/main/java/org/astraea/common/metrics/broker/LogMetrics.java
common/src/test/java/org/astraea/common/cost/LogMetricsGaugeBuilder.java
common/src/test/java/org/astraea/common/cost/NetworkCostTest.java
common/src/test/java/org/astraea/common/cost/utils/ClusterInfoSensorTest.java

[METRICS] rewrite LogMetrics by java 17 record

---

common/src/main/java/org/astraea/common/metrics/broker/ServerMetrics.java
common/src/test/java/org/astraea/common/cost/NetworkCostTest.java
common/src/test/java/org/astraea/common/cost/ServerMetricsMeterBuilder.java

[METRICS] rewrite ServerMetrics by java 17 record

---

common/src/main/java/org/astraea/common/producer/Metadata.java

[PRODUCER] rewrite proudcer.Metadata by java 17 record

---

connector/src/main/java/org/astraea/connector/SinkConnector.java
connector/src/main/java/org/astraea/connector/SinkTask.java
connector/src/main/java/org/astraea/connector/backup/Exporter.java
connector/src/main/java/org/astraea/connector/perf/PerfSink.java

[CONNECTOR] rewrite sink connector by java 17 toList

---

app/src/main/java/org/astraea/app/backup/Backup.java
app/src/main/java/org/astraea/app/performance/ConsumerThread.java
app/src/main/java/org/astraea/app/performance/DataGenerator.java
app/src/main/java/org/astraea/app/performance/MonkeyThread.java
app/src/main/java/org/astraea/app/performance/Performance.java
app/src/main/java/org/astraea/app/performance/ProducerThread.java
app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/main/java/org/astraea/app/web/BeanHandler.java
app/src/main/java/org/astraea/app/web/BrokerHandler.java
app/src/main/java/org/astraea/app/web/Channel.java
app/src/main/java/org/astraea/app/web/GroupHandler.java
app/src/main/java/org/astraea/app/web/ProducerHandler.java
app/src/main/java/org/astraea/app/web/QuotaHandler.java
app/src/main/java/org/astraea/app/web/ReassignmentHandler.java
app/src/main/java/org/astraea/app/web/TopicHandler.java
app/src/main/java/org/astraea/app/web/TransactionHandler.java

related to https://github.com/skiptests/astraea/issues/1686

[APP] rewrite files under app/src/main by java 17 toList

---

connector/src/main/java/org/astraea/connector/Definition.java
connector/src/main/java/org/astraea/connector/backup/Exporter.java
connector/src/main/java/org/astraea/connector/backup/Importer.java
connector/src/main/java/org/astraea/connector/perf/PerfSink.java
connector/src/main/java/org/astraea/connector/perf/PerfSource.java
connector/src/test/java/org/astraea/connector/DefinitionTest.java

[CONNECTOR] rewrite connector.Definition by java 17 record

---

common/src/main/java/org/astraea/common/cost/BrokerDiskSpaceCost.java

此PR修正在使用`BalancerBenchmark `測試`BrokerDiskSpaceCost`的效能問題
修正前在90秒內只能計算100~200個`CostFunction`，修正後在90秒內可以計算大約7500個`CostFunction`

[COST] fix BrokerDiskSpaceCost

---

app/src/main/java/org/astraea/app/argument/PositiveIntegerListField.java
app/src/main/java/org/astraea/app/argument/PositiveShortListField.java
app/src/main/java/org/astraea/app/argument/StringListField.java
app/src/main/java/org/astraea/app/web/BalancerHandler.java
app/src/main/java/org/astraea/app/web/ReassignmentHandler.java
app/src/main/java/org/astraea/app/web/SkewedPartitionScenario.java
app/src/main/java/org/astraea/app/web/TopicHandler.java
app/src/test/java/org/astraea/app/EnumInfoTest.java
app/src/test/java/org/astraea/app/TestUtils.java
app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
app/src/test/java/org/astraea/app/web/GroupHandlerTest.java
app/src/test/java/org/astraea/app/web/ProducerHandlerTest.java
app/src/test/java/org/astraea/app/web/RecordHandlerTest.java
app/src/test/java/org/astraea/app/web/RequestTest.java
app/src/test/java/org/astraea/app/web/ThrottleHandlerTest.java
app/src/test/java/org/astraea/app/web/TopicHandlerForProbabilityTest.java
app/src/test/java/org/astraea/app/web/TopicHandlerTest.java

related to https://github.com/skiptests/astraea/issues/1686
included `app/src/test` and some missed file in `app/src/main`

[APP] Rewrite files under app by java 17 toList

---

common/src/main/java/org/astraea/common/balancer/AlgorithmConfig.java

[BALANCER] rewrite AlgorithmConfig by java 17 record

---

common/src/main/java/org/astraea/common/connector/ConnectorReq.java
common/src/main/java/org/astraea/common/connector/ConnectorStatus.java
common/src/main/java/org/astraea/common/connector/PluginInfo.java
common/src/main/java/org/astraea/common/connector/TaskStatus.java
common/src/main/java/org/astraea/common/connector/WorkerStatus.java

related to https://github.com/skiptests/astraea/issues/1686

[COMMON] Rewrite file under connector by java 17 record

---

common/src/main/java/org/astraea/common/connector/Builder.java
common/src/test/java/org/astraea/common/connector/ConnectorClientBuilderTest.java
common/src/test/java/org/astraea/common/connector/ConnectorClientTest.java

from https://docs.oracle.com/javase/8/docs/api/java/net/URL.html#hashCode--
`URL#hashCode`會嘗試執行 DNS lookup，因此是一個 blocking call，目前在專案內並沒有比較的需求，因此將`Set`改成`List`

[COMMON] avoid calling URL#hashCode

---

app/src/test/java/org/astraea/app/backup/BackupTest.java

fix #1784
在 SERVICE 中獲取到的 controller id 是隨機的 
(`case KRaftCachedControllerId(_) => metadataCache.getRandomAliveBrokerId`)，
所以會導致replica 在重新建構後所在的同一個Broker.isController 不一致
目前改成只透過 replica 及 leader 的 topic partition 對應的 `broker id` 判斷分佈是否一致

[TEST] Fix flaky BackupTest#testRestoreDistribution()

---

app/src/main/java/org/astraea/app/web/BrokerHandler.java
app/src/main/java/org/astraea/app/web/ReassignmentHandler.java
common/src/main/java/org/astraea/common/ByteUtils.java
common/src/main/java/org/astraea/common/admin/Admin.java
common/src/main/java/org/astraea/common/admin/AdminImpl.java
common/src/main/java/org/astraea/common/admin/Broker.java
common/src/main/java/org/astraea/common/admin/ClusterInfo.java
common/src/main/java/org/astraea/common/admin/ClusterInfoBuilder.java
common/src/main/java/org/astraea/common/admin/TopicPartitionPath.java
common/src/main/proto/org/astraea/common/generated/admin/Broker.proto
common/src/test/java/org/astraea/common/admin/AdminTest.java
common/src/test/java/org/astraea/common/admin/AdminWithOfflineBrokerTest.java
common/src/test/java/org/astraea/common/admin/ClusterInfoBuilderTest.java
common/src/test/java/org/astraea/common/admin/ClusterInfoTest.java
common/src/test/java/org/astraea/common/balancer/FakeClusterInfo.java
common/src/test/java/org/astraea/common/cost/BrokerDiskSpaceCostTest.java
common/src/test/java/org/astraea/common/cost/CostUtilsTest.java
gui/src/main/java/org/astraea/gui/tab/BrokerNode.java
gui/src/main/java/org/astraea/gui/tab/topic/TopicNode.java

Broker 裡面有多個資料結構描述`TopicPartition`，這會讓大型叢集在操作時要創建好幾個大型集合才能形成`Broker`這個結構，此外 orphan 是一個很抽象的概念，實際上不常發生所以也移除

[COMMON] refine Broker structure to avoid duplicate large collection

---

common/src/test/java/org/astraea/common/admin/AdminTest.java

[COMMON] fix warnings of AdminTest

---

common/src/main/java/org/astraea/common/metrics/collector/MetricStore.java
common/src/test/java/org/astraea/common/metrics/collector/FixedMetricsTest.java

Resolve #1710 
這個 PR 實作一個新的 Metric Store receiver `Receiver#fixed(Map<Integer, Collection<BeanObject>)`
這個 Receiver 只會在第一次呼叫 `receive` 時回傳建立時提供的 Beans，然後就不再回傳任何新的 Beans。後面這個會和 #1769 的序列化功能搭配，從檔案系統將 BeanObjects 還原回 `Map<Integer, Collection<BeanObject>`，然後把這個東西當做輸入給 `Receiver` 的輸出使用，而後從 `MetricStore#clusterBean` 取得最後的 `ClusterBean` 物件。
這個大致上是後面 benchmark 的 `ClusterBean` 還原方法。

[METRICS] Implementation of fixed receiver

---

common/src/main/java/org/astraea/common/metrics/collector/MetricFetcher.java
common/src/main/java/org/astraea/common/metrics/collector/MetricStore.java
common/src/main/java/org/astraea/common/partitioner/StrictCostPartitioner.java

這隻 PR 在 `MetricStore` 和 `MetricFetcher` 紀錄 bean 收集的速率。
在降低 metric 收集的資源消耗外，也應該要考慮收集 metric 的數量 (速率)。
在 metric 量多時， fetch 的時間可能遠大於 `fetchBeanDelay`，這時候 metric 收集速度將會有所不同。
在我的預期中，topic collector 應該要有較快的收集速度 + 較低資源消耗。目前較低的資源消耗已經有方法證實，我認為再來需要看看 metric 收集的速率，證實 "較低資源消耗 不是因為 收集較少資料"。

[METRICS] Add mbean to metric store and metric fetcher

---

docker/start_broker.sh
docker/start_controller.sh

目前專案的 kafka container 的啟動指令是 `sh -c "./bin/kafka-storage.sh format -t $CLUSTER_ID -c /tmp/controller.properties && ./bin/kafka-server-start.sh /tmp/controller.properties"`，這個啟動的指令會在 container restart 時再執行一次，而從第二次執行開始前面的 `kafka-storage.sh` 會因為已經格式化過而噴錯，進而導致後面的 `kafka-server-start.sh` 沒辦法執行，因此專案腳本的 container 沒辦法透過 `docker stop`, `docker start` 重開。
這個 PR 給格式化的腳本使用 `--ignore-formatted`，這個選項會忽略已經格式化過的 log dir，讓後面的 `kafka-server-start.sh` 可以順利執行。

[SCRIPT] Enable to restart kafka container

---

common/src/main/java/org/astraea/common/assignor/Assignor.java
common/src/main/java/org/astraea/common/consumer/ConsumerConfigs.java

與 #1765 類似，將 topic collector 整合到 `Assignor` 中，讓使用者可以指定要使用哪一種 metric 收集方法。
這隻 PR 新增一個 consumer config -- "metric.store"，使用者可以選擇 "local" 或 "topic" 來使用 local collector 或 topic collector。

[METRICS] Configurable metric collector for Assignor

---

connector/src/main/java/org/astraea/connector/SinkConnector.java
connector/src/main/java/org/astraea/connector/SinkContext.java
connector/src/main/java/org/astraea/connector/SinkTaskContext.java
connector/src/main/java/org/astraea/connector/SourceConnector.java
connector/src/main/java/org/astraea/connector/SourceContext.java
connector/src/main/java/org/astraea/connector/SourceTask.java
connector/src/main/java/org/astraea/connector/SourceTaskContext.java
connector/src/main/java/org/astraea/connector/backup/Exporter.java
connector/src/main/java/org/astraea/connector/backup/Importer.java
connector/src/main/java/org/astraea/connector/perf/PerfSink.java
connector/src/main/java/org/astraea/connector/perf/PerfSource.java
connector/src/test/java/org/astraea/connector/ConnectorTest.java
connector/src/test/java/org/astraea/connector/MetadataStorageTest.java
connector/src/test/java/org/astraea/connector/SourceDataTest.java
connector/src/test/java/org/astraea/connector/backup/ImporterTest.java
connector/src/test/java/org/astraea/connector/perf/PerfSourceTest.java

一次把所有 context 放進去給 source/sink，這樣之後就不需要再調整介面了

[CONNECTOR] add contexts for source/sink

---

fs/src/main/java/org/astraea/fs/local/LocalFileSystem.java

fix #1801
此 Pr 透過 try-with-resources 的方式，確保 `Files.list()` 能在 `Stream` 完成後自動關閉。
有再透過 Importer 測試，不會有`Too many open files`錯誤。

[FS] Using try-with-resources with Files.list() in local listFolders

---

connector/src/main/java/org/astraea/connector/backup/Exporter.java

修正關閉 task 時沒有將 field fs 關閉的問題，這會導致即便刪除 connector 還是會佔用 filesystem 的連線數。

[EXPORTER] Close fs in Task.close()

---

common/src/main/java/org/astraea/common/backup/RecordWriterBuilder.java
connector/src/test/java/org/astraea/connector/backup/ExporterTest.java

RecordWriter 中的 size 在 append 中寫入到檔案後並沒有將寫入的內容大小更新到 size 之中，導致後續在判斷是否需要切檔案時始終判斷寫入檔案並沒有超過設定值而持續寫入同一檔案。
因此在 append 中將 `recordBuilder` 的 serializedSize 計算到 size 之中以避免上述狀況，並新增相關的測試來確認是否有這問題的發生。

[EXPORTER] Fix the size in RecordWriter never be updated

---

common/src/main/java/org/astraea/common/backup/RecordWriterBuilder.java
connector/src/main/java/org/astraea/connector/backup/Exporter.java
connector/src/test/java/org/astraea/connector/backup/ExporterTest.java

#1822 
目前增加參數 `compression.type` 使的 exporter 支援 gzip 壓縮方法，未來支援其他的壓縮演算法可以透過這個參數設定。
目前在建立 gzip 壓縮檔按時，有發現文件內容開頭會是 `1f 8b` ，因此沒有在針對寫出的檔案附加上 gzip 結尾。

[EXPORTER] Add support for gzip compression

---

common/src/main/java/org/astraea/common/metrics/collector/MetricStore.java
common/src/test/java/org/astraea/common/partitioner/StrictCostPartitionerTest.java

原本作法在 `reciever` 中沒有 `BeanObject` 時，線程會等到有資料或者 3 秒鐘時限到。這個等待會影響到其他 `receiver` 取得 `BeanObject`。
這隻 PR 改成不等待，`receiver` 當下沒有資料時會馬上回傳，換使用下一個 `receiver` 嘗試取得 `BeanObejct`。
這隻 PR 會導致一個測試發生錯誤 (`MetricSensor` 數量)，這項測試原本就應該要錯誤，但因為先前作法會讓 `metricStore` 較晚更新 `MetricSensor` (為了等待 metric)，所以剛好 `MetricSensor` 數量符合預期 (0)。但這隻 PR 不等待 metric 取得，所以馬上就會更新 `MetricSensor` 導致測試時 `MetricSensor` 數量為 1 ，內容為 `MetricSensor.EMPTY`。

[METRICS] Not block on BeanObject receiving

---

common/src/main/java/org/astraea/common/backup/RecordReaderBuilder.java
common/src/main/java/org/astraea/common/backup/RecordWriter.java
common/src/main/java/org/astraea/common/backup/RecordWriterBuilder.java
connector/src/main/java/org/astraea/connector/SinkTaskContext.java
connector/src/main/java/org/astraea/connector/backup/Exporter.java
connector/src/test/java/org/astraea/connector/backup/ExporterTest.java
fs/src/main/java/org/astraea/fs/ftp/FtpFileSystem.java

#1830 
更新到了版本1，現在備份的文件尾部增加了檔案的 metadata，有以下資訊
1. connector name -> 255 Bytes
2. ~topic name -> 255 Bytes~
3. ~partition number -> 4 Bytes~
4. ~1st record offset -> 8 Bytes~
5. ~1st record timestamp -> 8 Bytes~
6. record count -> 4 Bytes
7. roll.duration in mills -> 8 Bytes
8. compression.type -> 10Bytes
以上總共 ~552Bytes~ 277 Bytes，後續 importer 要先讀取 metadata 可以固定跳到尾部前的 metadata 位置先讀取。
目前針對 importer 中的測試部分，因為還沒有針對 metadata 的部分做處理，因此在判斷有無下一筆資料時遇到 metadata 的 protocol buffer 錯誤會先不理會，等到後續更新 v1 版本的 importer 時可以把這段拔掉。
現在因為要針對些 connector 與 1st record 等資料作紀錄，導致 v1 版的 RecordWriter 所需參數增加到三個。
分別為
1. configuration: 為了取得 connector name, roll.duration 或 compression.type 等創建 connector 時的資訊
2. record: 跟 1st record 相關資訊
3. outputStream
本次取消在 RecordWriterBuilder 中就依照 compression.type 就創建壓縮的 outputStream 如 …

[EXPORTER] Add metadata in record writer

---

common/src/main/java/org/astraea/common/metrics/collector/MetricStore.java

實驗時發現，MetricStore 檢查 waiting list 會影響指標拉取速率，這隻 PR 改成獨立使用一條執行緒來檢查。
在使用 Cost Aware Assignor 時，該程式會等待 MetricStore 有"完整"效能指標時才會做計算，其判斷"完整"的方式是實際代入 cost-function 計算，會在 MetricStore 有更新指標的時候檢查。但這些計算不應該由佔用 "MetricStore 的拉取執行緒" ，MetricStore 應該繼續拉取最新指標。
所以這裡的作法是建立一個新的執行緒檢查，且同時只會有一個執行緒在執行檢查（透過 `isChecking` 確保一次只會有一個執行緒）。
另外，先前的作法是看本次迴圈指標有無更新，再來執行檢查，但使用多執行緒執行的話，有可能會在前一個迴圈（執行檢查後）更新，為避免漏檢查，所以使用另一個參數 `needChecking` 確保每次更新都有檢查到。

[METRICS] New thread for waiting list checking

---

docker/docker_build_common.sh

如果有多張網卡會顯示下列訊息,我們只需要保留一個address就好了
```
node.id=11539
broker address: 192.168.31.57 192.168.31.94 172.17.0.1 172.18.0.1 fe80::da5e:d3ff:fe2a:2a9b fe80::6a54:5aff:fecb:4729 fe80::42:ffff:fe04:9b86:10883
jmx address: 192.168.31.57 192.168.31.94 172.17.0.1 172.18.0.1 fe80::da5e:d3ff:fe2a:2a9b fe80::6a54:5aff:fecb:4729 fe80::42:ffff:fe04:9b86:12836
exporter address: 192.168.31.57 192.168.31.94 172.17.0.1 172.18.0.1 fe80::da5e:d3ff:fe2a:2a9b fe80::6a54:5aff:fecb:4729 fe80::42:ffff:fe04:9b86:11841
```

fix multi-host issue

---

docker/start_broker.sh
docker/start_controller.sh

Prometheus project change example config path from example_configs to examples, thus we should update it to avoid http 404 error 
[Link](https://raw.githubusercontent.com/prometheus/jmx_exporter/master/examples/kafka-2_0_0.yml)
[Project file](https://github.com/prometheus/jmx_exporter/blob/main/examples/kafka-2_0_0.yml)

[MINOR] Fix the  prometheus example path
