- README.md
My name GitHub name is chinghongfang.
> Add my name to README in authors field

- README.md
- docker/start_broker.sh
- docker/start_zk.sh
> add scripts to set up env quickly

- app/build.gradle
新增的設定可以使`gradle`產生如下的輸出
```
> Task :app:test
AppTest > appHasAGreeting() STARTED
AppTest > appHasAGreeting() PASSED
```
> enable gradle to show test event

- app/src/main/java/org/astraea/performance/latency/DataManager.java
- app/src/main/java/org/astraea/performance/latency/KafkaUtils.java
- app/src/test/java/org/astraea/performance/latency/FakeComponentFactory.java
- app/src/test/java/org/astraea/performance/latency/KafkaUtilsTest.java
Add random timestamp to all generated data
> Generated data should include random timestamp

- app/src/main/java/org/astraea/performance/latency/DataManager.java
- app/src/test/java/org/astraea/performance/latency/DataManagerTest.java
> Format generated data

- app/src/main/java/org/astraea/performance/latency/CloseableThread.java
- app/src/test/java/org/astraea/performance/latency/CloseableThreadTest.java
Add a new method and a new variable in `CloseableThread` to set the thread. Make the thread execute once.
> Let CloseableThread could execute once.

- README.md
- docker/start_broker.sh
- docker/start_tool.sh
- docker/start_zookeeper.sh
Add a script to run kafka official tool by container
> Enable to run kafka official tool by container

- README.md
> Add outline of tools

- app/build.gradle
我們目前並沒有使用slf4j，因此使用nop消除warning
> Use slf4j-nop to eliminate the slf4j warning

- README.md
Context: https://github.com/skiptests/astraea/issues/41#issuecomment-939436584
> add metric client to README.md

- README.md
- app/src/main/java/org/astraea/performance/latency/End2EndLatency.java
> Align the argument naming

- app/src/main/java/org/astraea/Utils.java
- app/src/main/java/org/astraea/topic/TopicAdmin.java
- app/src/test/java/org/astraea/topic/FakeTopicAdmin.java
- app/src/test/java/org/astraea/topic/ReplicaCollieTest.java
- app/src/test/java/org/astraea/topic/TopicAdminTest.java
- app/src/test/java/org/astraea/topic/TopicExplorerTest.java
- 重寫`ReplicaCollieTest`
- 穩定`TopicAdminTest`
> Rewrite ReplicaCollieTest by embedded server

- app/src/main/java/org/astraea/consumer/Header.java
- app/src/test/java/org/astraea/producer/ProducerTest.java
> add Header#of(String, byte[])

- docker/start_broker.sh
> Enable to build kafak with sasl

- app/src/main/java/org/astraea/argument/BasicArgumentWithPropFile.java
- app/src/main/java/org/astraea/performance/Performance.java
- app/src/main/java/org/astraea/topic/ReplicaCollie.java
- app/src/main/java/org/astraea/topic/TopicExplorer.java
> Unify prop.file

- app/src/test/java/org/astraea/topic/TopicAdminTest.java
> Fix flaky TopicAdminTest#testCreator

- app/src/main/java/org/astraea/partitioner/partitionerFactory/LinkPartitioner.java
> Weight should be sum correct

- app/src/main/java/org/astraea/performance/Tracker.java
> No consumer causes incorrect console output

- app/src/main/java/org/astraea/topic/Builder.java
- app/src/main/java/org/astraea/topic/TopicAdmin.java
- app/src/main/java/org/astraea/topic/TopicConfig.java
- app/src/main/java/org/astraea/topic/cost/GetPartitionInf.java
- app/src/test/java/org/astraea/topic/TopicAdminTest.java
Convert the `Map` to our interface so as to add more useful functions in the future.
> Add TopicConfig interface

- app/src/main/java/org/astraea/performance/Performance.java
- app/src/test/java/org/astraea/performance/CompressionArgumentTest.java
> Enable performance tool to apply compression

- README.md
- docker/start_broker.sh
- docker/start_zookeeper.sh
1. 讓zk service也能使用host folder
2. 找尋broker id從已經存在的host folder (這樣才能使用舊有資料重啟broker)
3. 自動建立host folder如果使用者指定的話
> Enable to mount host folder to zookeeper service

- app/src/main/java/org/astraea/metrics/MetricExplorer.java
- app/src/main/java/org/astraea/metrics/jmx/MBeanClient.java
- app/src/main/java/org/astraea/metrics/jmx/MBeanClientImpl.java
- app/src/main/java/org/astraea/partitioner/nodeLoadMetric/NodeLoadClient.java
- app/src/main/java/org/astraea/partitioner/nodeLoadMetric/NodeMetrics.java
- app/src/test/java/org/astraea/metrics/jmx/MBeanClientTest.java
- app/src/test/java/org/astraea/metrics/kafka/KafkaMetricsTest.java
- app/src/test/java/org/astraea/service/RequireJmxServerTest.java
在測試#123的時候發現沒有抽象化蠻不方便的，因此給`MBeanClient`抽出介面
> Make MBeanClient be interface

- app/src/main/java/org/astraea/topic/Builder.java
> Fix duplicate partition caused by TopicAdmin#replicas

- app/src/main/java/org/astraea/performance/ExeTime.java
- app/src/main/java/org/astraea/performance/Performance.java
- app/src/test/java/org/astraea/performance/ExeTimeTest.java
> Move ExeTime to separate file

- app/src/main/java/org/astraea/consumer/Builder.java
- app/src/main/java/org/astraea/producer/Builder.java
- app/src/main/java/org/astraea/producer/Producer.java
- app/src/main/java/org/astraea/topic/Creator.java
- app/src/main/java/org/astraea/topic/ReplicaSyncingMonitor.java
- app/src/main/java/org/astraea/topic/TopicAdmin.java
- app/src/test/java/org/astraea/partitioner/nodeLoadMetric/PartitionerTest.java
- app/src/test/java/org/astraea/producer/ProducerTest.java
- app/src/test/java/org/astraea/service/Services.java
- app/src/test/java/org/astraea/topic/TopicAdminTest.java
- app/src/test/java/org/astraea/topic/cost/GetPartitionInfTest.java
- app/src/test/java/org/astraea/topic/cost/PartitionScoreTest.java
compact topic也是一個用的資料方式，這邊讓我們封裝的APIs可以建立compact topic，並且補上測試情境
> Enable to configure compact topic

- app/src/test/java/org/astraea/service/RequireJmxServer.java
- app/src/test/java/org/astraea/service/RequireJmxServerTest.java
> The address of jmx server should not use '127.0.0.1'

- docker/start_broker.sh
- docker/start_kafka_tool.sh
- docker/start_prometheus.sh
- docker/start_zookeeper.sh
有些環境建立好linux時用的local address會是`127.0.1.1`，因此該位址也需要被檢查
> Check both 127.0.0.1 and 127.0.1.1 when running containers

- app/src/main/java/org/astraea/metrics/BeanCollector.java
- app/src/test/java/org/astraea/metrics/BeanCollectorTest.java
> Fix flaky BeanCollectorTest#testAddNode

- README.md
- docker/start_broker.sh
- docker/start_kafka_tool.sh
- docker/start_zookeeper.sh
1. 可透過`REPO`剛改docker repo
2. 可透過`RUN`來決定是否只要build image
> Enable to configure docker repo used by docker scripts

- docker/submit_spark_job.sh
1. 如同kafka broker script，此更新讓提交spark job時也可以掛載目錄
2. 顯示help messages
> Enable to mount host folders when submitting spark job

- gradle/wrapper/gradle-wrapper.properties
see https://gradle.org/releases/ for update notes
> Update gradle from 7.3.0 to 7.3.2

- app/src/main/java/org/astraea/metrics/collector/BeanCollector.java
- app/src/test/java/org/astraea/metrics/collector/BeanCollectorTest.java
1. 先計算是否要更新才去拿lock，這是一個小優化
2. rename `TestBeanCollector` -> `BeanCollectorTest`
> Check the condition of updating beans before requiring the lock

- app/src/main/java/org/astraea/performance/Performance.java
- app/src/main/java/org/astraea/performance/Tracker.java
#164 
將輸出文字改為英文，註解中有使用中文的部份也一併更新成英文。
> Log in english

- docker/start_astraea.sh
- docker/start_broker.sh
- docker/start_spark.sh
- docker/start_zookeeper.sh
類似`start_broker.sh`，這讓`start_spark.sh`也可以從source code來建立
> Enable to run spark by source code

- docker/start_astraea.sh
> Replace "" by "" so as to pass arguments without quotes

- README.md
- app/src/main/java/org/astraea/topic/ReplicaSyncingMonitor.java
> ASCII code character only

- docker/start_astraea.sh
> Using uber jar to run astraea instead of compiling

- docker/start_broker.sh
> start_broker.sh can't mount multiples host folders

- .gitignore
- docker/start_broker.sh
- docker/start_kafka_tool.sh
- docker/start_spark.sh
- docker/start_zookeeper.sh
由於`astraea`已經有人使用(in dockerhub)，因此我們將image repo移動到github package
see https://github.com/orgs/skiptests/packages?repo_name=astraea for all available docker images
> Move all docker images to github packages

- docker/start_broker.sh
- docker/start_kafka_tool.sh
- docker/start_spark.sh
- docker/start_zookeeper.sh
see https://github.com/skiptests/astraea/pull/184#issuecomment-1013826243
> Don't end script after downloading image

- docker/start_broker.sh
- docker/start_kafka_tool.sh
- docker/start_spark.sh
- docker/start_zookeeper.sh
這樣方便其他專案可以直接用`bash <(curl -fsSL https://raw.githubusercontent.com/skiptests/astraea/main/docker/start_zookeeper.sh)`來操作腳本
> Generate dockerfile only if it needs to build image

- docker/start_broker.sh
- docker/start_kafka_tool.sh
- docker/start_spark.sh
- docker/start_zookeeper.sh
spark在任務提交到k8s的腳本仰賴`tini`，而為了保持衛生乾淨，我將其他服務也都置於`tini`底下
> Run an init inside for zookeeper, broker, kafka-tool, and spark

- docker/start_kafka_tool.sh
這樣方便我們觀察performance tool (by JMX)
> Enable JMX on kafka tools

- app/src/main/java/org/astraea/topic/ReplicaCollie.java
resolve #217 
eliminate chinese.
> To english

- app/src/main/java/org/astraea/performance/Performance.java
- docker/start_broker.sh
針對測試過程中產生的問題進行一些修復。
#196 中出現的問題會有一定概率同樣發生在performance創建過程中，以同樣的方式wait()進行處理。
docker2G的內存有一些影響我們的performance的測試，現在調整為12G。
> Improvements to problems in testing

- README.md
- app/src/main/java/org/astraea/performance/ExeTime.java
- app/src/main/java/org/astraea/performance/Performance.java
- app/src/main/java/org/astraea/performance/Tracker.java
- app/src/test/java/org/astraea/performance/ExeTimeTest.java
#221
補齊文檔，並做更嚴格的參數檢查。
修改輸出文字的不一致(大小寫、空格)。
> Argument check strictly

- gradle/wrapper/gradle-wrapper.properties
- gradlew
> Upgrade gradle from 7.3.3 to 7.4

- docker/start_broker.sh
Context: https://github.com/skiptests/astraea/pull/202#issuecomment-1044137176
允許透過環境變數對 `start_broker.sh` 指定 JMX exporter config
> Enable to mount JMX exporter config for `start_broker.sh`

- app/build.gradle
- docker/start_broker.sh
the next release of 3.x is 3.1.0, so it is time to upgrade Kafka version
> Upgrade kafak from 2.8.1 to 3.1.0

- app/src/main/java/org/astraea/partitioner/ClusterInfo.java
- app/src/main/java/org/astraea/partitioner/Configuration.java
- app/src/main/java/org/astraea/partitioner/Dispatcher.java
- app/src/main/java/org/astraea/partitioner/FlexibleRoundRobinDispatcher.java
- app/src/main/java/org/astraea/partitioner/NodeInfo.java
- app/src/main/java/org/astraea/partitioner/PartitionInfo.java
- app/src/main/java/org/astraea/partitioner/nodeLoadMetric/NodeLoadClient.java
- app/src/main/java/org/astraea/partitioner/nodeLoadMetric/PartitionerUtils.java
- app/src/main/java/org/astraea/partitioner/smoothPartitioner/SmoothWeightPartitioner.java
- app/src/test/java/org/astraea/partitioner/nodeLoadMetric/NodeLoadClientTest.java
微調#251
1. 新增`Dispatcher`，該介面實作`Partitioner`並提供更適合astraea的方法
2. 封裝大部分的kafka cluster物件
3. 新增`Configuration`方便索取參數
> Flexible Round Robin partitoner v2

- .github/workflows/ci.yml
> Don't run test two times

- app/src/test/java/org/astraea/topic/ReplicaCollieTest.java
Fix flaky ReplicaCollie unit test
> fix flaky ReplicaCollieTest

- app/src/main/java/org/astraea/metrics/collector/BeanCollector.java
- app/src/main/java/org/astraea/metrics/collector/Fetcher.java
- app/src/main/java/org/astraea/metrics/collector/Register.java
- app/src/main/java/org/astraea/partitioner/StrictCostDispatcher.java
- app/src/main/java/org/astraea/partitioner/cost/CostFunction.java
- app/src/main/java/org/astraea/partitioner/cost/ThroughputCost.java
- app/src/main/java/org/astraea/partitioner/nodeLoadMetric/NodeLoadClient.java
- app/src/main/java/org/astraea/partitioner/nodeLoadMetric/ReceiverFactory.java
- app/src/test/java/org/astraea/metrics/collector/BeanCollectorTest.java
- app/src/test/java/org/astraea/metrics/collector/FetcherTest.java
新增`Fetcher`方便後續cost function擴增。之前直接使用java function會限制我們之後加上更多方便的函式
> Introduce Fetcher

- app/src/main/java/org/astraea/performance/Performance.java
- app/src/test/java/org/astraea/performance/PerformanceTest.java
`Long` 無法轉換成`int`，因此使用`NonNegativeShortField`。
> Use ShortConverter for "--consumer" parameter

- app/src/main/java/org/astraea/automation/Automation.java
- app/src/main/java/org/astraea/performance/Performance.java
> change return type of Performance#execute from Future to Result

- gradle/wrapper/gradle-wrapper.properties
- gradlew
> Upgrade gradle from 7.4.0 to 7.4.1

- app/src/main/java/org/astraea/cost/CostFunction.java
Remove stale `@param` in javadoc
> Improve the javadoc of `CostFunction`

- docker/start_broker.sh
> Generate broker dockerfile only if we need to build image locally

- app/src/main/java/org/astraea/producer/Builder.java
- app/src/main/java/org/astraea/producer/TransactionalSender.java
幾個調整：
1. 將用不到的介面隱藏起來
2.重複使用`send`相關的程式碼
> Tweak transactional producer

- gradle/wrapper/gradle-wrapper.properties
- gradlew
> Upgrade gradle from 7.4.1 to 7.4.2

- app/src/main/java/org/astraea/metrics/kafka/HasValue.java
- app/src/main/java/org/astraea/metrics/kafka/KafkaMetrics.java
- app/src/test/java/org/astraea/metrics/jmx/MBeanClientTest.java
在KafkaMetrics新增一個enum，方便未來cost function取得算分所需得metrics
> add ReplicaManager to KafkaMetrics

- app/src/main/java/org/astraea/web/Handler.java
- docker/start_kafka_tool.sh
1. 增加一些logs避免web service從終端機來看像是當掉了
2. 修正腳本的啟動錯誤
> Fix web service script and add more logs

- app/src/main/java/org/astraea/web/GroupHandler.java
- app/src/test/java/org/astraea/web/GroupHandlerTest.java
將不存在的instance id改為顯示null，這是因為gson還不支援optional
> Nonexistent instance group id should be null

- app/build.gradle
- docker/start_broker.sh
> Update Kafka from 3.1.0 to 3.1.1

- app/src/main/java/org/astraea/admin/Admin.java
- app/src/main/java/org/astraea/admin/Builder.java
- app/src/main/java/org/astraea/admin/Migrator.java
- app/src/main/java/org/astraea/admin/ReplicaCollie.java
- app/src/main/java/org/astraea/admin/TopicExplorer.java
- app/src/test/java/org/astraea/admin/AdminTest.java
如標題講的，現在`Admin`有一些方法需要傳入空集合來代表回傳“所有資料”，這個使用方式非常的...奇怪
> Don't use empty collection to imply it should return all data

- app/src/main/java/org/astraea/admin/Admin.java
- app/src/main/java/org/astraea/admin/Builder.java
- app/src/main/java/org/astraea/admin/ProducerState.java
- app/src/test/java/org/astraea/admin/AdminTest.java
> Enable to fetch producer state

- app/src/main/java/org/astraea/web/BrokerHandler.java
- app/src/main/java/org/astraea/web/ErrorObject.java
- app/src/main/java/org/astraea/web/GroupHandler.java
- app/src/main/java/org/astraea/web/Handler.java
- app/src/main/java/org/astraea/web/PostRequest.java
- app/src/main/java/org/astraea/web/TopicHandler.java
- app/src/test/java/org/astraea/web/BrokerHandlerTest.java
- app/src/test/java/org/astraea/web/ErrorObjectTest.java
- app/src/test/java/org/astraea/web/GroupHandlerTest.java
- app/src/test/java/org/astraea/web/HandlerTest.java
- app/src/test/java/org/astraea/web/PostRequestTest.java
- app/src/test/java/org/astraea/web/TopicHandlerTest.java
> Add POST and DELETE method

- app/src/main/java/org/astraea/admin/Admin.java
- app/src/main/java/org/astraea/admin/Builder.java
- app/src/main/java/org/astraea/web/BrokerHandler.java
- app/src/main/java/org/astraea/web/ErrorObject.java
- app/src/main/java/org/astraea/web/GroupHandler.java
- app/src/main/java/org/astraea/web/Handler.java
- app/src/main/java/org/astraea/web/TopicHandler.java
- app/src/test/java/org/astraea/admin/AdminTest.java
- app/src/test/java/org/astraea/web/BrokerHandlerTest.java
- app/src/test/java/org/astraea/web/GroupHandlerTest.java
- app/src/test/java/org/astraea/web/TopicHandlerTest.java
> pre-filter the data by user-defined target

- app/src/main/java/org/astraea/admin/Builder.java
- app/src/main/java/org/astraea/admin/TopicPartition.java
- app/src/main/java/org/astraea/web/Handler.java
- app/src/main/java/org/astraea/web/ProducerHandler.java
- app/src/main/java/org/astraea/web/WebService.java
- app/src/test/java/org/astraea/admin/TopicPartitionTest.java
- app/src/test/java/org/astraea/web/ProducerHandlerTest.java
新增Restful APIs可以調閱producer state
> Enable to fetch producer state by Restful APIs

- app/src/main/java/org/astraea/admin/Admin.java
- app/src/main/java/org/astraea/admin/Builder.java
- app/src/main/java/org/astraea/admin/Quota.java
- app/src/main/java/org/astraea/admin/QuotaCreator.java
- app/src/main/java/org/astraea/admin/ReplicaMigrator.java
- app/src/main/java/org/astraea/admin/TopicCreator.java
- app/src/test/java/org/astraea/admin/AdminTest.java
- app/src/test/java/org/astraea/admin/QuotaTest.java
這讓我們的admin更加豐富，並且在下一個階段可以加上restful apis
> Enable to write/read quota

- docker/start_broker.sh
- docker/start_kafka_tool.sh
- docker/start_spark.sh
- docker/start_zookeeper.sh
> Upgrade ubuntu from 20.04 to 22.04

- app/src/main/java/org/astraea/Utils.java
- app/src/main/java/org/astraea/web/PostRequest.java
- app/src/main/java/org/astraea/web/TopicHandler.java
- app/src/test/java/org/astraea/UtilsTest.java
- app/src/test/java/org/astraea/web/PostRequestTest.java
- app/src/test/java/org/astraea/web/TopicHandlerTest.java
新增一個方法讓使用者可以透過restful來建立topic，並且能指定partitions, replicas, and configuration
> Enable to create topic by restful

- app/src/main/java/org/astraea/admin/Builder.java
- app/src/main/java/org/astraea/admin/Quota.java
- app/src/main/java/org/astraea/web/QuotaHandler.java
- app/src/main/java/org/astraea/web/WebService.java
- app/src/test/java/org/astraea/admin/AdminTest.java
- app/src/test/java/org/astraea/web/QuotaHandlerTest.java
> Enable to read/write quotas by restful

- app/src/main/java/org/astraea/admin/Builder.java
- app/src/main/java/org/astraea/admin/Quota.java
- app/src/main/java/org/astraea/web/QuotaHandler.java
- app/src/test/java/org/astraea/admin/AdminTest.java
- app/src/test/java/org/astraea/admin/QuotaTest.java
- app/src/test/java/org/astraea/web/QuotaHandlerTest.java
> Rename Quota.Action to Quota.Limit

- app/src/main/java/org/astraea/consumer/Builder.java
- app/src/test/java/org/astraea/consumer/ConsumerTest.java
該方法可以接受一個整數值，並且在建立consuemr時候會先行計算適當的offset，並且將seek到該offset後再將已經設定好的consumer回傳給使用者
> A new seek mode: the distance from the latest offset

- README.md
- docker/start_prometheus.sh
The following changes are included by this PR.
1. remove JMX address
2. remove refresh
3. mount configuration file directly
4. increase scrape timeout
5. remove volumes
6. refactor
> Simplify prometheus script

- app/build.gradle
- app/src/main/java/org/astraea/Utils.java
- app/src/test/java/org/astraea/service/Database.java
- app/src/test/java/org/astraea/service/DatabaseTest.java
新增embedded cluster，這可以讓我們之後測試kafka與database的互動
> Add embedded MySQL

- app/build.gradle
- app/src/main/java/org/astraea/database/Builder.java
- app/src/main/java/org/astraea/database/ColumnInfo.java
- app/src/main/java/org/astraea/database/DatabaseClient.java
- app/src/main/java/org/astraea/database/TableCreator.java
- app/src/main/java/org/astraea/database/TableInfo.java
- app/src/main/java/org/astraea/database/TableQuery.java
- app/src/test/java/org/astraea/database/DatabaseClientTest.java
新增簡單的database client，包含：
1. 建立表格
2. 查詢表格
3. 刪除表格
> Add database client which is implemented by JDBC

- app/src/main/java/org/astraea/metrics/kafka/KafkaMetrics.java
- app/src/test/java/org/astraea/metrics/kafka/KafkaMetricsTest.java
幾個變更如下：
1. 修正typo，該錯誤導致無法拉取正確的metrics
2. 補上測試
> Fix typo: LodEndOffset -> LogEndOffset

- docs/Run Zookeeper.md
此PR的目的為將Run Zookeeper的Readme翻譯成中文版。
> Translate Readme Run Zookeeper in Chinese.

- README.md
- app/build.gradle
- docker/start_kafka_tool.sh
我們已經用腳本啟動程式好一陣子了，因此是時候將uber jar移除了
> Remove uber jar

- app/src/main/java/org/astraea/app/admin/Builder.java
> fix flaky test

- app/build.gradle
- docker/start_broker.sh
> Update kafka from 3.1.1 to 3.2.0

- app/src/main/java/org/astraea/app/admin/Builder.java
- app/src/main/java/org/astraea/app/admin/Replica.java
- app/src/test/java/org/astraea/app/admin/AdminTest.java
- app/src/test/java/org/astraea/app/admin/ReplicaSyncingMonitorTest.java
- app/src/test/java/org/astraea/app/admin/TopicExplorerTest.java
* Add `Replica#isPreferredLeader` flag.
* Fix #308 offline flag is not part of the `hashCode()` function result.
> Add Replica#isPreferredLeader flag

- app/src/main/java/org/astraea/app/admin/Admin.java
- app/src/main/java/org/astraea/app/admin/Builder.java
- app/src/main/java/org/astraea/app/admin/Transaction.java
- app/src/main/java/org/astraea/app/admin/TransactionState.java
- app/src/main/java/org/astraea/app/producer/Builder.java
- app/src/main/java/org/astraea/app/producer/Producer.java
- app/src/test/java/org/astraea/app/admin/AdminTest.java
- app/src/test/java/org/astraea/app/admin/TransactionStateTest.java
- app/src/test/java/org/astraea/app/producer/ProducerTest.java
這隻PR新增了三個功能：
1. producer現在可以手動指定transaction id
2. admin可以查詢transaction id
3. admin可以查詢transaction state
> Enable to query transaction state from Admin

- app/src/main/java/org/astraea/app/web/GroupHandler.java
- app/src/main/java/org/astraea/app/web/ProducerHandler.java
- app/src/main/java/org/astraea/app/web/TransactionHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/admin/AdminTest.java
- app/src/test/java/org/astraea/app/web/TransactionHandlerTest.java
- docs/web_server/web_api_groups_chinese.md
新增web apis用來查詢transaction state
> Add transaction web APIs

- app/src/main/java/org/astraea/app/web/BeansHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/web/BeanHandlerTest.java
一個簡單的程式碼來暴露beans，後續會再補上測試和更多query
> Web APIs for all beans

- app/src/main/java/org/astraea/app/consumer/Builder.java
- app/src/main/java/org/astraea/app/consumer/Consumer.java
- app/src/main/java/org/astraea/app/consumer/PartitionsBuilder.java
- app/src/main/java/org/astraea/app/consumer/TopicsBuilder.java
- app/src/main/java/org/astraea/app/performance/Performance.java
- app/src/test/java/org/astraea/app/admin/AdminTest.java
- app/src/test/java/org/astraea/app/admin/TopicExplorerTest.java
- app/src/test/java/org/astraea/app/consumer/ConsumerTest.java
- app/src/test/java/org/astraea/app/consumer/RebalanceListenerTest.java
- app/src/test/java/org/astraea/app/partitioner/smooth/SmoothWeightRoundRobinDispatchTest.java
- app/src/test/java/org/astraea/app/performance/PerformanceTest.java
- app/src/test/java/org/astraea/app/producer/ProducerTest.java
- app/src/test/java/org/astraea/app/web/GroupHandlerTest.java
related to comment https://github.com/skiptests/astraea/pull/405#discussion_r897002521
> Implement consumer assign topic partition api

- app/src/main/java/org/astraea/app/admin/Admin.java
- app/src/main/java/org/astraea/app/admin/Builder.java
- app/src/main/java/org/astraea/app/consumer/TopicsBuilder.java
- app/src/test/java/org/astraea/app/admin/AdminTest.java
> Enable to delete consumer group

- docker/start_app.sh
年紀大了，犯了低級錯誤...
應該在抓取到`--port`後就該跳出迴圈
> start_app.sh can't parse binding port when jmx port is defined

- app/src/main/java/org/astraea/app/consumer/Builder.java
- app/src/main/java/org/astraea/app/consumer/PartitionsBuilder.java
- app/src/main/java/org/astraea/app/consumer/Record.java
- app/src/main/java/org/astraea/app/consumer/TopicsBuilder.java
- app/src/main/java/org/astraea/app/web/RecordHandler.java
- app/src/test/java/org/astraea/app/consumer/ConsumerTest.java
- app/src/test/java/org/astraea/app/web/RecordHandlerTest.java
relates to https://github.com/skiptests/astraea/issues/360
> Implement topic read web apis

- README.md
> Move the WEB docs link to the beginning of README

- app/src/main/java/org/astraea/app/cost/ClusterInfo.java
- app/src/test/java/org/astraea/app/cost/ClusterInfoTest.java
> tweak ClusterInfo#of(ClusterInfo, Beans)

- app/src/main/java/org/astraea/app/partitioner/RoundRobin.java
- app/src/main/java/org/astraea/app/partitioner/StrictCostDispatcher.java
- app/src/test/java/org/astraea/app/partitioner/RoundRobinTest.java
- app/src/test/java/org/astraea/app/partitioner/StrictCostDispatcherTest.java
這個PR包含兩個工作：
1. 建立RR介面 and SMRR實作
2. 將SMRR整合到`StrictCostDispatcher`
> Integrate StrictCostDispatcher with SMRR

- app/src/main/java/org/astraea/app/partitioner/StrictCostDispatcher.java
- app/src/test/java/org/astraea/app/partitioner/StrictCostDispatcherTest.java
1. 當有cost functions需要JMX，而JMX又沒有被設置的時候，`StrictCostDispatcher`會直接拋錯
2. 移除`StrictCostDispatcher`多餘的建構式，改用`configure`來測試
> StrictCostDispatcher should fail immediately if jmx ports are undefined

- app/src/main/java/org/astraea/app/partitioner/StrictCostDispatcher.java
- app/src/test/java/org/astraea/app/partitioner/StrictCostDispatcherTest.java
see https://github.com/skiptests/astraea/pull/454#pullrequestreview-1027222597
> StrictCostDispatcher should return partition id rather than broker id

- app/src/main/java/org/astraea/app/argument/DurationField.java
- app/src/main/java/org/astraea/app/web/RecordHandler.java
- app/src/test/java/org/astraea/app/web/RecordHandlerTest.java
- docs/web_server/web_api_records_chinese.md
resolve https://github.com/skiptests/astraea/issues/450
> Support durationfield in timeout

- gradle/wrapper/gradle-wrapper.properties
- gradlew
> Upgrade gradle from 7.4.2 to 7.5

- app/src/main/java/org/astraea/app/web/TopicHandler.java
- app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
- docs/web_server/web_api_topics_chinese.md
> Enable to query topic with specify partition

- app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
> Fix testQueryWithPartition

- app/src/test/java/org/astraea/app/consumer/RebalanceListenerTest.java
這是我在 #513 沒寫好的地方，不小心留了一隻 thread 在操作 consumer
> Fix testConsumerRebalanceListener

- app/src/main/java/org/astraea/app/cost/CostUtils.java
- app/src/main/java/org/astraea/app/cost/CpuCost.java
- app/src/test/java/org/astraea/app/cost/CpuCostTest.java
> Refactor CpuCost

- app/src/main/java/org/astraea/app/cost/MemoryCost.java
- app/src/test/java/org/astraea/app/cost/CpuCostTest.java
- app/src/test/java/org/astraea/app/cost/MemoryCostTest.java
> Refactor MemoryCost

- app/src/main/java/org/astraea/app/common/Utils.java
- app/src/main/java/org/astraea/app/cost/CpuCost.java
- app/src/main/java/org/astraea/app/cost/MemoryCost.java
- app/src/main/java/org/astraea/app/metrics/KafkaMetrics.java
- app/src/main/java/org/astraea/app/metrics/collector/BeanCollector.java
- app/src/main/java/org/astraea/app/metrics/platform/HostMetrics.java
- app/src/test/java/org/astraea/app/common/UtilsTest.java
- app/src/test/java/org/astraea/app/metrics/KafkaMetricsTest.java
- app/src/test/java/org/astraea/app/metrics/collector/BeanCollectorTest.java
- app/src/test/java/org/astraea/app/metrics/platform/HostMetricsTest.java
- app/src/test/java/org/astraea/app/service/RequireJmxServerTest.java
> Refactor host metrics

- app/src/main/java/org/astraea/app/cost/NodeLatencyCost.java
- app/src/main/java/org/astraea/app/cost/NodeThroughputCost.java
Producer metrics已經提供基本的統計，我們應該只採用最新的指標就好
> Only take recent producer metrics

- app/src/test/java/org/astraea/app/admin/AdminTest.java
> Fix testDeleteRecord

- app/src/main/java/org/astraea/app/cost/NodeLatencyCost.java
- app/src/main/java/org/astraea/app/cost/NodeThroughputCost.java
- app/src/main/java/org/astraea/app/metrics/KafkaMetrics.java
- app/src/main/java/org/astraea/app/metrics/producer/ProducerMetrics.java
- app/src/test/java/org/astraea/app/cost/NodeLatencyCostTest.java
- app/src/test/java/org/astraea/app/metrics/producer/HasProducerNodeMetricsTest.java
- app/src/test/java/org/astraea/app/metrics/producer/HasProducerTopicMetricsTest.java
> Refactor producer metrics

- README.md
> Add a new author

- app/src/main/java/org/astraea/app/admin/Builder.java
- app/src/main/java/org/astraea/app/web/GroupHandler.java
- app/src/test/java/org/astraea/app/admin/AdminTest.java
- app/src/test/java/org/astraea/app/web/GroupHandlerTest.java
- docs/web_server/web_api_groups_chinese.md
resolve https://github.com/skiptests/astraea/issues/497 [Add delete group api](https://github.com/skiptests/astraea/issues/497)
> Add delete group api

- app/src/main/java/org/astraea/app/App.java
- app/src/main/java/org/astraea/app/balancer/BalanceProcessDemo.java
- app/src/main/java/org/astraea/app/balancer/log/ClusterLogAllocation.java
- app/src/test/java/org/astraea/app/balancer/BalanceProcessDemoTest.java
@chia7712 這是上個禮拜三提到，要我放上來的 Generator 和 Executor 使用範例
1. `BalancerProcessDemo#main` 是主要的進入點
2. `BalancerProcessDemoTest#run` 提供一個快速在測試內執行的範例
`BalancerProcessDemoTest#run` 結果:
```
[Before]
[TestingTopic-0] 0(Optional[/tmp/local_kafka14626902519260956202]) 2(Optional[/tmp/local_kafka11253759099362447978]) 
[TestingTopic-1] 2(Optional[/tmp/local_kafka11253759099362447978]) 1(Optional[/tmp/local_kafka16293464009788394727]) 
[TestingTopic-2] 1(Optional[/tmp/local_kafka13005076731925113899]) 0(Optional[/tmp/local_kafka14626902519260956202]) 
[TestingTopic-3] 0(Optional[/tmp/local_kafka16325439987434116715]) 1(Optional[/tmp/local_kafka3614035964014968359]) 
[TestingTopic-4] 2(Optional[/tmp/local_kafka16417985240373605211]) 0(Optional[/tmp/local_kafka17537739788417371504]) 
[TestingTopic-5] …
```
> Balance Process Demo

- app/src/main/java/org/astraea/app/web/RecordHandler.java
- app/src/test/java/org/astraea/app/web/RecordHandlerTest.java
- docs/web_server/web_api_records_chinese.md
resolve https://github.com/skiptests/astraea/issues/441
> Remove limit in RecordHandler#get

- app/src/main/java/org/astraea/app/common/Utils.java
- app/src/main/java/org/astraea/app/partitioner/StrictCostDispatcher.java
- app/src/test/java/org/astraea/app/common/UtilsTest.java
- app/src/test/java/org/astraea/app/partitioner/StrictCostDispatcherTest.java
> Apply Utils.constructCostFunction

- app/src/test/java/org/astraea/app/admin/AdminTest.java
- app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
resolve #533 Fix TopicHandlerTest#testDeleteTopic
sleep after create and delete topic
> Fix TopicHandlerTest#testDeleteTopic

- README.md
> Add Chao-Heng to author list

- app/src/main/java/org/astraea/app/metrics/broker/ControllerMetrics.java
- app/src/test/java/org/astraea/app/metrics/MetricsTestUtil.java
- app/src/test/java/org/astraea/app/metrics/broker/ControllerMetricsTest.java
- app/src/test/java/org/astraea/app/metrics/broker/LogMetricsTest.java
- app/src/test/java/org/astraea/app/metrics/broker/ReplicaManagerMetricsTest.java
- app/src/test/java/org/astraea/app/metrics/broker/ServerMetricsTest.java
resolve #543 Add Kafka controller metrics
> Add Kafka controller metrics

- README.md
> Add YHL to Authors

- gradle/wrapper/gradle-wrapper.properties
- gradlew
> Upgrade gradle from 7.5.0 to 7.5.1

- app/build.gradle
- docker/start_broker.sh
> Upgrade kafka from 3.2.0 to 3.2.1

- app/src/main/java/org/astraea/app/common/Utils.java
- app/src/test/java/org/astraea/app/common/UtilsTest.java
fixes https://github.com/skiptests/astraea/issues/565
> Fix Utils.swallowException

- app/src/main/java/org/astraea/app/performance/Performance.java
- app/src/test/java/org/astraea/app/performance/PerformanceTest.java
- docker/start_prometheus.sh
新增一隻簡單的猴子，該猴子會定時隨機重啟consumer，如此我們就可以觀察consumer balance的狀況
> Add simple chaos monkey to kill consumers

- app/src/main/java/org/astraea/app/admin/ClusterBean.java
- app/src/test/java/org/astraea/app/admin/ClusterBeanTest.java
slove #582 
移除`ClusterBean`中的MapByPartition
> removeMapByPartition

- docker/start_zookeeper.sh
> Upgrade zookeeper from 3.7.0 to 3.7.1

- app/src/test/java/org/astraea/app/admin/ReplicationThrottlerTest.java
Context: https://github.com/skiptests/astraea/issues/549#issuecomment-1218245743
> Address the issue of replication throttle in Kafka broker implementation

- app/src/main/java/org/astraea/app/performance/Performance.java
- app/src/main/java/org/astraea/app/performance/ReportFormat.java
- app/src/test/java/org/astraea/app/performance/ReportFormatTest.java
#579 
1. 將完成度移除
2. 改成使用當地時間紀錄
3. 修改 json 輸出格式
把資料名稱和資料統一放在一起了，方便新增、刪除要紀錄的數據。
> Reconstruct `ReportFormat`

- app/src/main/java/org/astraea/app/balancer/executor/RebalanceAdminImpl.java
- app/src/test/java/org/astraea/app/admin/AdminTest.java
- app/src/test/java/org/astraea/app/balancer/executor/RebalanceAdminTest.java
修正與 `RebalanceAdmin` 和 `ReplicationThrottler` 有關的 flaky tests
> Fix flaky tests

- app/src/main/java/org/astraea/app/cost/NodeTopicSizeCost.java
- app/src/main/java/org/astraea/app/cost/ReplicaDiskInCost.java
- app/src/main/java/org/astraea/app/cost/ReplicaLeaderCost.java
- app/src/main/java/org/astraea/app/metrics/broker/ControllerMetrics.java
- app/src/main/java/org/astraea/app/metrics/broker/HasGauge.java
- app/src/main/java/org/astraea/app/metrics/broker/HasHistogram.java
- app/src/main/java/org/astraea/app/metrics/broker/HasMeter.java
- app/src/main/java/org/astraea/app/metrics/broker/HasTimer.java
- app/src/main/java/org/astraea/app/metrics/broker/IsMeter.java
- app/src/main/java/org/astraea/app/metrics/broker/IsTimer.java
- app/src/main/java/org/astraea/app/metrics/broker/LogMetrics.java
- app/src/main/java/org/astraea/app/metrics/broker/NetworkMetrics.java
- app/src/main/java/org/astraea/app/metrics/broker/ServerMetrics.java
- app/src/main/java/org/astraea/app/metrics/platform/HostMetrics.java
- app/src/test/java/org/astraea/app/admin/ClusterBeanTest.java
- app/src/test/java/org/astraea/app/balancer/BalancerUtilsTest.java
- app/src/test/java/org/astraea/app/cost/NodeTopicSizeCostTest.java
- app/src/test/java/org/astraea/app/cost/ReplicaDiskInCostTest.java
- app/src/test/java/org/astraea/app/cost/ReplicaLeaderCostTest.java
- app/src/test/java/org/astraea/app/metrics/MetricsTestUtil.java
- app/src/test/java/org/astraea/app/metrics/broker/ControllerMetricsTest.java
- app/src/test/java/org/astraea/app/metrics/broker/LogMetricsTest.java
- app/src/test/java/org/astraea/app/metrics/broker/NetworkMetricsTest.java
- app/src/test/java/org/astraea/app/metrics/broker/ReplicaManagerMetricsTest.java
- app/src/test/java/org/astraea/app/metrics/broker/ServerMetricsTest.java
- app/src/test/java/org/astraea/app/metrics/broker/ServerTopicMetricsTest.java
> Add Kafka controll state metrics

- app/src/main/java/org/astraea/app/web/PostRequest.java
- app/src/main/java/org/astraea/app/web/QuotaHandler.java
- app/src/main/java/org/astraea/app/web/ReassignmentHandler.java
- app/src/main/java/org/astraea/app/web/RecordHandler.java
- app/src/main/java/org/astraea/app/web/TopicHandler.java
- app/src/test/java/org/astraea/app/web/PostRequestTest.java
1. 重新排序各個方法
2. 新增`requests`讓使用者可以解析陣列成各個不同的PostRequest
> Refactor PostRequest

- build.gradle
- etl/build.gradle
- etl/src/main/scala/org/astraea/etl/LinkedList.scala
- etl/src/test/scala/org/astraea/etl/LinkedListTest.scala
- settings.gradle
> add ETL module

- app/src/main/java/org/astraea/app/balancer/BalancerUtils.java
- app/src/main/java/org/astraea/app/balancer/generator/RebalancePlanGenerator.java
- app/src/main/java/org/astraea/app/cost/ReplicaLeaderCost.java
- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/cost/ReplicaLeaderCostTest.java
- app/src/test/java/org/astraea/app/partitioner/StrictCostDispatcherTest.java
- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
- docs/web_server/README.md
- docs/web_server/web_api_balancer_chinese.md
這隻PR是一個開頭，讓我們逐步將 balancer 透過 Web APIs 暴露出去，目前使用者可以呼叫`GET /balancer` 來取得評價更好的配置
> Enable to query better assignment by Web API

- app/src/main/java/org/astraea/app/web/Handler.java
- app/src/main/java/org/astraea/app/web/RecordHandler.java
- app/src/main/java/org/astraea/app/web/Response.java
- app/src/test/java/org/astraea/app/web/HandlerTest.java
- app/src/test/java/org/astraea/app/web/RecordHandlerTest.java
- docs/web_server/web_api_records_chinese.md
resolve https://github.com/skiptests/astraea/issues/546
> Support groupId in subscription mode in GET /records

- app/src/main/java/org/astraea/app/common/json/OptionalIntSerializer.java
- app/src/main/java/org/astraea/app/common/json/OptionalSerializer.java
- app/src/main/java/org/astraea/app/web/Response.java
- app/src/main/java/org/astraea/app/web/ThrottleHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/common/json/OptionalIntSerializerTest.java
- app/src/test/java/org/astraea/app/common/json/OptionalSerializerTest.java
- app/src/test/java/org/astraea/app/web/ThrottleHandlerTest.java
- docs/web_server/README.md
- docs/web_server/web_api_throttles_chinese.md
這個 PR 幫 web service 實作取得 throttle 設定的功能
```java
@Test
void testThrottleHandler1() {
try (Admin admin = Admin.of(bootstrapServers())) {
var handler = new ThrottleHandler(admin);
var topicName = Utils.randomString();
admin.creator().topic(topicName).numberOfPartitions(3).numberOfReplicas((short) 3).create();
Utils.sleep(Duration.ofSeconds(1));
admin
.replicationThrottler()
.throttle(topicName)
.ingress(DataRate.MiB.of(500).perSecond())
.egress(DataRate.MiB.of(500).perSecond())
.apply();
Utils.sleep(Duration.ofSeconds(1));
System.out.println(handler.get(Optional.empty(), Map.of()).json());
}
}
```
<details>
{
"brokers": {
"0": {
"ingress": 524288000,
"egress": 524288000
},
"1": {
"ingress": 524288000,
"egress": 524288000
},
"2": {
"ingress": 524288000,
"egress": 524288000
}
},
"topics": [
{ …
> Implementation of `GET /throttles` for WebService

- docker/start_app.sh
當使用`start_app.sh`啟動工具時，host file沒有被自動掛載到容器裡面的話，容器內的程式無法順利讀取`--prop.file`指定的檔案
> Enable to mount prop file automatically

- app/src/test/java/org/astraea/app/web/TransactionHandlerTest.java
如果執行得太慢，有些交易會處於尚未完成的狀態，因此加上wait確保都會完成
> Fix unstable TransactionHandlerTest

- app/src/main/java/org/astraea/app/admin/Builder.java
- app/src/main/java/org/astraea/app/admin/NodeInfo.java
> Refactor Admin#replicas and remove NodeInfo#isOffline

- app/src/main/java/org/astraea/app/admin/ClusterInfo.java
- app/src/main/java/org/astraea/app/admin/ReplicaInfo.java
- app/src/main/java/org/astraea/app/balancer/log/ClusterLogAllocation.java
- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- app/src/test/java/org/astraea/app/cost/ClusterInfoIntegratedTest.java
- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
- docs/web_server/web_api_balancer_chinese.md
1. 每個產生的規劃中會在來源地顯示replica大小，幫助閱讀
2. 重構幾隻常用的資料結構轉換
> Show the size of replica when running balancer plan

- app/src/main/java/org/astraea/app/admin/Admin.java
- app/src/main/java/org/astraea/app/admin/Builder.java
- app/src/main/java/org/astraea/app/admin/ReplicationThrottler.java
- app/src/main/java/org/astraea/app/web/PostRequest.java
- app/src/main/java/org/astraea/app/web/ThrottleHandler.java
- app/src/test/java/org/astraea/app/admin/AdminTest.java
- app/src/test/java/org/astraea/app/web/ThrottleHandlerTest.java
- docs/web_server/web_api_throttles_chinese.md
resolve #480
這個 PR 替 WebService 實作 `POST /throttles` 和 `DELETE /throttles`
> Implementation of `POST /throttles` and `DELETE /throttles` for WebService

- app/src/main/java/org/astraea/app/common/ExecutionRuntimeException.java
- app/src/main/java/org/astraea/app/common/Utils.java
- app/src/main/java/org/astraea/app/performance/Performance.java
在建立大型 topics (a bunch of partitions) 的時候需要更多的等候時間
> Give more time to wait the large topics

- app/src/main/java/org/astraea/app/cost/Dispersion.java
- app/src/test/java/org/astraea/app/cost/DispersionTest.java
修正`Dispersion#correlationCoefficient`在輸入數值都是0時會噴NaN的問題
> fix Dispersion

- app/src/main/java/org/astraea/app/performance/Performance.java
- app/src/test/java/org/astraea/app/performance/PerformanceTest.java
- docs/performance_benchmark.md
https://github.com/skiptests/astraea/pull/657#discussion_r959910253
修改 performance tool `specify.brokers` 參數的輸入驗證
修改參數名稱
更新文檔 (java doc, docs, discription)
> Change `specify.brokers` validation

- app/src/main/java/org/astraea/app/performance/Performance.java
> Remove stale docs of performance tool

- app/src/main/java/org/astraea/app/metrics/client/producer/HasProducerTopicMetrics.java
- app/src/main/java/org/astraea/app/metrics/client/producer/ProducerMetrics.java
- app/src/main/java/org/astraea/app/performance/TrackerThread.java
- app/src/test/java/org/astraea/app/metrics/client/producer/HasProducerTopicMetricsTest.java
顯示 local metrics 中的 `error rate`，這方便我們查知是否有在寫入資料過程中出現問題
> [Perf tool] show the error rate

- app/src/main/java/org/astraea/app/consumer/Builder.java
- app/src/main/java/org/astraea/app/consumer/Consumer.java
- app/src/main/java/org/astraea/app/consumer/PartitionsBuilder.java
- app/src/main/java/org/astraea/app/consumer/TopicsBuilder.java
- app/src/main/java/org/astraea/app/performance/ConsumerThread.java
- app/src/main/java/org/astraea/app/performance/TrackerThread.java
- app/src/test/java/org/astraea/app/consumer/ConsumerTest.java
- app/src/test/java/org/astraea/app/performance/TrackerTest.java
大部分的資訊可以透過metrics取得，因此現在可以簡化`Report`的邏輯
> Simplify ConsumerThread#Report

- app/src/main/java/org/astraea/app/admin/ClusterInfo.java
- app/src/main/java/org/astraea/app/balancer/RebalancePlanProposal.java
- app/src/main/java/org/astraea/app/balancer/generator/ShufflePlanGenerator.java
- app/src/main/java/org/astraea/app/balancer/log/ClusterLogAllocation.java
- app/src/main/java/org/astraea/app/cost/HasBrokerCost.java
- app/src/main/java/org/astraea/app/cost/HasClusterCost.java
- app/src/main/java/org/astraea/app/cost/HasMoveCost.java
- app/src/main/java/org/astraea/app/cost/MoveCost.java
- app/src/main/java/org/astraea/app/cost/ReplicaDiskInCost.java
- app/src/main/java/org/astraea/app/cost/ReplicaLeaderCost.java
- app/src/main/java/org/astraea/app/cost/ReplicaSizeCost.java
- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- app/src/test/java/org/astraea/app/balancer/RebalancePlanProposalTest.java
- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
1. 只要找到合適的plan就回傳，而非測試完所有可能
2. 新增`step`表達這是第幾個嘗試
3. 重構`RebalancePlanProposal`，移除重複的sync、和新增index欄位
> Return the suitable plan early

- docs/dispatcher/smooth_dispatcher.md
> Fix package of SmoothWeightRoundRobinDispatcher

- app/src/main/java/org/astraea/app/performance/TrackerThread.java
- app/src/test/java/org/astraea/app/performance/TrackerThreadTest.java
> Add tests for TrackerThread

- common/src/test/java/org/astraea/common/argument/ListFieldTest.java
fix https://github.com/skiptests/astraea/issues/686#issue-1367443588
> add FakeParameter to check list field

- common/src/main/java/org/astraea/common/partitioner/Dispatcher.java
> Fix raw type of Dispatcher

- app/src/test/java/org/astraea/app/performance/PerformanceTest.java
> Fix flaky PerformanceTest#testCustomCreateMode

- common/src/main/java/org/astraea/common/admin/Builder.java
https://github.com/skiptests/astraea/issues/595#issuecomment-1245602792
> Admin#replicas does not show the replicas moving to anohter folder

- app/src/main/java/org/astraea/app/scenario/Scenario.java
- app/src/main/java/org/astraea/app/scenario/ScenarioMain.java
- app/src/main/java/org/astraea/app/scenario/SkewedPartitionScenario.java
- app/src/main/java/org/astraea/app/web/TopicHandler.java
- app/src/test/java/org/astraea/app/scenario/SkewedPartitionScenarioTest.java
- app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
- docs/web_server/web_api_topics_chinese.md
> [Web APIs] enable to distribute partitions by probability

- app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
> Fix flay testCreateTopicByProbability

- common/src/main/java/org/astraea/common/metrics/client/consumer/ConsumerMetrics.java
- common/src/main/java/org/astraea/common/metrics/client/consumer/HasConsumerMetrics.java
- common/src/test/java/org/astraea/common/metrics/client/consumer/HasConsumerMetricsTest.java
> astraea-704 Add consumer metrics

- common/src/main/java/org/astraea/common/partitioner/Dispatcher.java
- docs/dispatcher/README.md
- docs/dispatcher/strict_cost_dispatcher.md
增加中文說明 Astraea Dispatcher 的功能-- "Interdependent Message"。
修正 Astraea Dispatcher 型別使用錯誤。
> Dispatcher 文件新增使用說明

- app/src/main/java/org/astraea/app/performance/Report.java
- app/src/main/java/org/astraea/app/performance/ReportFormat.java
- app/src/main/java/org/astraea/app/performance/TrackerThread.java
- common/src/main/java/org/astraea/common/Utils.java
> Report of performance does not fetch latest metrics

- app/src/main/java/org/astraea/app/performance/Performance.java
- app/src/test/java/org/astraea/app/performance/PerformanceTest.java
- docs/performance_benchmark.md
#701 和 #713 提供了豐富的方式來建構 topics 和 分佈 partitions，因此`perf`現在可以不用再負責建構 topics了
> [Perf] Don't create topics automatically anymore

- docs/web_server/README.md
現在的 web service 是使用 `star_app.sh` 來啟動的，`start_kafka_tool.sh` 已經不存在了，故作此修改。
> Update web service doc

- common/src/test/java/org/astraea/common/cost/ClusterInfoIntegratedTest.java
- common/src/test/java/org/astraea/common/cost/ClusterInfoTest.java
> Add test for ClusterInfo

- app/src/main/java/org/astraea/app/balancer/BalancerUtils.java
- app/src/test/java/org/astraea/app/balancer/BalancerUtilsTest.java
- app/src/test/java/org/astraea/app/balancer/FakeClusterInfo.java
- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/Builder.java
- common/src/main/java/org/astraea/common/admin/ClusterInfo.java
- common/src/main/java/org/astraea/common/admin/Replica.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
- common/src/test/java/org/astraea/common/admin/SomePartitionOfflineTest.java
- common/src/test/java/org/astraea/common/cost/ClusterInfoTest.java
- common/src/test/java/org/astraea/common/cost/ReplicaDiskInCostTest.java
- common/src/test/java/org/astraea/common/cost/ReplicaSizeCostTest.java
1. 事先排序資料以加速搜尋
2. `ClusterInfo#nodes`應該要為`Set`
> Tweak Admin#replicas

- app/src/main/java/org/astraea/app/balancer/BalancerBuilder.java
- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/Builder.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
> Remove Admin#partitions(Set<String>, Set<Integer>)

- app/src/main/java/org/astraea/app/balancer/BalanceProcessDemo.java
- app/src/main/java/org/astraea/app/balancer/BalancerBuilder.java
- app/src/test/java/org/astraea/app/balancer/BalancerTest.java
對於使用者而言，次數限制是一個很難評估的項目，因為硬體設備或是演算法這些因素加總後很難評估次數所需的時間，因此這隻 PR 直接新增一個新的限制 - 時間
> Balancer supports to set limit of execution time

- common/src/main/java/org/astraea/common/cost/HasBrokerCost.java
- common/src/main/java/org/astraea/common/partitioner/StrictCostDispatcher.java
- common/src/test/java/org/astraea/common/cost/BrokerCostTest.java
- common/src/test/java/org/astraea/common/partitioner/StrictCostDispatcherTest.java
> Add helper to merge multiple HasBrokerCost functions

- app/src/main/java/org/astraea/app/balancer/BalancerUtils.java
- app/src/main/java/org/astraea/app/balancer/executor/StraightPlanExecutor.java
- app/src/main/java/org/astraea/app/balancer/generator/ShufflePlanGenerator.java
- app/src/main/java/org/astraea/app/balancer/log/ClusterLogAllocation.java
- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- app/src/test/java/org/astraea/app/balancer/BalancerUtilsIntegratedTest.java
- app/src/test/java/org/astraea/app/balancer/BalancerUtilsTest.java
- app/src/test/java/org/astraea/app/balancer/FakeClusterInfo.java
- app/src/test/java/org/astraea/app/balancer/executor/StraightPlanExecutorTest.java
- app/src/test/java/org/astraea/app/balancer/log/ClusterLogAllocationTest.java
resolve #433 
用 `Replica` 取代 `LogPlacement`
> Revise `ClusterLogAllocation`

- app/src/main/java/org/astraea/app/balancer/BalanceProcessDemo.java
- app/src/main/java/org/astraea/app/balancer/Balancer.java
- app/src/main/java/org/astraea/app/balancer/BalancerBuilder.java
- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- app/src/test/java/org/astraea/app/balancer/BalancerTest.java
- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
#725 
把`bestPlan`內部改成使用balancer來產生plan，並且修改了相關的測試
但`testBestPlan`這個測試有機律會失敗，不會產生出新的plan，而是維持原狀
> Add `Balancer` into `BalancerHandler`

- app/src/main/java/org/astraea/app/web/PipelineHandler.java
- app/src/main/java/org/astraea/app/web/ProducerHandler.java
- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/Builder.java
- common/src/main/java/org/astraea/common/admin/ProducerState.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
> Integrate ProducerState with TopicPartition

- app/src/main/java/org/astraea/app/balancer/executor/RebalanceAdminImpl.java
- app/src/main/java/org/astraea/app/performance/Performance.java
- app/src/main/java/org/astraea/app/web/BrokerHandler.java
- app/src/main/java/org/astraea/app/web/GroupHandler.java
- app/src/main/java/org/astraea/app/web/PipelineHandler.java
- app/src/main/java/org/astraea/app/web/ProducerHandler.java
- app/src/main/java/org/astraea/app/web/RecordHandler.java
- app/src/main/java/org/astraea/app/web/TopicHandler.java
- app/src/test/java/org/astraea/app/web/ProducerHandlerTest.java
- app/src/test/java/org/astraea/app/web/RecordHandlerTest.java
- app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/Builder.java
- common/src/main/java/org/astraea/common/admin/Partition.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
> Admin#partitions should return full partition information

- common/src/test/java/org/astraea/common/consumer/ConsumerTest.java
> fix ConsumerTest

- app/src/test/java/org/astraea/app/web/TopicHandlerForProbabilityTest.java
- app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
fix #775
搬移到獨立的環境讓分佈不會受到其他測試的影響
> Fix flay TopicHandlerTest#testCreateTopicByProbability

- app/src/main/java/org/astraea/app/web/BrokerHandler.java
- app/src/main/java/org/astraea/app/web/ThrottleHandler.java
- app/src/test/java/org/astraea/app/web/ThrottleHandlerTest.java
- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/Builder.java
- common/src/main/java/org/astraea/common/admin/Config.java
- common/src/main/java/org/astraea/common/admin/Node.java
- common/src/main/java/org/astraea/common/admin/NodeInfo.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
這個新的類別會包含常見的節點資訊，例如 path, configs and topic partitions，如此我們可以移除一些瑣碎的方法
> Add new class Node to represent more details of node

- app/src/main/java/org/astraea/app/web/ThrottleHandler.java
- app/src/main/java/org/astraea/app/web/TopicHandler.java
- app/src/test/java/org/astraea/app/web/ThrottleHandlerTest.java
- app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/Builder.java
- common/src/main/java/org/astraea/common/admin/Topic.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
> Add Topic POJO

- gui/build.gradle
- gui/src/main/java/org/astraea/gui/AboutTab.java
- gui/src/main/java/org/astraea/gui/AddingReplicaTab.java
- gui/src/main/java/org/astraea/gui/BrokerConfigTab.java
- gui/src/main/java/org/astraea/gui/Console.java
- gui/src/main/java/org/astraea/gui/ConsumerTab.java
- gui/src/main/java/org/astraea/gui/Context.java
- gui/src/main/java/org/astraea/gui/CreateTopicTab.java
- gui/src/main/java/org/astraea/gui/ExcludeNodeTab.java
- gui/src/main/java/org/astraea/gui/IntegerBox.java
- gui/src/main/java/org/astraea/gui/Main.java
- gui/src/main/java/org/astraea/gui/NodeTab.java
- gui/src/main/java/org/astraea/gui/PartitionTab.java
- gui/src/main/java/org/astraea/gui/ProducerTab.java
- gui/src/main/java/org/astraea/gui/SettingTab.java
- gui/src/main/java/org/astraea/gui/ShortBox.java
- gui/src/main/java/org/astraea/gui/ShuffleReplicaTab.java
- gui/src/main/java/org/astraea/gui/TopicConfigTab.java
- gui/src/main/java/org/astraea/gui/TopicTab.java
- gui/src/main/java/org/astraea/gui/Utils.java
- settings.gradle
這是一個非常陽春的 GUI ，主要目的是提供一些快速審視 kafka 的方式
> Add simple GUI

- gui/src/main/java/org/astraea/gui/AddingReplicaTab.java
- gui/src/main/java/org/astraea/gui/ExcludeNodeTab.java
主要完成兩個項目：
1. 修復在沒有選擇任何 broker 的時候會出現 NPE
2. 可選擇的 broker 只限於該次目標 topics
3. AddingReplicaTab 可以搜尋 broker id
> Fix NPE in ExcludeNodeTab; AddingReplicaTab supports to search node

- app/src/main/java/org/astraea/app/balancer/log/ClusterLogAllocation.java
- common/src/main/java/org/astraea/common/admin/Replica.java
- common/src/main/java/org/astraea/common/admin/ReplicaBuilder.java
#773 
新增`replicaBuilder`，現在可以參照一個已存在的的`replica`，修改部份參數後回傳一個新的`replica`
> Add replica builder

- app/src/main/java/org/astraea/app/balancer/executor/RebalanceAdminImpl.java
- app/src/main/java/org/astraea/app/performance/Performance.java
- app/src/main/java/org/astraea/app/web/ReassignmentHandler.java
- app/src/main/java/org/astraea/app/web/TopicHandler.java
- app/src/test/java/org/astraea/app/balancer/BalancerTest.java
- app/src/test/java/org/astraea/app/balancer/executor/RebalanceAdminTest.java
- app/src/test/java/org/astraea/app/performance/PerformanceTest.java
- app/src/test/java/org/astraea/app/web/ReassignmentHandlerTest.java
- app/src/test/java/org/astraea/app/web/ThrottleHandlerTest.java
- app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/Builder.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
- common/src/test/java/org/astraea/common/admin/ReplicationThrottlerTest.java
- common/src/test/java/org/astraea/common/admin/SomePartitionOfflineTest.java
- gui/src/main/java/org/astraea/gui/ExcludeNodeTab.java
> Replace old replica

- app/src/main/java/org/astraea/app/web/BeanHandler.java
- app/src/main/java/org/astraea/app/web/BrokerHandler.java
- app/src/main/java/org/astraea/app/web/ThrottleHandler.java
- app/src/test/java/org/astraea/app/web/ThrottleHandlerTest.java
- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/Broker.java
- common/src/main/java/org/astraea/common/admin/Builder.java
- common/src/main/java/org/astraea/common/balancer/executor/RebalanceAdminImpl.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
- gui/src/main/java/org/astraea/gui/BrokerConfigTab.java
- gui/src/main/java/org/astraea/gui/BrokerTab.java
- gui/src/main/java/org/astraea/gui/TopicTab.java
> Rename Node to Broker; Add isController to Broker

- gui/src/main/java/org/astraea/gui/BrokerTab.java
新增一個欄位來顯示 broker 是否為 controller
> [GUI] add controller to BrokerTab

- common/src/test/java/org/astraea/common/admin/AdminTest.java
> Fix flaky AdminTest#testListPartitions

- app/src/test/java/org/astraea/app/web/RecordHandlerTest.java
> Fix flaky RecordHandlerTest#testDeleteParameter

- gui/src/main/java/org/astraea/gui/BalancerTab.java
將`greedy`放到gui上面，使用者有更大的機率在一次操作時獲取更好的結果
> [GUI] apply greedy to balancer

- gui/src/main/java/org/astraea/gui/AddingReplicaTab.java
- gui/src/main/java/org/astraea/gui/BalancerTab.java
- gui/src/main/java/org/astraea/gui/BrokerConfigTab.java
- gui/src/main/java/org/astraea/gui/BrokerTab.java
- gui/src/main/java/org/astraea/gui/Console.java
- gui/src/main/java/org/astraea/gui/ConsoleArea.java
- gui/src/main/java/org/astraea/gui/ConsumerTab.java
- gui/src/main/java/org/astraea/gui/CreateTopicTab.java
- gui/src/main/java/org/astraea/gui/PartitionTab.java
- gui/src/main/java/org/astraea/gui/ProducerTab.java
- gui/src/main/java/org/astraea/gui/ReassignReplicaTab.java
- gui/src/main/java/org/astraea/gui/SearchResult.java
- gui/src/main/java/org/astraea/gui/SettingTab.java
- gui/src/main/java/org/astraea/gui/TopicConfigTab.java
- gui/src/main/java/org/astraea/gui/TopicTab.java
- gui/src/main/java/org/astraea/gui/Utils.java
> Reformat all tabs by unified layout

- common/src/main/java/org/astraea/common/cost/ReplicaNumberCost.java
- common/src/test/java/org/astraea/common/cost/ReplicaNumberCostTest.java
當有節點在當薪水小偷的時候，我們應該回傳會高的成本表示無法接受
> ReplicaNumberCost should return highest cost when there are idle brokers

- app/src/main/java/org/astraea/app/web/TransactionHandler.java
- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/Builder.java
- common/src/main/java/org/astraea/common/admin/Transaction.java
- common/src/main/java/org/astraea/common/admin/TransactionState.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
- common/src/test/java/org/astraea/common/admin/TransactionStateTest.java
- docs/run_gui.md
- gui/src/main/java/org/astraea/gui/Main.java
- gui/src/main/java/org/astraea/gui/TransactionTab.java
> Add transaction tab

- gui/src/main/java/org/astraea/gui/TopicTab.java
> [GUI] TopicTab should show the partition distribution

- app/src/main/java/org/astraea/app/App.java
- app/src/main/java/org/astraea/app/version/Version.java
#808 
輸出結果如下
```
version: 0.0.1-SNAPSHOT
builder: Jia-Sheng Chen
revision: 322f51d01bc77861f1cd814ae57666f7dbd702db
date: 2022-10-05 17:28:16
```
> Add main class to expose version

- common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
- common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
- common/src/main/java/org/astraea/common/admin/Builder.java
- gui/src/main/java/org/astraea/gui/AddingReplicaTab.java
- gui/src/main/java/org/astraea/gui/BalancerTab.java
- gui/src/main/java/org/astraea/gui/BrokerTab.java
- gui/src/main/java/org/astraea/gui/ConfigTab.java
- gui/src/main/java/org/astraea/gui/ConsumerTab.java
- gui/src/main/java/org/astraea/gui/Context.java
- gui/src/main/java/org/astraea/gui/CreateTopicTab.java
- gui/src/main/java/org/astraea/gui/PartitionTab.java
- gui/src/main/java/org/astraea/gui/ProducerTab.java
- gui/src/main/java/org/astraea/gui/ReassignReplicaTab.java
- gui/src/main/java/org/astraea/gui/SettingTab.java
- gui/src/main/java/org/astraea/gui/TopicTab.java
- gui/src/main/java/org/astraea/gui/TransactionTab.java
- gui/src/main/java/org/astraea/gui/Utils.java
> [GUI] apply async admin

- common/src/main/java/org/astraea/common/cost/ReplicaLeaderCost.java
- common/src/main/java/org/astraea/common/metrics/broker/ControllerMetrics.java
- common/src/main/java/org/astraea/common/metrics/broker/ServerMetrics.java
- common/src/test/java/org/astraea/common/balancer/BalancerUtilsTest.java
- common/src/test/java/org/astraea/common/cost/ReplicaLeaderCostTest.java
- common/src/test/java/org/astraea/common/metrics/broker/ReplicaManagerMetricsTest.java
- common/src/test/java/org/astraea/common/metrics/broker/ServerMetricsTest.java
- gui/src/main/java/org/astraea/gui/AddingReplicaTab.java
- gui/src/main/java/org/astraea/gui/BalancerTab.java
- gui/src/main/java/org/astraea/gui/BrokerTab.java
- gui/src/main/java/org/astraea/gui/ConfigTab.java
- gui/src/main/java/org/astraea/gui/ConsumerTab.java
- gui/src/main/java/org/astraea/gui/Context.java
- gui/src/main/java/org/astraea/gui/Main.java
- gui/src/main/java/org/astraea/gui/MetricsTab.java
- gui/src/main/java/org/astraea/gui/PartitionTab.java
- gui/src/main/java/org/astraea/gui/ProducerTab.java
- gui/src/main/java/org/astraea/gui/ReassignReplicaTab.java
- gui/src/main/java/org/astraea/gui/SettingTab.java
- gui/src/main/java/org/astraea/gui/TopicTab.java
- gui/src/main/java/org/astraea/gui/TransactionTab.java
- gui/src/main/java/org/astraea/gui/Utils.java
允許使用者定義 jmx port 並且幫助撈回比較重要的資訊
> [GUI] add metrics tab

- common/src/main/java/org/astraea/common/LinkedHashSet.java
- common/src/main/java/org/astraea/common/admin/TopicCreator.java
- gui/src/main/java/org/astraea/gui/AddPartitionTab.java
- gui/src/main/java/org/astraea/gui/Context.java
- gui/src/main/java/org/astraea/gui/CreateTopicTab.java
- gui/src/main/java/org/astraea/gui/Main.java
- gui/src/main/java/org/astraea/gui/ReassignReplicaTab.java
- gui/src/main/java/org/astraea/gui/SettingTab.java
- gui/src/main/java/org/astraea/gui/Utils.java
重新調整了所有變更有關的頁面，邏輯調整如下：
1. 畫面分成四塊，第一塊為重要的參數、第二塊為較不重要的參數、第三塊是按鈕、第四塊則是 console 
2. 調整搜尋按鈕的排序，會影響搜尋的按鈕會先顯示出來，最後才會是搜尋按鈕
> [GUI] add standard page for write tab

- gui/src/main/java/org/astraea/gui/AddPartitionTab.java
- gui/src/main/java/org/astraea/gui/AddingReplicaTab.java
- gui/src/main/java/org/astraea/gui/BalancerTab.java
- gui/src/main/java/org/astraea/gui/BrokerTab.java
- gui/src/main/java/org/astraea/gui/ConfigTab.java
- gui/src/main/java/org/astraea/gui/ConsumerTab.java
- gui/src/main/java/org/astraea/gui/CreateTopicTab.java
- gui/src/main/java/org/astraea/gui/Main.java
- gui/src/main/java/org/astraea/gui/MetricsTab.java
- gui/src/main/java/org/astraea/gui/PartitionTab.java
- gui/src/main/java/org/astraea/gui/ProducerTab.java
- gui/src/main/java/org/astraea/gui/ReassignReplicaTab.java
- gui/src/main/java/org/astraea/gui/SearchResult.java
- gui/src/main/java/org/astraea/gui/TopicTab.java
- gui/src/main/java/org/astraea/gui/TransactionTab.java
- gui/src/main/java/org/astraea/gui/Utils.java
> [GUI] tweak the description of icon

- common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
- common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
- common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
讓`AsyncAdmin`可以動態更新 topic/broker 的參數
> Enable to update topic/broker configs

- common/src/main/java/org/astraea/common/LinkedHashSet.java
> Cleanup LinkedHashSet

- README.md
- gui/src/main/java/org/astraea/gui/AboutTab.java
- gui/src/main/java/org/astraea/gui/PaneBuilder.java
> [GUI] add chinese name and copyable table

- gui/src/main/java/org/astraea/gui/PaneBuilder.java
在產生`Output`的時候如果發生錯誤，該錯誤並沒有被導向console ...
> [GUI] show all error on console

- gui/src/main/java/org/astraea/gui/CreateTopicTab.java
- gui/src/main/java/org/astraea/gui/PaneBuilder.java
> [GUI] enable to config topic

- common/src/main/java/org/astraea/common/Utils.java
- common/src/main/java/org/astraea/common/admin/BrokerConfigs.java
- common/src/main/java/org/astraea/common/admin/TopicConfigs.java
- common/src/test/java/org/astraea/common/admin/BrokerConfigsTest.java
- gui/src/main/java/org/astraea/gui/Main.java
- gui/src/main/java/org/astraea/gui/MoveTopicTab.java
- gui/src/main/java/org/astraea/gui/MovingReplicaTab.java
- gui/src/main/java/org/astraea/gui/UpdateBrokerTab.java
- gui/src/main/java/org/astraea/gui/UpdateTopicTab.java
允許使用者透過GUI來更新 topic/broker 參數檔
> [GUI] enable to update configs of topic/broker

- gui/src/main/java/org/astraea/gui/ConsumerTab.java
ConsumerTab 在過濾 topic 的時候是採用"anyMatch"，這會導致不符合搜尋條件的 topic 也跟著被顯示出來
> [GUI] ConsumerTab should display the result matched to keyword

- README.md
> switching names in README.md

- gui/src/main/java/org/astraea/gui/AboutTab.java
- gui/src/main/java/org/astraea/gui/BalancerTab.java
- gui/src/main/java/org/astraea/gui/BrokerTab.java
- gui/src/main/java/org/astraea/gui/ConfigTab.java
- gui/src/main/java/org/astraea/gui/ConsumerTab.java
- gui/src/main/java/org/astraea/gui/CreateTopicTab.java
- gui/src/main/java/org/astraea/gui/MetricsTab.java
- gui/src/main/java/org/astraea/gui/MoveTopicTab.java
- gui/src/main/java/org/astraea/gui/MovingReplicaTab.java
- gui/src/main/java/org/astraea/gui/PaneBuilder.java
- gui/src/main/java/org/astraea/gui/PartitionTab.java
- gui/src/main/java/org/astraea/gui/ProducerTab.java
- gui/src/main/java/org/astraea/gui/SettingTab.java
- gui/src/main/java/org/astraea/gui/TopicTab.java
- gui/src/main/java/org/astraea/gui/TransactionTab.java
- gui/src/main/java/org/astraea/gui/UpdateBrokerTab.java
- gui/src/main/java/org/astraea/gui/UpdateTopicTab.java
> [GUI] Refactor PaneBuilder

- gui/src/main/java/org/astraea/gui/Main.java
- gui/src/main/java/org/astraea/gui/tab/TruncateRecordTab.java
> [GUI] enable to truncate records

- common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
- common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
- common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
- gui/src/main/java/org/astraea/gui/tab/UpdateBrokerTab.java
- gui/src/main/java/org/astraea/gui/tab/UpdateTopicTab.java
> Enable AsyncAdmin to unset topic/broker configs

- common/src/main/java/org/astraea/common/cost/BrokerInputCost.java
- common/src/main/java/org/astraea/common/cost/BrokerOutputCost.java
- common/src/main/java/org/astraea/common/cost/LoadCost.java
- common/src/main/java/org/astraea/common/metrics/broker/ServerMetrics.java
- common/src/test/java/org/astraea/common/cost/BrokerInputCostTest.java
- common/src/test/java/org/astraea/common/cost/BrokerOutputCostTest.java
- common/src/test/java/org/astraea/common/cost/LoadCostTest.java
- common/src/test/java/org/astraea/common/metrics/broker/ServerMetricsTest.java
- common/src/test/java/org/astraea/common/metrics/broker/ServerTopicMetricsTest.java
- gui/src/main/java/org/astraea/gui/tab/MetricsTab.java
添加以 topic 為目標的 metrics，這樣方便我們個別追蹤
> Add topic metrics

- README.md
> Add 2022 publication link

- common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
#837
上次更新不小心操作錯誤，導致資料變化非常亂，所以重新開一個
後續新測試會在此分之繼續更新
> Add tests in AsyncAdminTest

- .gitignore
- README.md
- docker/start_broker.sh
- docker/start_worker.sh
- docs/run_kafka_worker.md
- docs/run_worker.md
resolve https://github.com/skiptests/astraea/issues/734
> Add kafka worker script

- common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
- common/src/main/java/org/astraea/common/balancer/executor/RebalanceAdmin.java
- common/src/main/java/org/astraea/common/balancer/executor/RebalanceAdminImpl.java
- common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
1. 新增 `AsyncAdmin#waitCluster` 讓我們可以等待叢集狀態同步
2. deprecate `RebalanceAdmin`
> add AsyncAdmin#waitCluster to wait synced cluster state

- app/src/main/java/org/astraea/app/web/QuotaHandler.java
- app/src/test/java/org/astraea/app/web/QuotaHandlerTest.java
- common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
- common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
- common/src/main/java/org/astraea/common/admin/Builder.java
- common/src/main/java/org/astraea/common/admin/Quota.java
- common/src/main/java/org/astraea/common/admin/QuotaConfigs.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
- common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
> AsyncAdmin supports to set/unset quotas

- gui/src/main/java/org/astraea/gui/Context.java
- gui/src/main/java/org/astraea/gui/pane/BorderPane.java
- gui/src/main/java/org/astraea/gui/tab/BalancerTab.java
- gui/src/main/java/org/astraea/gui/tab/BrokerTab.java
- gui/src/main/java/org/astraea/gui/tab/ConfigTab.java
- gui/src/main/java/org/astraea/gui/tab/ConsumerTab.java
- gui/src/main/java/org/astraea/gui/tab/CreateTopicTab.java
- gui/src/main/java/org/astraea/gui/tab/MetricsTab.java
- gui/src/main/java/org/astraea/gui/tab/MovingReplicaTab.java
- gui/src/main/java/org/astraea/gui/tab/PartitionTab.java
- gui/src/main/java/org/astraea/gui/tab/ProducerTab.java
- gui/src/main/java/org/astraea/gui/tab/QuotaTab.java
- gui/src/main/java/org/astraea/gui/tab/SettingTab.java
- gui/src/main/java/org/astraea/gui/tab/TopicTab.java
- gui/src/main/java/org/astraea/gui/tab/TransactionTab.java
- gui/src/main/java/org/astraea/gui/tab/UpdateBrokerTab.java
- gui/src/main/java/org/astraea/gui/tab/UpdatePartitionTab.java
- gui/src/main/java/org/astraea/gui/tab/UpdateQuotaTab.java
- gui/src/main/java/org/astraea/gui/tab/UpdateTopicTab.java
幾個項目：
1. 各個 tabs 應該共用 `MBeanClient`
2. 簡化`Context`
3. 簡化`BorderPane`
> [GUI] all tabs should reuse mbean clients

- etl/src/test/scala/org/astraea/etl/DeployModeTest.scala
- etl/src/test/scala/org/astraea/etl/KafkaWriterTest.scala
- etl/src/test/scala/org/astraea/etl/MetadataTest.scala
因為原本的test我在本機跑了10W次都沒出錯，所以放上來進行測試。
> Fix flaky KafkaWriterTest#TopicCreatorTest

- gui/src/main/java/org/astraea/gui/tab/BalancerTab.java
如題，現在會應用`AsyncAdmin#waitCluster`來盡量確保不會遇到metadata不同步的狀態...
> [GUI] BalancerTab supports to mvoe folder

- common/src/test/java/org/astraea/common/balancer/BalancerAlgorithmTest.java
> Fix flaky BalancerAlgorithmTest#test

- gui/src/main/java/org/astraea/gui/pane/PaneBuilder.java
- gui/src/main/java/org/astraea/gui/tab/PartitionTab.java
- gui/src/main/java/org/astraea/gui/tab/TopicTab.java
> [GUI] support to delete topcs

- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- app/src/main/java/org/astraea/app/web/BeanHandler.java
- app/src/main/java/org/astraea/app/web/BrokerHandler.java
- app/src/main/java/org/astraea/app/web/GroupHandler.java
- app/src/main/java/org/astraea/app/web/Handler.java
- app/src/main/java/org/astraea/app/web/PipelineHandler.java
- app/src/main/java/org/astraea/app/web/ProducerHandler.java
- app/src/main/java/org/astraea/app/web/QuotaHandler.java
- app/src/main/java/org/astraea/app/web/ReassignmentHandler.java
- app/src/main/java/org/astraea/app/web/RecordHandler.java
- app/src/main/java/org/astraea/app/web/Response.java
- app/src/main/java/org/astraea/app/web/ThrottleHandler.java
- app/src/main/java/org/astraea/app/web/TopicHandler.java
- app/src/main/java/org/astraea/app/web/TransactionHandler.java
- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
- app/src/test/java/org/astraea/app/web/BeanHandlerTest.java
- app/src/test/java/org/astraea/app/web/BrokerHandlerTest.java
- app/src/test/java/org/astraea/app/web/GroupHandlerTest.java
- app/src/test/java/org/astraea/app/web/HandlerTest.java
- app/src/test/java/org/astraea/app/web/PipelineHandlerTest.java
- app/src/test/java/org/astraea/app/web/ProducerHandlerTest.java
- app/src/test/java/org/astraea/app/web/QuotaHandlerTest.java
- app/src/test/java/org/astraea/app/web/ReassignmentHandlerTest.java
- app/src/test/java/org/astraea/app/web/RecordHandlerTest.java
- app/src/test/java/org/astraea/app/web/ThrottleHandlerTest.java
- app/src/test/java/org/astraea/app/web/TopicHandlerForProbabilityTest.java
- app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
- app/src/test/java/org/astraea/app/web/TransactionHandlerTest.java
這隻PR先將 Handler 的用法都改成 async，之後再逐一將各個Handler替換成 AsyncAdmin
> [WEB] use async interface for Handler

- app/src/main/java/org/astraea/app/web/BeanHandler.java
- app/src/main/java/org/astraea/app/web/BrokerHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/web/BeanHandlerTest.java
- app/src/test/java/org/astraea/app/web/BrokerHandlerTest.java
- common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
- common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
- common/src/main/java/org/astraea/common/admin/Broker.java
- common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
> [WEB] BrokerHandler/BeanHandler use AsyncAdmin to replace Admin

- common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
- common/src/main/java/org/astraea/common/admin/Broker.java
- common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
如題，如果回傳 -1 的話會顯得很詭異 ... 不符合物理現象 :)
> The size of topic which having no data should be zero instead of -1

- common/src/main/java/org/astraea/common/admin/ClusterInfo.java
- common/src/main/java/org/astraea/common/balancer/BalancerBuilder.java
- common/src/main/java/org/astraea/common/balancer/BalancerUtils.java
- common/src/test/java/org/astraea/common/admin/AsyncAdminWithOfflineBrokerTest.java
- common/src/test/java/org/astraea/common/admin/ClusterInfoIntegratedTest.java
- common/src/test/java/org/astraea/common/admin/ClusterInfoTest.java
- common/src/test/java/org/astraea/common/admin/NodeInfoTest.java
- common/src/test/java/org/astraea/common/admin/ReplicaInfoTest.java
- common/src/test/java/org/astraea/common/balancer/BalancerTest.java
greedy 的過程中有幾個問題：
1. 重複 update cluster
2. 計算搬移成本的時候使用了錯的 cluster info
另外這隻 PR 也稍微重構了一下 ( resolve #585)
> Refactor greedy algorithm

- common/src/test/java/org/astraea/common/admin/AsyncAdminWithOfflineBrokerTest.java
> Add more tests for offline replicas

- gui/src/main/java/org/astraea/gui/tab/PartitionTab.java
> [GUI] enable to move all partitions

- app/src/main/java/org/astraea/app/web/GroupHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/web/GroupHandlerTest.java
- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
- common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
- common/src/main/java/org/astraea/common/admin/Builder.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
- common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
> [WEB] GroupHandler replace Admin by AsyncAdmin

- app/src/main/java/org/astraea/app/web/ProducerHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/web/ProducerHandlerTest.java
- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/Builder.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
> [WEB] replace Admin by AsyncAdmin for ProducerHandler

- app/src/main/java/org/astraea/app/scenario/ScenarioMain.java
- app/src/main/java/org/astraea/app/web/TopicHandler.java
- common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
- common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
- common/src/main/java/org/astraea/common/balancer/executor/RebalanceAdminImpl.java
- common/src/main/java/org/astraea/common/scenario/Scenario.java
- common/src/main/java/org/astraea/common/scenario/SkewedPartitionScenario.java
- common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
- common/src/test/java/org/astraea/common/balancer/BalancerTest.java
- common/src/test/java/org/astraea/common/scenario/SkewedPartitionScenarioTest.java
> Replace Admin by AsyncAdmin for Scenario

- gui/src/main/java/org/astraea/gui/tab/ClientTab.java
> [GUI] format timestamp of producer

- common/src/main/java/org/astraea/common/metrics/broker/LogMetrics.java
- common/src/test/java/org/astraea/common/metrics/broker/LogMetricsTest.java
- it/src/main/java/org/astraea/it/BrokerCluster.java
- it/src/main/java/org/astraea/it/RequireBrokerCluster.java
- it/src/main/java/org/astraea/it/RequireSingleBrokerCluster.java
- it/src/main/java/org/astraea/it/Services.java
如題，該metrics 可以讓我們知道還有多少沒被清除的資料
> Add LogCleanerManager metrics

- app/src/main/java/org/astraea/app/web/TopicHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/web/TopicHandlerForProbabilityTest.java
- app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
> Replace Admin by AsyncAdmin for TopicHandler

- app/src/main/java/org/astraea/app/web/RecordHandler.java
- app/src/main/java/org/astraea/app/web/TransactionHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/web/RecordHandlerTest.java
- app/src/test/java/org/astraea/app/web/TransactionHandlerTest.java
> [WEB] replace Admin by AsyncAdmin for TransactionHandler

- common/src/main/java/org/astraea/common/metrics/broker/ServerMetrics.java
- common/src/test/java/org/astraea/common/metrics/broker/ServerMetricsTest.java
as title，這是從 broker 作為 zk client 來紀錄的資訊
> Add zookeeper metrics

- common/src/main/java/org/astraea/common/metrics/broker/ServerMetrics.java
- gui/src/main/java/org/astraea/gui/tab/BrokerTab.java
> [GUI] add zk metrics to BrokerTab

- docker/start_zookeeper.sh
> Enable JMX for zookeeper

- common/src/main/java/org/astraea/common/metrics/AppInfo.java
- common/src/main/java/org/astraea/common/metrics/broker/ServerMetrics.java
- common/src/main/java/org/astraea/common/metrics/client/consumer/ConsumerMetrics.java
- common/src/main/java/org/astraea/common/metrics/client/producer/ProducerMetrics.java
- common/src/test/java/org/astraea/common/metrics/MetricsTestUtil.java
- common/src/test/java/org/astraea/common/metrics/broker/ServerMetricsTest.java
- common/src/test/java/org/astraea/common/metrics/client/consumer/ConsumerMetricsTest.java
- common/src/test/java/org/astraea/common/metrics/client/producer/ProducerMetricsTest.java
> Add AppInfo metrics

- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
- common/src/main/java/org/astraea/common/admin/Broker.java
- common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
- common/src/test/java/org/astraea/common/admin/AsyncAdminWithOfflineBrokerTest.java
- gui/src/main/java/org/astraea/gui/Context.java
- gui/src/main/java/org/astraea/gui/tab/BrokerTab.java
- gui/src/main/java/org/astraea/gui/tab/TopicTab.java
> [GUI] add folder tab to show details of data folder

- common/src/main/java/org/astraea/common/balancer/generator/ShufflePlanGenerator.java
- common/src/test/java/org/astraea/common/balancer/generator/ShufflePlanGeneratorTest.java
> Avoid the placement of unsuitable partition being alter

- common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
- common/src/main/java/org/astraea/common/admin/TopicChecker.java
- common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
- common/src/test/java/org/astraea/common/admin/TopicCheckerTest.java
> Enable AsyncAdmin to fetch timestamp of the latest records

- app/src/main/java/org/astraea/app/web/RecordHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/web/RecordHandlerTest.java
#920
replace Admin by AsyncAdmin for record
> [WEB] replace Admin by AsyncAdmin for record

- app/src/main/java/org/astraea/app/web/GroupHandler.java
- app/src/main/java/org/astraea/app/web/RecordHandler.java
- app/src/main/java/org/astraea/app/web/TopicHandler.java
- common/src/main/java/org/astraea/common/FutureUtils.java
- common/src/main/java/org/astraea/common/Utils.java
- common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
- common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
- common/src/main/java/org/astraea/common/admin/TopicChecker.java
- common/src/main/java/org/astraea/common/function/Bi3Function.java
- common/src/main/java/org/astraea/common/function/Bi4Function.java
- common/src/main/java/org/astraea/common/function/Bi5Function.java
- common/src/test/java/org/astraea/common/UtilsTest.java
- common/src/test/java/org/astraea/common/consumer/ConsumerTest.java
- common/src/test/java/org/astraea/common/metrics/collector/BeanCollectorTest.java
- common/src/test/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobinDispatchTest.java
- gui/src/main/java/org/astraea/gui/tab/PartitionTab.java
- gui/src/main/java/org/astraea/gui/tab/TopicTab.java
> Add FutureUtils

- common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
- common/src/main/java/org/astraea/common/admin/TopicChecker.java
- common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
- common/src/test/java/org/astraea/common/admin/TopicCheckerTest.java
- gui/build.gradle
- gui/src/main/java/org/astraea/gui/tab/TopicTab.java
如題，使用者可以設定要搜尋的時間範圍來過濾出沒有資料寫入的 topics
> [GUI] add no_write tab to search idle topics

- gui/src/main/java/org/astraea/gui/pane/PaneBuilder.java
- gui/src/main/java/org/astraea/gui/tab/BalancerTab.java
- gui/src/main/java/org/astraea/gui/tab/topic/PartitionTab.java
- gui/src/main/java/org/astraea/gui/tab/topic/TopicTab.java
如題，套用我們新的流程，使用者可以先查看 plans 後再執行
> [GUI] add two phases (plan and execute) for BalancerTab

- common/src/main/java/org/astraea/common/admin/AsyncAdminImpl.java
- gui/src/main/java/org/astraea/gui/pane/PaneBuilder.java
- gui/src/main/java/org/astraea/gui/tab/BalancerTab.java
- gui/src/main/java/org/astraea/gui/tab/BrokerTab.java
- gui/src/main/java/org/astraea/gui/tab/ClientTab.java
- gui/src/main/java/org/astraea/gui/tab/QuotaTab.java
- gui/src/main/java/org/astraea/gui/tab/SettingTab.java
- gui/src/main/java/org/astraea/gui/tab/topic/PartitionTab.java
- gui/src/main/java/org/astraea/gui/tab/topic/ReplicaTab.java
- gui/src/main/java/org/astraea/gui/tab/topic/TopicTab.java
- gui/src/main/java/org/astraea/gui/text/TextField.java
修正幾個小地方：
1. SettingTab 會將使用過的資訊存放到硬碟，下次開啟時會嘗試去載入最近的設定
2. 新增 input hint，顯示一些可用的範例
3. Consumer 欄位顯示`lag`代表落後多少 offset
> [GUI] tweak GUI

- gui/src/main/java/org/astraea/gui/pane/Input.java
- gui/src/test/java/org/astraea/gui/pane/InputTest.java
> [GUI] Input#emptyValueKeys does not return true keys with empty value

- gui/src/main/java/org/astraea/gui/pane/Input.java
- gui/src/main/java/org/astraea/gui/tab/topic/TopicTab.java
- gui/src/test/java/org/astraea/gui/pane/InputTest.java
> [GUI] sort the dynamic key of TopicTab

- common/src/test/java/org/astraea/common/admin/AsyncAdminTest.java
確定目前放在專案內的常數都是可以動態調整的內容 (for latest kafka)
> Add more dynamic configs test

- gui/src/main/java/org/astraea/gui/tab/topic/TopicTab.java
> [GUI] Config tab should offer internal info of topic

- common/src/main/java/org/astraea/common/admin/AsyncAdmin.java
- gui/src/main/java/org/astraea/gui/tab/topic/TopicTab.java
> [GUI] enable to configure poll timeout

- app/src/main/java/org/astraea/app/web/ReassignmentHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/web/ReassignmentHandlerTest.java
> [WEB] replace Admin by AsyncAdmin for ReassignmentHandler

- etl/src/test/scala/org/astraea/etl/ReaderTest.scala
- etl/src/test/scala/org/astraea/etl/Spark2KafkaTest.scala
#1002 #1007 這兩隻 flaky test太容易出錯了，因此現將它們disable。
> Make flaky test Disable

- app/src/main/java/org/astraea/app/automation/Automation.java
- app/src/main/java/org/astraea/app/performance/MonkeyThread.java
- app/src/main/java/org/astraea/app/performance/Performance.java
- app/src/test/java/org/astraea/app/performance/PerformanceTest.java
> Replace Admin By AsyncAdmin for Perf tool

- etl/build.gradle
- etl/src/main/scala/org/astraea/etl/Utils.scala
- etl/src/test/scala/org/astraea/etl/WriterTest.scala
> Fix flaky WriterTest#topicCreatorTest 

- app/src/main/java/org/astraea/app/web/ThrottleHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/web/ThrottleHandlerTest.java
- docs/web_server/web_api_throttles_chinese.md
> Replace Admin by AsyncAdmin for ThrottleHandler

- common/src/test/java/org/astraea/common/admin/AsyncAdminWithOfflineBrokerTest.java
> fix AsyncAdminWithOfflineBrokerTest

- app/src/test/java/org/astraea/app/balancer/BalanceProcessDemoTest.java
- common/src/test/java/org/astraea/common/admin/ClusterInfoIntegratedTest.java
- common/src/test/java/org/astraea/common/admin/ClusterInfoWithOfflineNodeTest.java
- common/src/test/java/org/astraea/common/admin/SomePartitionOfflineTest.java
- common/src/test/java/org/astraea/common/balancer/BalancerAlgorithmTest.java
- common/src/test/java/org/astraea/common/balancer/BalancerTest.java
- common/src/test/java/org/astraea/common/balancer/log/ClusterLogAllocationTest.java
- common/src/test/java/org/astraea/common/consumer/ConsumerTest.java
- common/src/test/java/org/astraea/common/cost/ClusterCostTest.java
- common/src/test/java/org/astraea/common/cost/ClusterInfoIntegratedTest.java
- common/src/test/java/org/astraea/common/cost/NodeLatencyCostTest.java
- common/src/test/java/org/astraea/common/metrics/client/admin/AdminMetricsTest.java
- common/src/test/java/org/astraea/common/metrics/client/producer/ProducerMetricsTest.java
- common/src/test/java/org/astraea/common/partitioner/DispatcherTest.java
- common/src/test/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobinDispatchTest.java
如題，盡可能地取代，應該剩下balancer相關的程式碼還沒有被改完
> Replace Admin by AsyncAdmin for test code

- gui/build.gradle
- gui/src/main/java/org/astraea/gui/Context.java
- gui/src/main/java/org/astraea/gui/pane/Input.java
- gui/src/main/java/org/astraea/gui/pane/PaneBuilder.java
- gui/src/main/java/org/astraea/gui/tab/topic/PartitionTab.java
- gui/src/main/java/org/astraea/gui/tab/topic/ReplicaTab.java
- gui/src/test/java/org/astraea/gui/pane/InputTest.java
- gui/src/test/java/org/astraea/gui/tab/topic/ReplicaTabTest.java
將移動 replicas 的功能放到 ReplicaTab
將增加 partitions 放到 PartitionTab
> [GUI] move "add partitions" to ReplicaTab

- gui/src/main/java/org/astraea/gui/pane/Tab.java
- gui/src/main/java/org/astraea/gui/tab/BrokerTab.java
> [GUI] remove useless dynamic tab

- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
> [WEB] replace Admin by AsyncAdmin for BalancerHandler

- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- app/src/test/java/org/astraea/app/balancer/BalanceProcessDemoTest.java
- common/src/main/java/org/astraea/common/admin/AdminImpl.java
- common/src/main/java/org/astraea/common/admin/ClusterInfo.java
- common/src/main/java/org/astraea/common/balancer/algorithms/GreedyBalancer.java
- common/src/main/java/org/astraea/common/balancer/algorithms/SingleStepBalancer.java
- common/src/main/java/org/astraea/common/balancer/executor/StraightPlanExecutor.java
- common/src/main/java/org/astraea/common/balancer/generator/ShufflePlanGenerator.java
- common/src/main/java/org/astraea/common/balancer/log/ClusterLogAllocation.java
- common/src/test/java/org/astraea/common/balancer/BalancerTest.java
- common/src/test/java/org/astraea/common/balancer/FakeClusterInfo.java
- common/src/test/java/org/astraea/common/balancer/RebalancePlanProposalTest.java
- common/src/test/java/org/astraea/common/balancer/executor/StraightPlanExecutorTest.java
- common/src/test/java/org/astraea/common/balancer/generator/ShufflePlanGeneratorTest.java
- common/src/test/java/org/astraea/common/balancer/log/ClusterLogAllocationTest.java
- common/src/test/java/org/astraea/common/cost/ClusterInfoIntegratedTest.java
- common/src/test/java/org/astraea/common/cost/NeutralIntegratedCostTest.java
- common/src/test/java/org/astraea/common/cost/ReplicaSizeCostTest.java
- gui/build.gradle
- gui/src/main/java/org/astraea/gui/tab/BalancerNode.java
- gui/src/test/java/org/astraea/gui/tab/BalancerTabTest.java
> Make ClusterLogAllocation extend ClusterInfo<Replica>

- gui/src/main/java/org/astraea/gui/tab/topic/ReplicaNode.java
- gui/src/test/java/org/astraea/gui/tab/topic/ReplicaTabTest.java
> [GUI] enable to change both broker and path on ReplicaTab

- .github/workflows/ci.yml
這隻PR嘗試將CI用容器化去執行，這有幾個好處：
1. CI image 會包含我們過程中要用到的所有第三方套件，可以加速
2. 環境方便我們掌控
> Run CI by container

- common/src/main/java/org/astraea/common/balancer/executor/StraightPlanExecutor.java
- common/src/main/java/org/astraea/common/balancer/log/ClusterLogAllocation.java
resolve #1040.
使 `StraightPlanExecutor` 等待 migration 結束，才視為負載平衡計劃完成。
> Fix Flaky `StraightPlanExecutorTest#testAsyncRun`

- app/build.gradle
- common/build.gradle
- docker/start_broker.sh
- docker/start_worker.sh
- etl/build.gradle
- gui/build.gradle
- it/build.gradle
- it/src/main/java/org/astraea/it/Services.java
> Upgrade kafka from 3.2.1 to 3.3.1

- app/build.gradle
- common/build.gradle
- docker/start_zookeeper.sh
- etl/build.gradle
- etl/src/test/scala/org/astraea/etl/FileCreator.scala
- gui/build.gradle
- it/build.gradle
- junit 5.8.2 -> 5.9.1
- mockito 4.6.1 -> 4.8.1
- slf4j 1.7.36 -> 2.0.3
- gson 2.9.0 -> 2.10.0
- opencv 4.1 -> 5.7.1
- mysql 8.0.29 -> 8.0.31
- zookeeper 3.6.3 -> 3.8.0
> Upgrade dependencies

- app/src/main/java/org/astraea/app/performance/MonkeyThread.java
- app/src/main/java/org/astraea/app/performance/Performance.java
> Fix failed build caused by #1049

- gui/src/main/java/org/astraea/gui/pane/PaneBuilder.java
- gui/src/main/java/org/astraea/gui/tab/BalancerNode.java
> [GUI] Fix NPE caused by Balancer

- common/src/main/java/org/astraea/common/admin/AdminImpl.java
- common/src/main/java/org/astraea/common/admin/Replica.java
- common/src/main/java/org/astraea/common/admin/ReplicaBuilder.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
- common/src/test/java/org/astraea/common/balancer/generator/ShufflePlanGeneratorTest.java
- gui/src/main/java/org/astraea/gui/tab/topic/ReplicaNode.java
- gui/src/test/java/org/astraea/gui/tab/BalancerNodeTest.java
- gui/src/test/java/org/astraea/gui/tab/topic/ReplicaNodeTest.java
`internal`是一個常用於過濾的欄位，因此將該欄位加入 replica tab
> [GUI] add internal field to replica tab

- gui/src/main/java/org/astraea/gui/button/SelectBox.java
- gui/src/main/java/org/astraea/gui/pane/Argument.java
- gui/src/main/java/org/astraea/gui/pane/MultiInput.java
- gui/src/main/java/org/astraea/gui/pane/PaneBuilder.java
- gui/src/main/java/org/astraea/gui/tab/AboutNode.java
- gui/src/main/java/org/astraea/gui/tab/BalancerNode.java
- gui/src/main/java/org/astraea/gui/tab/BrokerNode.java
- gui/src/main/java/org/astraea/gui/tab/ClientNode.java
- gui/src/main/java/org/astraea/gui/tab/QuotaNode.java
- gui/src/main/java/org/astraea/gui/tab/SettingNode.java
- gui/src/main/java/org/astraea/gui/tab/topic/PartitionNode.java
- gui/src/main/java/org/astraea/gui/tab/topic/ReplicaNode.java
- gui/src/main/java/org/astraea/gui/tab/topic/TopicNode.java
- gui/src/main/java/org/astraea/gui/table/TableViewer.java
- gui/src/test/java/org/astraea/gui/pane/InputTest.java
- gui/src/test/java/org/astraea/gui/tab/BalancerNodeTest.java
- gui/src/test/java/org/astraea/gui/tab/topic/ReplicaNodeTest.java
重構 PaneBuilder
1. 整個畫面分成四部分，從 first part -> table view -> second part -> console
2. 呼叫者一次設定一個 part
3. `tableRefresher`回傳值的時候才會顯示 table view，並且同時顯示 second part，否則都會隱藏
> [GUI] refactor PaneBuilder to decouple first/second part

- common/src/main/java/org/astraea/common/DataSize.java
- gui/src/main/java/org/astraea/gui/pane/PaneBuilder.java
- gui/src/main/java/org/astraea/gui/pane/Slide.java
- gui/src/main/java/org/astraea/gui/pane/TableRefresher.java
- gui/src/main/java/org/astraea/gui/tab/BalancerNode.java
- gui/src/main/java/org/astraea/gui/tab/ClientNode.java
- gui/src/main/java/org/astraea/gui/table/TableViewer.java
- gui/src/test/java/org/astraea/gui/tab/BalancerNodeTest.java
> [GUI] show the cost of re-balance

- common/src/test/java/org/astraea/common/admin/AdminTest.java
> Fix flaky AdminTest#testMoveLeaderBroker

- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/backup/ByteBufferUtils.java
- common/src/main/java/org/astraea/common/backup/RecordReader.java
- common/src/main/java/org/astraea/common/backup/RecordWriter.java
- common/src/main/java/org/astraea/common/consumer/Builder.java
- common/src/test/java/org/astraea/common/backup/TestReaderWriter.java
- common/src/test/java/org/astraea/common/consumer/ConsumerTest.java
> Add basic recrod reader/writer

- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
> Fix Flaky AdminTest#testTimestampOfLatestRecords

- common/src/main/java/org/astraea/common/json/JsonConverter.java
- common/src/test/java/org/astraea/common/json/JsonConverterTest.java
> astraea-1081 Json converter should serialize Map equals

- common/src/main/java/org/astraea/common/balancer/executor/StraightPlanExecutor.java
- gui/src/main/java/org/astraea/gui/tab/BalancerNode.java
> Show something when wait balance

- common/src/main/java/org/astraea/common/cost/BrokerOutputCost.java
- common/src/test/java/org/astraea/common/cost/BrokerOutputCostTest.java
補上`BrokerOutputCost`的`ClusterCost`
> add ClusterCost to BrokerOutputCost

- app/src/main/java/org/astraea/app/App.java
- app/src/main/java/org/astraea/app/backup/Exporter.java
- app/src/main/java/org/astraea/app/backup/Importer.java
- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/backup/ByteBufferUtils.java
- common/src/main/java/org/astraea/common/backup/RecordReader.java
- common/src/main/java/org/astraea/common/backup/RecordWriter.java
- common/src/main/java/org/astraea/common/consumer/Builder.java
- common/src/main/java/org/astraea/common/consumer/IteratorLimit.java
- common/src/test/java/org/astraea/common/backup/TestReaderWriter.java
- common/src/test/java/org/astraea/common/consumer/ConsumerTest.java
> Add simple Import/Export

- common/src/main/java/org/astraea/common/metrics/stats/AvgRateByTime.java
- common/src/main/java/org/astraea/common/metrics/stats/ExpWeightAvgByTime.java
- common/src/main/java/org/astraea/common/metrics/stats/ExpWeightByTime.java
- common/src/main/java/org/astraea/common/metrics/stats/RateByTime.java
- common/src/test/java/org/astraea/common/metrics/stats/ExpWeightByTimeTest.java
為了要使用exponentially weighted moving average來計算一段時間內的加權平均值(時間愈久權重愈小)，新增`ExpWeightByTime`來實作`Stat`
> add ExpWeightByTime

- gui/src/main/java/org/astraea/gui/tab/BrokerNode.java
- gui/src/main/java/org/astraea/gui/tab/topic/TopicNode.java
> typo: alert -> alter

- common/src/main/java/org/astraea/common/admin/Admin.java
- gui/src/main/java/org/astraea/gui/Context.java
- gui/src/main/java/org/astraea/gui/Main.java
- gui/src/main/java/org/astraea/gui/tab/ClientNode.java
一個簡單的頁面方便我們將 csv 資料放到指定的 topics
> [GUI] add import node

- app/src/main/java/org/astraea/app/backup/Importer.java
- app/src/test/java/org/astraea/app/backup/TestImportExport.java
> [BACKUP] import headers

- common/src/main/java/org/astraea/common/cost/Configuration.java
- common/src/main/java/org/astraea/common/producer/Metadata.java
- connector/build.gradle
- connector/src/main/java/org/astraea/connector/Definition.java
- connector/src/main/java/org/astraea/connector/SourceConnector.java
- connector/src/main/java/org/astraea/connector/SourceTask.java
- connector/src/test/java/org/astraea/connector/SourceConnectorTest.java
- settings.gradle
如題，我們將之後要實作的 connector 放在這個模組裡面
> [CONNECTOR] add connector module

- common/src/main/java/org/astraea/common/backup/RecordReader.java
- common/src/main/java/org/astraea/common/consumer/Record.java
> add builder for consumer record

- common/build.gradle
- connector/build.gradle
- connector/src/main/java/org/astraea/connector/fs/FileSystem.java
- connector/src/main/java/org/astraea/connector/fs/FtpFileSystem.java
- connector/src/test/java/org/astraea/connector/fs/FtpFileSystemTest.java
- it/build.gradle
- it/src/main/java/org/astraea/it/FtpServer.java
接下來要開始銜接各種檔案系統，這隻PR以最傳統的`ftp server`作為開始，提供了一個基本的檔案系統介面，並且實作了 ftp 的版本，同時在 it 模組中增加了 ftp server 作為測試需求
> [CONNECTOR] add ftp server, ftp client, and file system interface

- common/src/main/java/org/astraea/common/Configuration.java
- connector/build.gradle
- fs/build.gradle
- fs/src/main/java/org/astraea/fs/FileSystem.java
- fs/src/main/java/org/astraea/fs/Type.java
- fs/src/main/java/org/astraea/fs/ftp/FtpFileSystem.java
- fs/src/main/java/org/astraea/fs/local/LocalFileSystem.java
- fs/src/test/java/org/astraea/fs/FileSystemTest.java
- fs/src/test/java/org/astraea/fs/ftp/FtpFileSystemTest.java
- fs/src/test/java/org/astraea/fs/local/LocalFileSystemTest.java
- it/src/main/java/org/astraea/it/FtpServer.java
> [FS] add local file system

- app/src/main/java/org/astraea/app/backup/Exporter.java
- common/src/main/java/org/astraea/common/backup/ByteUtils.java
- common/src/main/java/org/astraea/common/backup/RecordReader.java
- common/src/main/java/org/astraea/common/backup/RecordWriter.java
- common/src/main/java/org/astraea/common/backup/RecordWriterBuilder.java
- common/src/test/java/org/astraea/common/backup/TestReaderWriter.java
> [BAKCUP] Apply RecordWriter on Exporter

- common/src/test/java/org/astraea/common/metrics/broker/LogMetricsTest.java
> remove unused code in LogMetricsTest

- docker/start_spark.sh
- etl/src/main/scala/org/astraea/etl/DeployMode.scala
- etl/src/main/scala/org/astraea/etl/Metadata.scala
- etl/src/main/scala/org/astraea/etl/Spark2Kafka.scala
- etl/src/test/scala/org/astraea/etl/DeployModeTest.scala
- etl/src/test/scala/org/astraea/etl/Spark2KafkaTest.scala
在跑submit的時候有一些bug。先發上來修一下。
“deploy.model”與properties中的不一致
`excutor`中配置Duration.inf在實際無法運行。
> Fix deploy.model && excutor()

- common/src/main/java/org/astraea/common/balancer/algorithms/GreedyBalancer.java
- common/src/test/java/org/astraea/common/balancer/algorithms/GreedyBalancerTest.java
> [BALANCER] simplify JMX register of greedy balancer

- app/src/main/java/org/astraea/app/performance/ConsumerThread.java
#1122
remove all unused `@SuppressWarnings`
> Remove unused SuppressWarnings from ConsumerThread

- app/src/main/java/org/astraea/app/web/Response.java
- app/src/main/java/org/astraea/app/web/ThrottleHandler.java
- app/src/test/java/org/astraea/app/web/ThrottleHandlerTest.java
ref #974 [JSON][WEB] Implement ThrottleHandler post request by Jackson
> astraea-974 Implement ThrottleHandler post request

- connector/src/main/java/org/astraea/connector/Definition.java
- connector/src/main/java/org/astraea/connector/SinkConnector.java
- connector/src/main/java/org/astraea/connector/SinkTask.java
- connector/src/test/java/org/astraea/connector/ConnectorTest.java
如題，這加入屬於 Astraea 自己的封裝，更多的測試和實作將陸續由 https://github.com/skiptests/astraea/issues/1188 https://github.com/skiptests/astraea/issues/1114 https://github.com/skiptests/astraea/issues/870 等議題完成
> [CONNECTOR] add Astraea sink

- gradle/wrapper/gradle-wrapper.properties
- gradlew
> Upgrade gradle from 7.5.1 to 7.6

- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
- common/src/main/java/org/astraea/common/Utils.java
- common/src/main/java/org/astraea/common/admin/AdminImpl.java
- common/src/main/java/org/astraea/common/partitioner/Dispatcher.java
> Cleanup unused helpers from Utils

- app/src/main/java/org/astraea/app/web/BeanHandler.java
- app/src/main/java/org/astraea/app/web/RecordHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/web/BeanHandlerTest.java
- app/src/test/java/org/astraea/app/web/RecordHandlerTest.java
- app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
- app/src/test/java/org/astraea/app/web/WebServiceTest.java
> [WEB] Make WebService and standalone class

- app/src/test/java/org/astraea/app/web/WebServiceTest.java
> [WEB] fix flaky WebServiceTest#testClose

- common/src/main/java/org/astraea/common/connector/ConnectorClient.java
- common/src/main/java/org/astraea/common/connector/PluginInfo.java
- common/src/main/java/org/astraea/common/connector/TaskInfo.java
- common/src/test/java/org/astraea/common/connector/ConnectorClientTest.java
- connector/src/test/java/org/astraea/connector/ConnectorTest.java
> [CONNECTOR] use connector client to rewrite ConnectorTest

- gui/src/main/java/org/astraea/gui/tab/SettingNode.java
- gui/src/test/java/org/astraea/gui/tab/SettingNodeTest.java
感謝 @g1geordie 提供方便的 json 轉換，我們現在可以將 setting 也透過 json 來存放
> [GUI] save setting by json

- gui/src/main/java/org/astraea/gui/Context.java
- gui/src/main/java/org/astraea/gui/Main.java
- gui/src/main/java/org/astraea/gui/tab/ConnectorNode.java
- gui/src/main/java/org/astraea/gui/tab/SettingNode.java
這隻PR新增簡單的GUI頁面來顯示 connector 資訊
> [GUI][CONNECTOR] add connector page

- app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
- docs/web_server/web_api_topics_chinese.md
> Fix Flaky `TopicHandlerTest#testWithWebService()`

- common/src/main/java/org/astraea/common/admin/ClusterBean.java
- common/src/main/java/org/astraea/common/admin/ClusterBeanQuery.java
- common/src/test/java/org/astraea/common/admin/ClusterBeanTest.java
Resolve #1112.
給 `ClusterBean` 添加函數 `ClusterBean#select`，可以寫一些常見的過濾條件
```java
var windowQuery =
clusterBean.query(
ClusterBeanQuery.window(MetricType1.class, 1)
.metricSince(500)
.metricQuantities(10)
.ascending());
```
* metrics 的形態
* 源自哪個節點
* metrics 從何時開始累計
* metrics 的數量
* metrics 以時間升冪/降冪排序
上面的項目中， metrics 數量有做特別檢查，如果最後過濾出來的 metrics 沒有滿足條件要求（節點效能指標數量不足），則會噴出 `NoSufficientMetricsException`
```java
Stream<HasBeanObject> random(int broker) {
return Stream.generate(
() -> {
final var domainName = "test";
final var properties =
Map.of(
"type", "testing",
"broker", String.valueOf(broker),
"name", "whatever");
final var attributes =
Map.<String, Object>of("value", ThreadLocalRandom.current().nextInt());
return new BeanObject(domainName, properties, attributes);
})
.map(
bean -> {
final var …
```
> Implementation of `ClusterBeanQuery`

- common/src/main/java/org/astraea/common/connector/Builder.java
- common/src/main/java/org/astraea/common/connector/ConnectorClient.java
- common/src/main/java/org/astraea/common/connector/ConnectorStatus.java
- common/src/main/java/org/astraea/common/connector/TaskStatus.java
- common/src/test/java/org/astraea/common/connector/ConnectorClientTest.java
- connector/src/test/java/org/astraea/connector/ConnectorTest.java
- gui/src/main/java/org/astraea/gui/tab/ConnectorNode.java
> [CONNECTOR] enable to fetch connector status

- fs/src/main/java/org/astraea/fs/FileSystem.java
- fs/src/main/java/org/astraea/fs/ftp/FtpFileSystem.java
- fs/src/main/java/org/astraea/fs/local/LocalFileSystem.java
- fs/src/test/java/org/astraea/fs/AbstractFileSystemTest.java
- fs/src/test/java/org/astraea/fs/FileSystemTest.java
related to https://github.com/skiptests/astraea/issues/1188#issuecomment-1337022058
這隻PR確保目前的 fs impl 都是執行緒安全
> [FS] Make file system be thread-safe

- common/src/main/java/org/astraea/common/connector/ConnectorClient.java
- common/src/main/java/org/astraea/common/connector/TaskInfo.java
- common/src/test/java/org/astraea/common/connector/ConnectorClientTest.java
- gui/src/main/java/org/astraea/gui/tab/ConnectorNode.java
> [GUI] enable to create connector and list task

- connector/build.gradle
- database/build.gradle
- docker/start_broker.sh
- docker/start_worker.sh
- fs/build.gradle
將 astraea connector 加到 worker image 裡面，如此就可以方便測試 astraea connector 功能，如下圖：
> [CONNECTOR] add astraea connector to worker

- common/src/test/java/org/astraea/common/connector/ConnectorClientTest.java
> [CONNECTOR] fix COnnectorClientTest.testUpdateConnector

- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
- common/src/main/java/org/astraea/common/balancer/algorithms/AlgorithmConfig.java
- common/src/main/java/org/astraea/common/balancer/algorithms/GreedyBalancer.java
- common/src/main/java/org/astraea/common/balancer/algorithms/SingleStepBalancer.java
- common/src/test/java/org/astraea/common/balancer/BalancerTest.java
- common/src/test/java/org/astraea/common/balancer/algorithms/AlgorithmConfigTest.java
- common/src/test/java/org/astraea/common/balancer/algorithms/GreedyBalancerTest.java
- gui/src/main/java/org/astraea/gui/tab/BalancerNode.java
> [WEB] tweak BalancerHandler

- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
移除`CostWeight`中用不到的程式碼、以及簡化取得 cost function 的邏輯
> [WEB] Refactor BalancerHandler#CostWeight

- app/src/main/java/org/astraea/app/App.java
- app/src/main/java/org/astraea/app/web/RecordHandler.java
- app/src/test/java/org/astraea/app/backup/ImportCsvTest.java
- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
- common/src/main/java/org/astraea/common/cost/ReplicaSizeCost.java
- common/src/test/java/org/astraea/common/DataRateTest.java
- common/src/test/java/org/astraea/common/LazyTest.java
- common/src/test/java/org/astraea/common/consumer/ConsumerTest.java
- common/src/test/java/org/astraea/common/http/HttpExecutorBuilderTest.java
- common/src/test/java/org/astraea/common/json/JsonConverterTest.java
- common/src/test/java/org/astraea/common/metrics/BeanQueryTest.java
- common/src/test/java/org/astraea/common/partitioner/DispatcherTest.java
- common/src/test/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobinDispatchTest.java
- connector/src/main/java/org/astraea/connector/SourceTask.java
- gui/src/main/java/org/astraea/gui/pane/Slide.java
- gui/src/main/java/org/astraea/gui/tab/topic/ReplicaNode.java
> Tweak code base

- common/src/main/java/org/astraea/common/metrics/connector/SourceMetrics.java
- common/src/main/java/org/astraea/common/metrics/connector/SourceTaskError.java
- common/src/main/java/org/astraea/common/metrics/connector/SourceTaskInfo.java
- connector/src/test/java/org/astraea/connector/perf/PerfConnectorTest.java
新增基於 source connector task 為目標的效能指標，並且搭配 perf connector 做測試
> [CONNECTOR] add source connector metrics

- gui/src/main/java/org/astraea/gui/button/SelectBox.java
- gui/src/main/java/org/astraea/gui/pane/MultiInput.java
- gui/src/main/java/org/astraea/gui/pane/PaneBuilder.java
- gui/src/main/java/org/astraea/gui/tab/BalancerNode.java
- gui/src/main/java/org/astraea/gui/tab/BrokerNode.java
- gui/src/main/java/org/astraea/gui/tab/ClientNode.java
- gui/src/main/java/org/astraea/gui/tab/ConnectorNode.java
- gui/src/main/java/org/astraea/gui/tab/QuotaNode.java
- gui/src/main/java/org/astraea/gui/tab/SettingNode.java
- gui/src/main/java/org/astraea/gui/tab/topic/PartitionNode.java
- gui/src/main/java/org/astraea/gui/tab/topic/ReplicaNode.java
- gui/src/main/java/org/astraea/gui/tab/topic/TopicNode.java
- gui/src/main/java/org/astraea/gui/text/TextInput.java
`MultiInput` 應該是 `PaneBuilder`內部使用的類別，各個頁面應該直接使用`TextInput`就足夠了
> [GUI] each node should not use MultiInput directly

- gui/src/main/java/org/astraea/gui/tab/SettingNode.java
- gui/src/test/java/org/astraea/gui/tab/SettingNodeTest.java
`Prop.equals`只有在測試中使用，所以移動到測試中
> [GUI] remove Prop.equals

- gui/src/main/java/org/astraea/gui/Context.java
- gui/src/main/java/org/astraea/gui/tab/BrokerNode.java
- gui/src/main/java/org/astraea/gui/tab/ConnectorNode.java
- gui/src/main/java/org/astraea/gui/tab/SettingNode.java
- gui/src/main/java/org/astraea/gui/tab/topic/TopicNode.java
- gui/src/test/java/org/astraea/gui/tab/SettingNodeTest.java
> [GUI] add source task metrics

- docker/etl.dockerfile
https://github.com/skiptests/astraea/pull/1174 不小心加入的檔案，現在移除
> remove etl.dockerfile

- docker/etl.dockerfile
- docker/start_etl.sh
- docker/start_spark.sh
> Upgradle spark version to 3.3.1 in start_spark.sh

- common/src/main/java/org/astraea/common/connector/ConnectorClient.java
- common/src/main/java/org/astraea/common/connector/ConnectorConfigs.java
- common/src/test/java/org/astraea/common/connector/ConnectorClientTest.java
- connector/src/test/java/org/astraea/connector/ConnectorTest.java
- connector/src/test/java/org/astraea/connector/SourceTest.java
- connector/src/test/java/org/astraea/connector/perf/PerfSinkTest.java
- connector/src/test/java/org/astraea/connector/perf/PerfSourceTest.java
- gui/src/main/java/org/astraea/gui/tab/ConnectorNode.java
> [CONNECTOR] add ConnectorConfigs

- docs/web_server/web_api_balancer_chinese.md
Context: https://github.com/skiptests/astraea/pull/1240#discussion_r1046646213
新增 Balancer API 使用的注意事項。
> Add API usage note to `web_api_balancer_chinese.md`

- common/src/main/java/org/astraea/common/connector/Builder.java
- common/src/main/java/org/astraea/common/connector/ConnectorClient.java
- common/src/main/java/org/astraea/common/connector/PluginInfo.java
- common/src/test/java/org/astraea/common/connector/ConnectorClientTest.java
- connector/src/main/java/org/astraea/connector/perf/PerfSource.java
- connector/src/test/java/org/astraea/connector/ConnectorTest.java
- gui/src/main/java/org/astraea/gui/tab/ConnectorNode.java
> [CONNECTOR] PluginInfo should carry definitions

- docs/dispatcher/README.md
- gradle.properties
> Change version from 0.0.1-SNAPSHOT to 0.1.0-SNAPSHOT

- common/src/main/java/org/astraea/common/connector/ConnectorConfigs.java
- connector/src/main/java/org/astraea/connector/SourceTask.java
- connector/src/test/java/org/astraea/connector/SourceTest.java
- docker/start_worker.sh
- gui/src/main/java/org/astraea/gui/tab/ConnectorNode.java
- it/src/main/java/org/astraea/it/Services.java
converter 相關的參數都設定回 kafka 預設值，並且在GUI上提醒使用者可以設定converter
> [CONNECTOR] add converter configs

- docker/start_etl.sh
> Upgradle Astraea version to 0.1.0 in start_etl.sh

- common/src/main/java/org/astraea/common/metrics/connector/ConnectorInfo.java
- common/src/main/java/org/astraea/common/metrics/connector/ConnectorMetrics.java
- connector/src/test/java/org/astraea/connector/perf/PerfSinkTest.java
- connector/src/test/java/org/astraea/connector/perf/PerfSourceTest.java
> [CONNECTOR] add connector info metrics

- common/src/main/java/org/astraea/common/balancer/algorithms/GreedyBalancer.java
- common/src/main/java/org/astraea/common/balancer/algorithms/SingleStepBalancer.java
- common/src/test/java/org/astraea/common/balancer/algorithms/GreedyBalancerTest.java
- common/src/test/java/org/astraea/common/balancer/algorithms/SingleStepBalancerTest.java
- docs/web_server/web_api_balancer_chinese.md
#1066 中把 `ShufflePlanGenerator` 的名稱改為 `ShuffleTweaker`
這個 PR 把 Balancer 的 `shuffle.plan.generator.*` 參數名稱改正為 `shuffle.tweaker.*`
> Rename Balancer config

- common/src/main/java/org/astraea/common/admin/ReplicaInfo.java
因為有實作`equals`，對應的`hashCode`也應該要提供
> Add ReplicaInfo#hashCode

- docker/start_spark.sh
> [SPARK] enable to mount host folder on spark master/worker container

- connector/src/main/java/org/astraea/connector/MetadataStorage.java
- connector/src/main/java/org/astraea/connector/SourceTask.java
- connector/src/main/java/org/astraea/connector/perf/PerfSource.java
- connector/src/test/java/org/astraea/connector/ConnectorTest.java
- connector/src/test/java/org/astraea/connector/MetadataStorageTest.java
- connector/src/test/java/org/astraea/connector/SourceDataTest.java
- connector/src/test/java/org/astraea/connector/perf/PerfSourceTest.java
> [CONNECTOR] add MetadataStorage to SourceTask

- gui/src/main/java/org/astraea/gui/tab/ConnectorNode.java
- gui/src/main/java/org/astraea/gui/table/TableViewer.java
> [GUI] enable to display documentation and wrap the long line

- connector/src/main/java/org/astraea/connector/perf/PerfSource.java
- connector/src/test/java/org/astraea/connector/perf/PerfSourceTest.java
> [PERF][CONNECTOR] support to define specify partitions to send records

- connector/src/main/java/org/astraea/connector/perf/PerfSource.java
> [PERF] add documentation for key.length/value.length

- connector/src/main/java/org/astraea/connector/backup/Exporter.java
- connector/src/test/java/org/astraea/connector/backup/ExporterTest.java
我在 #1290 做了一件蠢事，正確的名字應該是`Exporter`但我寫成`Importer`...
> [BACKUP] fix incorrect rename caused by #1290

- app/build.gradle
- common/build.gradle
- connector/build.gradle
- database/build.gradle
- etl/build.gradle
- fs/build.gradle
- gradle/dependencies.gradle
- gui/build.gradle
- it/build.gradle
新增一個檔案統一描述各個 dependencies，其他`build.gradle`就可以共用相同版本
> Unify dependencies

- common/src/test/java/org/astraea/common/metrics/stats/RateTest.java
- connector/src/main/java/org/astraea/connector/perf/PerfSource.java
- connector/src/test/java/org/astraea/connector/perf/PerfSourceTest.java
> Rewrite Rate.of to apply DataSize

- gui/src/main/java/org/astraea/gui/tab/topic/TopicNode.java
這方便我們快速查看關聯到 topic 的 producer states
> [GUI] Topic tag should include number of producer id

- common/src/main/java/org/astraea/common/admin/AdminImpl.java
- common/src/test/java/org/astraea/common/admin/AdminWithOfflineBrokerTest.java
如題，我們盡量避免 offline nodes 影響 APIs的運作
> Admin#producerStates get stuck if there are offline nodes

- connector/src/main/java/org/astraea/connector/Definition.java
- connector/src/main/java/org/astraea/connector/SinkConnector.java
- connector/src/main/java/org/astraea/connector/SourceConnector.java
- connector/src/test/java/org/astraea/connector/DefinitionTest.java
> [CONNECTOR] add required setter to create required argument

- connector/src/main/java/org/astraea/connector/backup/Exporter.java
- connector/src/test/java/org/astraea/connector/backup/ExporterTest.java
https://github.com/skiptests/astraea/issues/1297 
https://github.com/skiptests/astraea/issues/1299
有為sink connector 參數增添說明，並且把必要參數需求在init就先確認過，在缺失參數時以提早報錯。 關於time參數應該會在之後的針對時間刷新檔案的時候一併增加。
> [CONNECTOR] Add exporter definition

- docker/start_etl.sh
> Add check etl

- docs/performance_benchmark.md
related https://github.com/skiptests/astraea/pull/1340#issue-1510326052
突然想起忘記把 throttle 功能加入說明文件中，故此 PR 把 throttle 功能說明加入 performance tool 的說明文件中
> 將 throttle 功能說明加入 performance docs 內

- docs/connector/exporter.md
- docs/gui/connector/README.md
fix #1375 
在文件中新增提醒以避免因使用到 Kafka 預設之 json converter使 backup 工具出錯
> [BACKUP] update docs for reminding the converter

- docs/run_prometheus.md
resolve https://github.com/skiptests/astraea/issues/1347#issuecomment-1368203700
此 PR 新增 node_exporter 文件連結到 prometheus 文件中
> add the link of node_exporter readme into prometheus readme

- gradle.properties
> Update version from 0.1.0-SNAPSHOT to 0.1.0

- gradle.properties
> Update version from 0.1.0 to 0.2.0-SNAPSHOT

- docs/web_server/web_api_balancer_chinese.md
* 提及目前支援的 Cost Functions
* 提及 Network Cost 的使用注意事項
* 因為 ReplicaSizeCost 的問題還沒修好(#1333)，暫時將他從文件範例中移除
> [WEB] Revise balancer documentation

- common/src/main/java/org/astraea/common/balancer/algorithms/GreedyBalancer.java
- common/src/main/java/org/astraea/common/metrics/MBeanRegister.java
- common/src/main/java/org/astraea/common/partitioner/StrictCostDispatcher.java
- common/src/test/java/org/astraea/common/metrics/MBeanRegisterTest.java
- common/src/test/java/org/astraea/common/partitioner/StrictCostDispatcherPerfTest.java
- common/src/test/java/org/astraea/common/partitioner/StrictCostDispatcherTest.java
新增測試確認`StrictCostDispatcher` 可以反應基本的延遲變化
> [DISPATCHER] add more tests for StrictCostDispatcher

- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
- common/src/main/java/org/astraea/common/FutureUtils.java
- common/src/main/java/org/astraea/common/admin/AdminImpl.java
- common/src/main/java/org/astraea/common/admin/ClusterInfo.java
- common/src/main/java/org/astraea/common/admin/ClusterInfoBuilder.java
- common/src/main/java/org/astraea/common/function/Bi6Function.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
- common/src/test/java/org/astraea/common/admin/ClusterInfoBuilderTest.java
- common/src/test/java/org/astraea/common/admin/ClusterInfoTest.java
- common/src/test/java/org/astraea/common/balancer/FakeClusterInfo.java
- common/src/test/java/org/astraea/common/cost/ReplicaLeaderCostTest.java
- common/src/test/java/org/astraea/common/cost/ReplicaNumberCostTest.java
- common/src/test/java/org/astraea/common/cost/ReplicaSizeCostTest.java
- common/src/test/java/org/astraea/common/partitioner/StrictCostDispatcherPerfTest.java
- common/src/test/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobinDispatchTest.java
- common/src/test/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobinTest.java
- gui/src/test/java/org/astraea/gui/tab/BalancerNodeTest.java
- gui/src/test/java/org/astraea/gui/tab/topic/ReplicaNodeTest.java
如題，這方便幫助我們面對多叢集的時候分類 ClusterInfo
> [COMMON] add cluster id to ClusterInfo

- app/src/main/java/org/astraea/app/argument/Argument.java
- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/AdminConfigs.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
> [COMMON] add AdminConfigs

- app/src/main/java/org/astraea/app/web/RecordHandler.java
- common/src/main/java/org/astraea/common/Cache.java
- common/src/test/java/org/astraea/common/CacheTest.java
如題，這方便使用者用更多種用途，尤其是可以接受暫時沒有快取的時候
> [COMMON] add get/require method to Cache

- common/src/main/java/org/astraea/common/cost/HasPartitionCost.java
- common/src/main/java/org/astraea/common/cost/ReplicaSizeCost.java
> [COST] replace ReplicaInfo by Replica for HasPartitionCost

- app/src/main/java/org/astraea/app/performance/Performance.java
- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- app/src/main/java/org/astraea/app/web/ReassignmentHandler.java
- app/src/test/java/org/astraea/app/performance/PerformanceTest.java
- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/ClusterInfo.java
- common/src/main/java/org/astraea/common/balancer/executor/StraightPlanExecutor.java
- common/src/main/java/org/astraea/common/balancer/tweakers/ShuffleTweaker.java
- common/src/main/java/org/astraea/common/cost/NetworkCost.java
- common/src/main/java/org/astraea/common/cost/ReplicaLeaderCost.java
- common/src/main/java/org/astraea/common/partitioner/StrictCostDispatcher.java
- common/src/main/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobin.java
- common/src/main/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobinDispatcher.java
- common/src/test/java/org/astraea/common/admin/AdminWithOfflineBrokerTest.java
- common/src/test/java/org/astraea/common/admin/ClusterInfoBuilderTest.java
- common/src/test/java/org/astraea/common/admin/ClusterInfoTest.java
- common/src/test/java/org/astraea/common/admin/ClusterInfoWithOfflineNodeTest.java
- common/src/test/java/org/astraea/common/balancer/BalancerTest.java
- common/src/test/java/org/astraea/common/cost/NetworkCostTest.java
- common/src/test/java/org/astraea/common/cost/ReplicaLeaderCostTest.java
- common/src/test/java/org/astraea/common/cost/ReplicaSizeCostTest.java
- common/src/test/java/org/astraea/common/partitioner/StrictCostDispatcherTest.java
- common/src/test/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobinDispatchTest.java
- common/src/test/java/org/astraea/common/partitioner/smooth/SmoothWeightRoundRobinTest.java
- gui/src/main/java/org/astraea/gui/tab/BalancerNode.java
related to #1403
由於`Assignor`還無法使用`Replica`，因此這隻PR還沒有移除`ReplicaInfo`
> [COMMON] Replace ReplicaInfo by Replica for test scope

- docker/start_etl.sh
checkpoint目錄得分開掛載，不然只能放在source下，遞歸讀取會讀取到checkpoint裡面的資料。
> [ETL]add checkpoint_path in start_stl.sh

- common/src/main/java/org/astraea/common/admin/ClusterInfo.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
> [COMMON] add ClusterInfo#brokers

- docs/connector/exporter.md
#1300 
已在 doc 中增加對於 `roll.duration` 相關之說明
> [BACKUP] Update the doc about Exporter 

- gui/src/main/java/org/astraea/gui/tab/topic/TopicNode.java
- gui/src/test/java/org/astraea/gui/tab/topic/TopicNodeTest.java
> [GUI] add empty topic to health page

- common/src/main/java/org/astraea/common/producer/Record.java
- gui/src/main/java/org/astraea/gui/tab/ClientNode.java
- gui/src/test/java/org/astraea/gui/tab/ClientNodeTest.java
如上圖，可以看到 assignor = range 和 state = STABLE
> [GUI] enbale to show assignor and state of consumer group

- common/src/main/java/org/astraea/common/admin/Admin.java
- common/src/main/java/org/astraea/common/admin/TopicChecker.java
- common/src/test/java/org/astraea/common/admin/TopicCheckerTest.java
> [COMMON] add more topic checkers

- common/src/main/java/org/astraea/common/admin/TopicChecker.java
- common/src/test/java/org/astraea/common/admin/TopicCheckerTest.java
- gui/src/main/java/org/astraea/gui/Main.java
- gui/src/main/java/org/astraea/gui/tab/health/BalancerNode.java
- gui/src/main/java/org/astraea/gui/tab/health/HealthNode.java
- gui/src/main/java/org/astraea/gui/tab/topic/PartitionNode.java
- gui/src/main/java/org/astraea/gui/tab/topic/ReplicaNode.java
- gui/src/main/java/org/astraea/gui/tab/topic/TopicNode.java
- gui/src/main/java/org/astraea/gui/table/TableViewer.java
- gui/src/test/java/org/astraea/gui/tab/health/BalancerNodeTest.java
- gui/src/test/java/org/astraea/gui/tab/health/HealthNodeTest.java
這隻 PR 將 balancer 和 health 獨立成一個 tag，並且在 health basic 中新增更多屬性（如下圖）
> Add health page

- common/src/main/java/org/astraea/common/Lazy.java
- common/src/main/java/org/astraea/common/partitioner/Dispatcher.java
- common/src/main/java/org/astraea/common/partitioner/RoundRobinKeeper.java
- common/src/main/java/org/astraea/common/partitioner/SmoothWeightCal.java
- common/src/main/java/org/astraea/common/partitioner/SmoothWeightRoundRobinDispatcher.java
- common/src/main/java/org/astraea/common/partitioner/StrictCostDispatcher.java
- common/src/test/java/org/astraea/common/LazyTest.java
- common/src/test/java/org/astraea/common/partitioner/StrictCostDispatcherTest.java
> [DISPATCHER] tweak Dispatcher

- common/src/main/java/org/astraea/common/metrics/client/admin/AdminMetrics.java
- common/src/main/java/org/astraea/common/metrics/client/consumer/ConsumerMetrics.java
- common/src/main/java/org/astraea/common/metrics/client/producer/ProducerMetrics.java
> [COMMON] remove unused variables

- common/src/main/java/org/astraea/common/cost/HasMoveCost.java
- common/src/test/java/org/astraea/common/cost/MoveCostTest.java
在合併多個`HasMoveCost`時，也應該要同合併`Fetcher`，否則會沒辦法抓metrics
> fix `HasMoveCost#of`

- common/src/main/java/org/astraea/common/admin/ClusterBean.java
> [COMMON] add ClusterBean#brokerIds and ClusterBean#brokerMetrics

- docker/start_broker.sh
- docker/start_worker.sh
- gradle/dependencies.gradle
> [DEP] Upgrade kafka from 3.3.1 to 3.3.2

- README.md
> [DOC] add 2022 party to README

- common/src/main/java/org/astraea/common/cost/BrokerInputCost.java
- common/src/main/java/org/astraea/common/cost/BrokerOutputCost.java
- common/src/main/java/org/astraea/common/cost/CostFunction.java
- common/src/main/java/org/astraea/common/cost/CpuCost.java
- common/src/main/java/org/astraea/common/cost/HasBrokerCost.java
- common/src/main/java/org/astraea/common/cost/HasClusterCost.java
- common/src/main/java/org/astraea/common/cost/HasMoveCost.java
- common/src/main/java/org/astraea/common/cost/HasPartitionCost.java
- common/src/main/java/org/astraea/common/cost/LoadCost.java
- common/src/main/java/org/astraea/common/cost/MemoryCost.java
- common/src/main/java/org/astraea/common/cost/NetworkCost.java
- common/src/main/java/org/astraea/common/cost/NetworkEgressCost.java
- common/src/main/java/org/astraea/common/cost/NetworkIngressCost.java
- common/src/main/java/org/astraea/common/cost/NeutralIntegratedCost.java
- common/src/main/java/org/astraea/common/cost/NodeLatencyCost.java
- common/src/main/java/org/astraea/common/cost/NodeThroughputCost.java
- common/src/main/java/org/astraea/common/cost/RecordSizeCost.java
- common/src/main/java/org/astraea/common/cost/ReplicaLeaderCost.java
- common/src/main/java/org/astraea/common/cost/ReplicaLeaderSizeCost.java
- common/src/main/java/org/astraea/common/cost/ReplicaNumberCost.java
> [COST] Provide `Object#toString` implementation for CostFunctions

- docker/start_zookeeper.sh
- gradle/dependencies.gradle
> [COMMON] upgrade zookeeper from 3.8.0 to 3.8.1

- app/src/main/java/org/astraea/app/performance/Report.java
- app/src/main/java/org/astraea/app/web/BeanHandler.java
- common/src/main/java/org/astraea/common/metrics/MBeanClient.java
- common/src/main/java/org/astraea/common/metrics/broker/ControllerMetrics.java
- common/src/main/java/org/astraea/common/metrics/broker/LogMetrics.java
- common/src/main/java/org/astraea/common/metrics/broker/NetworkMetrics.java
- common/src/main/java/org/astraea/common/metrics/broker/ServerMetrics.java
- common/src/main/java/org/astraea/common/metrics/client/admin/AdminMetrics.java
- common/src/main/java/org/astraea/common/metrics/client/consumer/ConsumerMetrics.java
- common/src/main/java/org/astraea/common/metrics/client/producer/ProducerMetrics.java
- common/src/main/java/org/astraea/common/metrics/connector/ConnectorMetrics.java
- common/src/main/java/org/astraea/common/metrics/platform/HostMetrics.java
- common/src/test/java/org/astraea/common/balancer/algorithms/GreedyBalancerTest.java
- common/src/test/java/org/astraea/common/cost/NodeLatencyCostTest.java
- common/src/test/java/org/astraea/common/cost/NodeThroughputCostTest.java
- common/src/test/java/org/astraea/common/metrics/MBeanClientTest.java
- common/src/test/java/org/astraea/common/metrics/MBeanRegisterTest.java
- common/src/test/java/org/astraea/common/metrics/collector/MetricCollectorTest.java
`MBeanClient`是我們索取metrics的介面，為了之後可以串接其他 metrics source (例如 #1369)，因此有必要將介面做更通用的簡化
> [COMMON] simplify MBeanClient

- docs/run_kafka_broker.md
> [DOC] add zk doc link to broker doc

- docs/build_project.md
fix #1482
修改 doc 的 gui jar 檔名呈現方式
> [DOC] Make clear of gui jar file name in build_project

- docker/start_hadoop.sh
如題，HDFS中還有 RPC 和 HTTP 兩個服務需要指定正確的 hostname
> [HDFS] Make rpc and http service use correct hostname

- docker/start_broker.sh
- docker/start_worker.sh
- gradle/dependencies.gradle
> [COMMON] upgrade kafka from 3.3.2 to 3.4.0

- common/src/main/java/org/astraea/common/metrics/AppInfo.java
- common/src/main/java/org/astraea/common/metrics/broker/ServerMetrics.java
- common/src/main/java/org/astraea/common/metrics/client/consumer/ConsumerMetrics.java
- common/src/main/java/org/astraea/common/metrics/client/producer/ProducerMetrics.java
> [METRICS] unify AppInfo

- gui/src/main/java/org/astraea/gui/tab/BrokerNode.java
> [GUI] add memory to BrokerNode

- common/src/main/java/org/astraea/common/balancer/Balancer.java
- common/src/main/java/org/astraea/common/balancer/algorithms/GreedyBalancer.java
- common/src/main/java/org/astraea/common/balancer/algorithms/SingleStepBalancer.java
- common/src/test/java/org/astraea/common/balancer/BalancerConsoleTest.java
- common/src/test/java/org/astraea/common/balancer/BalancerTest.java
as title
這方便下游應用只保存 plan 就可以知道當時使用的 cluster info
> [BALANCER] add init cluster info to Balancer.Plan

- common/src/main/java/org/astraea/common/json/JsonConverter.java
> [JSON] remove debug code

- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
> [TEST] Fix flaky BalancerHandlerTest.testSubmitRebalancePlanThreadSafe

- common/build.gradle
- common/src/test/java/org/astraea/common/csv/CsvReaderTest.java
- common/src/test/java/org/astraea/common/csv/CsvWriterTest.java
- common/src/test/java/org/astraea/common/partitioner/DispatcherTest.java
- etl/src/main/scala/org/astraea/etl/Metadata.scala
- etl/src/main/scala/org/astraea/etl/Spark2Kafka.scala
- etl/src/main/scala/org/astraea/etl/Utils.scala
- etl/src/test/scala/org/astraea/etl/DataFrameProcessorTest.scala
- etl/src/test/scala/org/astraea/etl/FileCreator.scala
- etl/src/test/scala/org/astraea/etl/MetadataTest.scala
- etl/src/test/scala/org/astraea/etl/Spark2KafkaTest.scala
- fs/src/main/java/org/astraea/fs/local/LocalFileSystem.java
- fs/src/test/java/org/astraea/fs/AbstractFileSystemTest.java
- gui/src/main/java/org/astraea/gui/tab/SettingNode.java
- it/src/main/java/org/astraea/it/BrokerCluster.java
- it/src/main/java/org/astraea/it/Database.java
- it/src/main/java/org/astraea/it/FtpServer.java
- it/src/main/java/org/astraea/it/HdfsServer.java
- it/src/main/java/org/astraea/it/Utils.java
- it/src/main/java/org/astraea/it/ZookeeperCluster.java
一個小改善，將過時的`java.io.File`都用nio2改寫
> [COMMON] replace java.io.File by nio 2

- common/src/main/java/org/astraea/common/cost/BrokerCost.java
- common/src/main/java/org/astraea/common/cost/HasBrokerCost.java
- common/src/main/java/org/astraea/common/cost/NeutralIntegratedCost.java
- common/src/main/java/org/astraea/common/cost/Normalizer.java
- common/src/test/java/org/astraea/common/cost/BrokerCostTest.java
- common/src/test/java/org/astraea/common/cost/NormalizerTest.java
> [COMMON] remove BrokerCost#normalize

- common/src/main/java/org/astraea/common/admin/AdminImpl.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
https://github.com/skiptests/astraea/blob/a78bf0095fe2ef6c20746d02cae9fdbc1adfc27f/common/src/main/java/org/astraea/common/admin/AdminImpl.java#L1001-L1005
`Admin#declarePreferredFolders` 會對接受的 `Map<TopicPartitionReplica, String> assignment` 做過濾，所有 assignment 中真的存在的 replica 會被過濾掉。避免後面呼叫 `Admin#moveToFolders()` 的時候不小心觸發搬移。
https://github.com/skiptests/astraea/blob/a78bf0095fe2ef6c20746d02cae9fdbc1adfc27f/common/src/main/java/org/astraea/common/admin/AdminImpl.java#L1009-L1015
同時在 PRC 做完之後要確保某個特定的錯誤被丟出。
https://github.com/skiptests/astraea/blob/a78bf0095fe2ef6c20746d02cae9fdbc1adfc27f/common/src/main/java/org/astraea/common/admin/AdminImpl.java#L1001-L1006
但如果傳入 assignment  的每個 TopicPartitionReplica 都是目前存在的，則所有的項目都會被 filter 過濾。而後面的`Admin#moveToFolders()` 會傳入一個空的 map。由於預期丟出的錯誤只有在 map …
> [COMMON] Fix `Admin#declarePreferredFolders` raising an exception when no cross-broker movement

- gui/src/main/java/org/astraea/gui/tab/ConnectorNode.java
- gui/src/main/java/org/astraea/gui/table/TableViewer.java
之前將文件放在表格內會不好閱讀，因此改成用浮動視窗的方式來呈現文件
> [GUI][CONNECTOR] use tip to display documentation of connector plugins

- docker/start_broker.sh
- docker/start_worker.sh
- docker/start_zookeeper.sh
- docs/run_kafka_broker.md
- docs/run_kafka_worker.md
- docs/run_zookeeper.md
> [SCRIPT] cleanup confluent setup

- common/src/main/java/org/astraea/common/metrics/collector/LocalMetricCollector.java
- common/src/test/java/org/astraea/common/metrics/collector/MetricCollectorTest.java
resolve https://github.com/skiptests/astraea/issues/1535#issue-1608506791
> fix LocalMetricCollector registerJMX

- .gitignore
- docker/docker_build_common.sh
- docker/start_controller.sh
- docs/run_kafka_broker.md
related to #1537
如題，我們將支援 zk and Kraft 兩種模式，使用者可自由決定要部署在哪一種服務上面
> [SCRIPT] support to run broker with kraft

- gradle/wrapper/gradle-wrapper.properties
- gradlew
> [COMMON] upgrade gradle from 8.0.1 to 8.0.2

- common/src/main/java/org/astraea/common/backup/RecordWriter.java
- common/src/main/java/org/astraea/common/backup/RecordWriterBuilder.java
- connector/src/main/java/org/astraea/connector/backup/Exporter.java
> [CONNECTOR] Writer will not close all other when exceeds the roll.duration

- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- common/src/main/java/org/astraea/common/Utils.java
- common/src/main/java/org/astraea/common/assignor/Assignor.java
- common/src/main/java/org/astraea/common/partitioner/StrictCostPartitioner.java
- common/src/test/java/org/astraea/common/UtilsTest.java
> [COMMON] revise Utils#costFunctions

- connector/src/main/java/org/astraea/connector/backup/Exporter.java
移除當初測試所輸出的 message
順便希望可以更新 worker image，現在的版本在超過 size 時會出現問題，這問題在前一段時間以修復
> [CONNECTOR] Remove unnecessary output message

- common/src/main/java/org/astraea/common/Configuration.java
- common/src/test/java/org/astraea/common/ConfigurationTest.java
resolve https://github.com/skiptests/astraea/pull/1524#discussion_r1133198915
> Add Duration into Configuration

- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
- common/src/main/java/org/astraea/common/cost/RecordSizeCost.java
- common/src/main/java/org/astraea/common/cost/ReplicaLeaderCost.java
- common/src/main/java/org/astraea/common/cost/ReplicaLeaderSizeCost.java
- common/src/main/java/org/astraea/common/cost/ReplicaNumberCost.java
- docs/web_server/web_api_balancer_chinese.md
#1573 更新move cost constraint參數的命名方式
> update move cost constraint config keys

- fs/src/main/java/org/astraea/fs/local/LocalFileSystem.java
> [COMMON] delete unused log from LocalFilesSystem.java

- common/src/test/java/org/astraea/common/metrics/collector/MetricSensorTest.java
related https://github.com/skiptests/astraea/pull/1569
修改此 MetricSensor 中的 Consumer 邏輯時，忘記修改了測試中的 exception 判斷，故此 PR 修復這個問題，不好意思
> Fix MetricSensor test

- common/src/main/java/org/astraea/common/consumer/TopicsBuilder.java
> [CONSUMER] Remove redundant debug message

- common/src/main/java/org/astraea/common/assignor/Assignor.java
- common/src/main/java/org/astraea/common/metrics/collector/InternalTopicCollector.java
- common/src/main/java/org/astraea/common/metrics/collector/LocalMetricCollector.java
- common/src/main/java/org/astraea/common/metrics/collector/MetricCollector.java
- common/src/main/java/org/astraea/common/partitioner/SmoothWeightRoundRobinPartitioner.java
- common/src/main/java/org/astraea/common/partitioner/StrictCostPartitioner.java
- common/src/test/java/org/astraea/common/cost/BrokerInputCostTest.java
- common/src/test/java/org/astraea/common/cost/MemoryCostTest.java
- common/src/test/java/org/astraea/common/metrics/collector/AbstractMetricCollectorTest.java
- common/src/test/java/org/astraea/common/metrics/collector/LocalMetricCollectorTest.java
- common/src/test/java/org/astraea/common/partitioner/StrictCostPartitionerTest.java
> [METRICS] revise signature of metrics collector

- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
- common/src/main/java/org/astraea/common/DataSize.java
- common/src/main/java/org/astraea/common/metrics/MBeanClient.java
- common/src/main/java/org/astraea/common/metrics/collector/InternalTopicCollector.java
- common/src/main/java/org/astraea/common/metrics/collector/MetricsFetcher.java
- common/src/main/java/org/astraea/common/metrics/collector/MetricsStore.java
- common/src/test/java/org/astraea/common/metrics/MBeanClientTest.java
- common/src/test/java/org/astraea/common/metrics/collector/LocalMetricsTest.java
- common/src/test/java/org/astraea/common/metrics/collector/MetricsFetcherTest.java
as title
先用我們的 first class - balancer 來試試看新的 metrics
> [BALANCER] use new metrics store

- connector/src/main/java/org/astraea/connector/backup/Exporter.java
在之前跑較大型資料的備份時，會因為沒有設定 recordsQueue 上限，而導致 heap 的 oom 發生。
因此在這邊有增加一個新的參數 `records.queue.number` 讓使用者可以自訂 recordsQueue 的大小，並且將原本使用 addAll 的地方變更為 put 方法， 以避免放入資料超過大小上限而導致Exception的發生。
同時在 Writer 中有修改從 recordsQueue 中存取資料的方式，試著讓效率可以稍微增加
下圖片可以是將 `records.queue.number` 設定為 100000 的情況，基本不會碰到 worker 預設的 2G heap 上限，因此沒有發生 oom 的情況。
之前有另外做變更 recordsQueue 不同上限的實驗，基本 worker 以專案預設的情況下來說，將 queue 大小設定為 150000 是相對極限的狀況，有時可能會碰到 2GB 的上限，但基本可以順利完成 500GB 的資料備份
> [CONNECTOR] Reducing stress on exporter heap

- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- app/src/main/java/org/astraea/app/web/BeanHandler.java
- app/src/main/java/org/astraea/app/web/WebService.java
- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
- app/src/test/java/org/astraea/app/web/BeanHandlerTest.java
- app/src/test/java/org/astraea/app/web/TopicHandlerTest.java
- app/src/test/java/org/astraea/app/web/WebServiceTest.java
- common/src/main/java/org/astraea/common/assignor/Assignor.java
- common/src/main/java/org/astraea/common/metrics/collector/MetricsFetcher.java
- common/src/main/java/org/astraea/common/metrics/collector/MetricsStore.java
- common/src/test/java/org/astraea/common/assignor/AssignorTest.java
- common/src/test/java/org/astraea/common/metrics/collector/LocalMetricsTest.java
- common/src/test/java/org/astraea/common/metrics/collector/MetricsFetcherTest.java
考量更新時串接的 API 都是非同步的，所以改成非同步的介面
fix #1609 #1611
> [METRICS] use CompletionStage for client supplier

- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- common/src/main/java/org/astraea/common/assignor/Assignor.java
- common/src/main/java/org/astraea/common/metrics/collector/MetricsStore.java
- common/src/main/java/org/astraea/common/partitioner/SmoothWeightRoundRobinPartitioner.java
- common/src/main/java/org/astraea/common/partitioner/StrictCostPartitioner.java
- common/src/test/java/org/astraea/common/assignor/AssignorTest.java
- common/src/test/java/org/astraea/common/partitioner/StrictCostPartitionerPerfTest.java
- common/src/test/java/org/astraea/common/partitioner/StrictCostPartitionerTest.java
> [PARTITIONER] replace metrics collector by metrics store

- docs/build_project.md
- gradle.properties
> [RELEASE] 0.3.0-SNAPSHOT

- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
- common/src/main/java/org/astraea/common/balancer/BalancerConsoleImpl.java
重寫 `BalancerHandlerTest#testRebalanceDetectOngoing`
> [TEST] fix flaky `BalancerHandlerTest#testRebalanceDetectOngoing`

- common/src/main/java/org/astraea/common/metrics/stats/Rate.java
- common/src/main/java/org/astraea/common/producer/RecordGenerator.java
- common/src/test/java/org/astraea/common/cost/NetworkIngressCostTest.java
- common/src/test/java/org/astraea/common/metrics/stats/RateTest.java
- common/src/test/java/org/astraea/common/producer/ProducerTest.java
- common/src/test/java/org/astraea/common/producer/RecordGeneratorTest.java
- connector/src/main/java/org/astraea/connector/perf/PerfSource.java
- connector/src/test/java/org/astraea/connector/perf/PerfSourceTest.java
> [PERF] adopt RecordGenerator

- docker/start_hadoop.sh
resolve #1636 
增加可以指定 datanode 儲存位置的功能。
> [SCRIPT] add support for DATA_FOLDERS in start_hadoop.sh

- app/src/main/java/org/astraea/app/performance/Performance.java
- app/src/main/java/org/astraea/app/web/QuotaHandler.java
- app/src/test/java/org/astraea/app/argument/DataRateFieldTest.java
- app/src/test/java/org/astraea/app/argument/TopicPartitionDataRateMapFieldTest.java
- app/src/test/java/org/astraea/app/web/ThrottleHandlerTest.java
- common/src/main/java/org/astraea/common/DataRate.java
- common/src/main/java/org/astraea/common/DataSize.java
- common/src/main/java/org/astraea/common/cost/NetworkCost.java
- common/src/test/java/org/astraea/common/DataRateTest.java
- common/src/test/java/org/astraea/common/DataSizeTest.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
- common/src/test/java/org/astraea/common/cost/NetworkCostTest.java
- common/src/test/java/org/astraea/common/cost/NetworkIngressCostTest.java
- common/src/test/java/org/astraea/common/producer/RecordGeneratorTest.java
- gui/src/main/java/org/astraea/gui/tab/QuotaNode.java
移除大量沒有在使用的方法，並且把預設的時間都設定成 "1 second"
> [COMMON] refactor DataRate

- common/src/main/java/org/astraea/common/ByteUtils.java
- common/src/main/java/org/astraea/common/consumer/Deserializer.java
- common/src/main/java/org/astraea/common/producer/Serializer.java
- common/src/test/java/org/astraea/common/ByteUtilsTest.java
> [SERIALIZATION] use ByteUtils to replace kafka seralizer/deserializer

- docker/start_app.sh
如題，`latest`已經是個常用的預設標籤，我們應給從善如流
> [DOCKER] use "latest" instead of "main"

- docker/build_deps_image.sh
#1655 移除了 sql 相關的功能，因此這些函式庫都用不到了，移除他們以降低映像檔的容量
> [DOCKER] remove libraries used by MySQL

- build.gradle
- common/src/main/java/org/astraea/common/metrics/MBeanClient.java
- common/src/test/java/org/astraea/common/metrics/MBeanClientTest.java
- connector/build.gradle
- docker/build_deps_image.sh
- docker/start_hadoop.sh
- docker/start_spark.sh
- etl/build.gradle
- gradle/dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gui/build.gradle
如題，更新 jar 以及 docker image 內置的版本
> [COMMON] update all dependencies

- common/src/main/java/org/astraea/common/ByteUtils.java
- common/src/main/java/org/astraea/common/backup/RecordReaderBuilder.java
- common/src/main/java/org/astraea/common/backup/RecordWriterBuilder.java
- common/src/main/proto/org/astraea/common/generated/Record.proto
Related #1581 
這隻 PR 取代原來的手刻序列化 `Record`，使用 protobuf 來實現。
> [SERIALIZATION] Serialize record by protobuf

- gradle/wrapper/gradle-wrapper.properties
- gradlew
> [COMMON] upgrade gradle from 8.1.0 to 8.1.1

- app/src/main/java/org/astraea/app/performance/ConsumerThread.java
- app/src/main/java/org/astraea/app/performance/ProducerThread.java
- app/src/main/java/org/astraea/app/performance/ReportFormat.java
- app/src/main/java/org/astraea/app/web/WebService.java
- common/src/main/java/org/astraea/common/Utils.java
- common/src/main/java/org/astraea/common/csv/CsvReaderBuilder.java
- common/src/main/java/org/astraea/common/csv/CsvWriterBuilder.java
- common/src/main/java/org/astraea/common/metrics/MBeanClient.java
- common/src/main/java/org/astraea/common/metrics/collector/MetricFetcher.java
- common/src/main/java/org/astraea/common/partitioner/Partitioner.java
- common/src/test/java/org/astraea/common/UtilsTest.java
- connector/src/main/java/org/astraea/connector/backup/Importer.java
- fs/src/main/java/org/astraea/fs/hdfs/HdfsFileSystem.java
這個方法允許使用者關閉任何物件，並且保證只有該物件是可關閉時才啟動。
> [COMMON] add Utils#close

- app/build.gradle
- common/build.gradle
- connector/build.gradle
- docker/build_deps_image.sh
- docker/start_app.sh
- docker/start_broker.sh
- docker/start_controller.sh
- docker/start_hadoop.sh
- docker/start_spark.sh
- docker/start_worker.sh
- docker/start_zookeeper.sh
- etl/build.gradle
- fs/build.gradle
- gui/build.gradle
- it/build.gradle
> [COMMON] upgrade jdk from 11 to 17

- app/src/main/java/org/astraea/app/web/WebService.java
- docker/start_app.sh
兩個修改：
1. app要否運行在背景/前景改成參數控制
2. 提早檢查 jmx port 的設定
> [WEB] run web service foreground by default

- common/src/main/java/org/astraea/common/balancer/Balancer.java
- common/src/main/java/org/astraea/common/balancer/algorithms/GreedyBalancer.java
- common/src/main/java/org/astraea/common/balancer/algorithms/SingleStepBalancer.java
- common/src/test/java/org/astraea/common/balancer/BalancerConsoleTest.java
- gui/src/main/java/org/astraea/gui/tab/health/BalancerNode.java
- gui/src/test/java/org/astraea/gui/tab/health/BalancerNodeTest.java
> [BALANCER] remove MoveCost from Plan

- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
fix  #1701
產生的搬移計畫不一定會移動到每一個broker，因此不檢查每個broker是否都有移動資料
> fix BalancerHandlerTest#testReport

- common/src/main/java/org/astraea/common/assignor/Assignor.java
resolve https://github.com/skiptests/astraea/issues/1694#issue-1692928248
目前 assignor 會使用 `admin` 與 `MetricStore` 來取得足夠的資訊來分配 partition，但是分配後不會將 `admin` 與 `MetricStore` 釋放
故此 PR 用來解決 Astraea assignor 不會釋放資源的議題
> [ASSIGNOR] Establish and release resource

- docs/web_server/web_api_balancer_chinese.md
> [DOC] Fix `web_api_balancer_chinese.md` documentation text alignment

- common/src/main/java/org/astraea/common/admin/AdminImpl.java
- common/src/main/java/org/astraea/common/admin/Partition.java
> [COMMON] rewrite admin.Partition by java 17 record

- docs/web_server/web_api_balancer_chinese.md
> [DOC] Revise `web_api_balancer_chinese.md` API configuration

- common/src/main/java/org/astraea/common/Configuration.java
- common/src/main/java/org/astraea/common/partitioner/PartitionerUtils.java
- common/src/test/java/org/astraea/common/ConfigurationTest.java
- fs/src/main/java/org/astraea/fs/hdfs/HdfsFileSystem.java
> [COMMON] cleanup Configuration

- common/src/main/java/org/astraea/common/admin/Offset.java
> [COMMON] rewrite admin.Offset by java 17 record

- common/src/main/java/org/astraea/common/admin/Transaction.java
- common/src/test/java/org/astraea/common/admin/AdminTest.java
> [COMMON] rewrite admin.Transaction by java 17 record

- app/src/test/java/org/astraea/app/performance/PerformanceTest.java
> [TEST] fix PerformanceTest#testNoProducer

- common/src/main/java/org/astraea/common/admin/ConsumerGroup.java
> [COMMON] rewrite ConsumerGroup by java 17 record

- common/src/main/java/org/astraea/common/metrics/broker/ClusterMetrics.java
> [METRICS] rewrite ClusterMetrics.PartitionMetric by java 17 record

- common/src/main/java/org/astraea/common/metrics/broker/ControllerMetrics.java
> [METRICS] rewrite ControllerMetrics.Gauge by java 17 record

- common/src/main/java/org/astraea/common/metrics/broker/NetworkMetrics.java
> [METRICS] rewrite NetworkMetrics by java 17 record

- common/src/main/java/org/astraea/common/metrics/platform/JvmMemory.java
related #1249 
移除StringBuilder方法，改成用字串直接拼接。
> [METRICS] rewrite JvmMemory toString by remove StringBuilder

- docs/web_server/web_api_balancer_chinese.md
> [DOC] Reformat `web_api_balancer_docs`

- connector/src/main/java/org/astraea/connector/SourceConnector.java
- connector/src/main/java/org/astraea/connector/SourceTask.java
- connector/src/main/java/org/astraea/connector/backup/Importer.java
> [CONNECTOR] rewrite source connect by java 17 record and toList

- common/src/main/java/org/astraea/common/ByteUtils.java
- common/src/main/proto/org/astraea/common/generated/BeanObject.proto
- common/src/test/java/org/astraea/common/serializer/BeanObjectSerializerTest.java
> [SERIALIZATION] Serialize `BeanObject#createdTimestampe`

- common/src/main/java/org/astraea/common/cost/utils/ClusterInfoSensor.java
提升 `ClusterInfoSensor#metricViewCluster` 的執行速度，程式碼實作內存在一些昂貴的排序和重複的查找，這個 PR 將他們稍微整理，避免不必要的計算。
針對 10000 個 replica 的叢集，原本的實作需要 50 秒才能計算完成，這個 PR 的修正將時間壓到大約 279 ms，大約是 179 倍的速度。
> [COST] Enhance performance for `ClusterInfoSensor`

- connector/src/main/java/org/astraea/connector/perf/PerfSource.java
> [CONNECTOR] rewrite PerfSource by java17 toList

- common/src/main/java/org/astraea/common/ByteUtils.java
- common/src/main/java/org/astraea/common/admin/OptimizedClusterInfo.java
- common/src/main/java/org/astraea/common/admin/Topic.java
> [COMMON] rewrite admin.Topic by java 17 record

- app/src/main/java/org/astraea/app/performance/MonkeyThread.java
- app/src/main/java/org/astraea/app/performance/ReportFormat.java
- app/src/main/java/org/astraea/app/web/BalancerHandler.java
- app/src/main/java/org/astraea/app/web/Channel.java
- app/src/main/java/org/astraea/app/web/Handler.java
- app/src/test/java/org/astraea/app/web/BalancerHandlerTest.java
- common/src/main/java/org/astraea/common/ByteUtils.java
- common/src/main/java/org/astraea/common/Utils.java
- common/src/main/java/org/astraea/common/backup/RecordReaderBuilder.java
- common/src/main/java/org/astraea/common/backup/RecordWriterBuilder.java
- common/src/main/java/org/astraea/common/cost/NetworkCost.java
- common/src/main/java/org/astraea/common/cost/NeutralIntegratedCost.java
- fs/src/main/java/org/astraea/fs/ftp/FtpFileSystem.java
- gui/src/main/java/org/astraea/gui/Query.java
- gui/src/main/java/org/astraea/gui/tab/BrokerNode.java
> [COMMON] rewrite switch by java 17 switch

- common/src/main/java/org/astraea/common/admin/AdminImpl.java
- common/src/main/java/org/astraea/common/admin/Broker.java
- common/src/test/java/org/astraea/common/cost/BrokerDiskSpaceCostTest.java
- common/src/test/java/org/astraea/common/cost/CostUtilsTest.java
1. 移除過時的 Kafka APIs
2. 根據 java 17 調整一些語法
> [COMMON] tweak Admin

- common/src/main/java/org/astraea/common/cost/RecordSizeCost.java
- common/src/main/java/org/astraea/common/cost/ReplicaLeaderCost.java
- common/src/main/java/org/astraea/common/cost/ReplicaLeaderSizeCost.java
- common/src/main/java/org/astraea/common/cost/ReplicaNumberCost.java
- common/src/test/java/org/astraea/common/UtilsTest.java
- common/src/test/java/org/astraea/common/balancer/algorithms/GreedyBalancerTest.java
- common/src/test/java/org/astraea/common/partitioner/StrictCostPartitionerTest.java
- connector/src/test/java/org/astraea/connector/ConnectorTest.java
> [COMMON] apply Configuration#EMPTY to code base

- connector/src/main/java/org/astraea/connector/SinkTask.java
- connector/src/main/java/org/astraea/connector/SinkTaskContext.java
- connector/src/main/java/org/astraea/connector/backup/Exporter.java
- connector/src/main/java/org/astraea/connector/perf/PerfSink.java
- connector/src/test/java/org/astraea/connector/perf/PerfSinkTest.java
#1802 漏掉了 `SinkTaskContext` ...
> [CONNECTOR] add SinkTaskContext to Connector

- docs/web_server/web_api_balancer_chinese.md
> [DOCS] Fix typo in `web_api_balancer_chinese.md`

- docker/start_broker.sh
- docker/start_controller.sh
- docker/start_worker.sh
- gradle/dependencies.gradle
as title
合併後會更新所有 docker image
> [COMMON] upgrade kafka from 3.4.0 to 3.4.1

- common/src/main/java/org/astraea/common/Utils.java
- common/src/main/java/org/astraea/common/json/JsonConverter.java
- common/src/test/java/org/astraea/common/json/JsonConverterTest.java
resolve https://github.com/skiptests/astraea/issues/1430
> Add duration string formatter

- docker/start_broker.sh
- docker/start_controller.sh
- docker/start_worker.sh
- gradle/dependencies.gradle
- it/src/main/java/org/astraea/it/BrokerCluster.java
- it/src/main/java/org/astraea/it/WorkerCluster.java
> [COMMON] upgrade kafka from 3.4.1 to 3.5.0

- docker/build_deps_image.sh
> [DOCKER] fix the broken GRADLE url

- connector/src/main/java/org/astraea/connector/backup/Exporter.java
- connector/src/test/java/org/astraea/connector/backup/ExporterTest.java
> [EXPORTER] fix typo: targeOffset -> targetOffset

- gradle/wrapper/gradle-wrapper.properties
- gradlew
> [COMMON] upgrade gradle from 8.1.1 to 8.2.1

- docker/start_broker.sh
- docker/start_controller.sh
- docker/start_worker.sh
- gradle/dependencies.gradle
> [COMMON] upgrade kafka from 3.5.0 to 3.5.1

- common/src/main/java/org/astraea/common/balancer/algorithms/GreedyBalancer.java
- common/src/test/java/org/astraea/common/balancer/algorithms/GreedyBalancerTest.java
紀錄 balancer 計算的計畫數量，並將之暴露在 Jmx MBean 上。
> [BALANCER] Expose number of plans generated

- gradle/wrapper/gradle-wrapper.properties
- gradlew
> [COMMON] Upgrade gradle from 8.2.1 to 8.6

- docker/build_deps_image.sh
- docker/start_app.sh
- docker/start_broker.sh
- docker/start_controller.sh
- docker/start_hadoop.sh
- docker/start_spark.sh
- docker/start_worker.sh
- docker/start_zookeeper.sh
> [COMMON] update ubuntu from 22.04 to 23.10

- config/kafka_changelog.json
This PR aims to add a checker for protocol baseline changes
> [CHECKER] Add baseline checker for protocols

- app/src/main/java/org/astraea/app/checker/Config.java
- app/src/main/java/org/astraea/app/checker/ConfigGuard.java
This PR implements `ConfigGuard`
> [CHECKER] Implement ConfigGuard

- docker/start_kafka.sh
command `ip` not support in MacOs.
extract to a function.
`,,` syntax has been supported since bash 4.0.
after update, we can run ./start_kafka.sh in MacOs
> Enhanced shell OS compatibility
